import type { SkillJourneyDefinition } from "@anuma/sdk";

const US_STATES = [
  "AL",
  "AK",
  "AZ",
  "AR",
  "CA",
  "CO",
  "CT",
  "DE",
  "DC",
  "FL",
  "GA",
  "HI",
  "ID",
  "IL",
  "IN",
  "IA",
  "KS",
  "KY",
  "LA",
  "ME",
  "MD",
  "MA",
  "MI",
  "MN",
  "MS",
  "MO",
  "MT",
  "NE",
  "NV",
  "NH",
  "NJ",
  "NM",
  "NY",
  "NC",
  "ND",
  "OH",
  "OK",
  "OR",
  "PA",
  "RI",
  "SC",
  "SD",
  "TN",
  "TX",
  "UT",
  "VT",
  "VA",
  "WA",
  "WV",
  "WI",
  "WY",
];

function outputFormatBlock(lengthGuidance: string): string[] {
  return [
    "",
    "## Output format",
    "Lead with a 2–3 sentence executive summary.",
    "Use ## headings to separate major sections.",
    "Keep each finding to 2–4 lines: state the issue, cite the law, and give the risk level.",
    "Use tables only when comparing items (e.g. fees, costs). Avoid decorative tables.",
    "End with a prioritized action list — most urgent first.",
    lengthGuidance,
  ];
}

export const HAVEN_SKILL_JOURNEYS: Record<string, SkillJourneyDefinition> = {
  "housing.lease-review": {
    title: "Lease review",
    description:
      "Haven reviews a lease for red flags, fee traps, ambiguous clauses, and state-specific tenant protections.",
    steps: [
      "Add your state and paste the lease text or upload the PDF.",
      "Haven highlights risks clause by clause.",
      "Keep chatting to ask about specific sections.",
    ],
    acceptsFiles: true,
    fileLabel: "Upload a lease PDF",
    fileHint:
      "If the lease is scanned or very long, upload the PDF and use the notes field to point Haven to the most important sections.",
    fields: [
      {
        key: "home_type",
        label: "Home type",
        placeholder: "Select your home type",
        helper: "Helps Haven identify red flags specific to your housing type.",
        type: "select",
        required: false,
        options: [
          "Apartment",
          "Condo",
          "Single-family home",
          "Multi-family home",
          "Townhouse",
          "Co-op",
          "Other",
        ],
      },
      {
        key: "state",
        label: "State",
        placeholder: "Select your state",
        helper: "Required for state-specific lease rules.",
        type: "select",
        required: true,
        options: US_STATES,
      },
      {
        key: "lease_text",
        label: "Paste lease terms",
        placeholder:
          "Paste lease text, key clauses, or the sections you want Haven to review first.",
        helper: "Use this instead of upload, or add context for the attached lease.",
        type: "textarea",
        required: false,
      },
    ],
    requiresContext: true,
    submitLabel: "Review in Haven chat",
    promptTitle: "Review this lease for red flags, tenant-risk clauses, and hidden fees",
    systemContext: [
      "Parse the lease clause by clause and cross-reference each clause with the state tenant protection laws provided.",
      "",
      "Flag any clauses that are:",
      "- Illegal or unenforceable under state law",
      "- Unusual or heavily favor the landlord",
      "- Missing standard protections required by law",
      "",
      "For each red flag, cite the specific state statute or regulation.",
      "Provide a risk rating: HIGH / MEDIUM / LOW for each issue.",
      "",
      "Organize findings into these sections:",
      "1. Red flags and problematic clauses (with clause number/section references)",
      "2. Financial obligations (rent, deposits, fees, penalties)",
      "3. Maintenance and repair responsibilities",
      "4. Termination and renewal terms",
      "5. Tenant rights that may be missing or limited",
      "",
      "End with an overall risk assessment and recommended actions.",
      "Use web search to verify current state landlord-tenant law statutes when needed.",
      ...outputFormatBlock("Target 1000–1500 words. Be precise, not exhaustive."),
    ].join("\n"),
  },
  "housing.rent-increase-checker": {
    title: "Rent increase check",
    description:
      "Haven checks whether a rent increase looks lawful and drafts a negotiation plan with local context.",
    steps: [
      "Enter your city, state, current rent, and proposed rent.",
      "Haven checks the increase and outlines leverage.",
      "Refine the reply in chat.",
    ],
    acceptsFiles: false,
    fields: [
      {
        key: "city",
        label: "City",
        placeholder: "San Francisco",
        helper: "Required for local rent rules and market context.",
        type: "text",
        required: true,
      },
      {
        key: "state",
        label: "State",
        placeholder: "Select your state",
        helper: "Required.",
        type: "select",
        required: true,
        options: US_STATES,
      },
      {
        key: "current_rent",
        label: "Current rent",
        placeholder: "$2,900",
        helper: "Required.",
        type: "text",
        required: true,
      },
      {
        key: "proposed_rent",
        label: "Proposed rent",
        placeholder: "$3,250",
        helper: "Required.",
        type: "text",
        required: true,
      },
    ],
    requiresContext: false,
    submitLabel: "Check increase in chat",
    promptTitle: "Check whether this rent increase is legal and help me respond",
    systemContext: [
      "Research the city and state rent control laws and local ordinances.",
      "",
      "1. Determine if the increase is within legal limits (if rent control applies)",
      "2. Check if proper notice was given per state law",
      "3. Research comparable market rates in the area",
      "4. Assess whether the increase is legally challengeable",
      "5. If challengeable: draft a response letter citing specific laws",
      "6. If legal but high: provide negotiation talking points and comparable data",
      "",
      "Include specific statute references and deadlines for tenant response.",
      "Provide specific dollar amounts and percentages where relevant.",
      ...outputFormatBlock("Target 600–1000 words. Be precise, not exhaustive."),
    ].join("\n"),
  },
  "housing.demand-letter": {
    title: "Demand letter draft",
    description:
      "Haven drafts a professional demand letter with a clear timeline, requested remedy, and a cleaner tone than starting from scratch.",
    steps: [
      "Add the parties, property, state, and issue details.",
      "Haven drafts a structured letter in chat.",
      "Revise tone or legal emphasis with follow-up messages.",
    ],
    acceptsFiles: false,
    fields: [
      {
        key: "tenant_name",
        label: "Tenant name",
        placeholder: "Jane Doe",
        helper: "Required.",
        type: "text",
        required: true,
      },
      {
        key: "landlord_name",
        label: "Landlord name",
        placeholder: "Property manager or landlord",
        helper: "Required.",
        type: "text",
        required: true,
      },
      {
        key: "property_address",
        label: "Property address",
        placeholder: "123 Main St, Austin, TX",
        helper: "Required.",
        type: "text",
        required: true,
      },
      {
        key: "landlord_address",
        label: "Landlord/management address",
        placeholder: "Registered business address",
        helper:
          "The landlord or management company registered address for the demand letter header.",
        type: "text",
        required: false,
      },
      {
        key: "state",
        label: "State",
        placeholder: "Select your state",
        helper: "Required.",
        type: "select",
        required: true,
        options: US_STATES,
      },
      {
        key: "issue_description",
        label: "What needs to be fixed?",
        placeholder: "Describe the issue, timeline, prior requests, and what remedy you want.",
        helper: "Required.",
        type: "textarea",
        required: true,
      },
    ],
    requiresContext: false,
    submitLabel: "Draft letter in chat",
    promptTitle: "Draft a professional demand letter from these details",
    systemContext: [
      "Research the state landlord-tenant law relevant to this issue.",
      "Identify the specific legal violations or obligations.",
      "",
      "Draft a formal demand letter that:",
      "- States the facts clearly and chronologically",
      "- Cites specific state statutes that apply",
      "- Clearly states what is being demanded",
      "- Sets a reasonable deadline for response (per state law requirements)",
      "- Notes potential legal remedies if demands are not met",
      "- Maintains a professional, firm tone",
      "",
      "Include proper formatting: date, addresses, RE line, signature block.",
      "Add a brief legal analysis section explaining the tenant rights involved.",
      "Use web search to verify current state statutes and remedies when needed.",
      ...outputFormatBlock(
        "The letter itself should be 400–600 words. Add a brief legal analysis section (200–300 words) after the letter."
      ),
    ].join("\n"),
  },
  "housing.hoa-dispute": {
    title: "HOA dispute response",
    description:
      "Haven reviews an HOA notice and drafts a response strategy that is firm, organized, and easier to send.",
    steps: [
      "Add your state, HOA name, and dispute type.",
      "Paste or upload the HOA notice.",
      "Get a reply draft and follow-up plan in chat.",
    ],
    acceptsFiles: true,
    fileLabel: "Upload HOA notice",
    fileHint: "Attach the notice, violation letter, screenshots, or supporting docs.",
    fields: [
      {
        key: "state",
        label: "State",
        placeholder: "Select your state",
        helper: "Required.",
        type: "select",
        required: true,
        options: US_STATES,
      },
      {
        key: "hoa_name",
        label: "HOA name",
        placeholder: "Community or association name",
        helper: "Required.",
        type: "text",
        required: true,
      },
      {
        key: "issue_type",
        label: "Dispute type",
        placeholder: "Fine appeal, rule violation, maintenance dispute",
        helper: "Required.",
        type: "text",
        required: true,
      },
      {
        key: "hoa_notice",
        label: "Paste the HOA notice or your notes",
        placeholder: "Paste the notice text or summarize the dispute.",
        helper: "If the full notice is uploaded, add any extra context Haven should know.",
        type: "textarea",
        required: false,
      },
    ],
    requiresContext: true,
    submitLabel: "Draft response in chat",
    promptTitle: "Review this HOA issue and draft a formal response",
    systemContext: [
      "Analyze the HOA's notice or violation for procedural correctness.",
      "Research the state HOA law (e.g., Common Interest Development Act, HOA Bill of Rights).",
      "",
      "Cross-reference the HOA's action with:",
      "- State HOA statutes",
      "- The CC&Rs provisions cited",
      "- Required procedures for notices, hearings, and fines",
      "",
      "Identify any procedural failures or overreach by the HOA.",
      "",
      "Draft a formal response that:",
      "- Addresses each point in the HOA notice",
      "- Cites specific state law protections",
      "- References relevant CC&R provisions",
      "- Requests specific remedies (hearing, reversal, mediation)",
      "- Notes the homeowner's rights under state law",
      "",
      "Include escalation path: internal appeal, mediation, small claims, civil court.",
      "Use web search to verify current state HOA statutes when needed.",
      ...outputFormatBlock("Target 800–1200 words. Be precise, not exhaustive."),
    ].join("\n"),
  },
};
