/**
 * One-time script to generate centroid vectors for the weather classifier.
 *
 * Embeds the reference phrases, averages each class into a single centroid,
 * and writes the result to src/lib/chat/weatherCentroids.ts.
 *
 * Usage:
 *   PORTAL_API_KEY=... npx tsx scripts/generateWeatherCentroids.ts
 */

import "dotenv/config";
import { writeFileSync } from "fs";
import { resolve } from "path";

import { BASE_URL } from "../src/clientConfig";
import { generateEmbeddings } from "../src/lib/memoryEngine/embeddings";
import { averageVectors } from "./lib/centroids";
import { GENERIC_NEGATIVE_PHRASES } from "./lib/genericNegatives";

const WEATHER_PHRASES = [
  // Forecasts
  "What's the weather in San Francisco today",
  "Will it rain in New York this weekend",
  "Weather forecast for Tokyo tomorrow",
  "Is it going to be sunny in Paris on Saturday",
  "What's the weekly forecast for Berlin",
  "Will there be snow in Denver next week",
  "5-day forecast for Miami",
  "Will it be cold in Chicago tonight",

  // Temperature
  "What's the temperature in Dubai right now",
  "How hot is it in Phoenix",
  "Current temperature in London",
  "Will it freeze tomorrow in Helsinki",
  "What's the high today in Madrid",
  "Heat index in Houston",

  // Precipitation / conditions
  "Is it raining in Seattle right now",
  "Will it snow in Aspen this week",
  "Chance of thunderstorms in Atlanta tomorrow",
  "Cloud cover in Reykjavik",
  "Is it humid in Singapore today",
  "Will there be fog in San Francisco tonight",

  // Wind / sun
  "Wind speed in Wellington",
  "What time is sunrise in Iceland today",
  "Sunset time in Tokyo",
  "UV index in Sydney right now",
  "Is it windy in Chicago today",

  // Air quality
  "What is the air quality in Beijing",
  "AQI in Los Angeles right now",
  "Pollution levels in Delhi today",
  "PM2.5 levels in Shanghai",

  // Marine / flood / specialty
  "Tide times in San Diego today",
  "Wave height at Mavericks",
  "Flood risk in Houston tomorrow",
  "River discharge in the Rhine",
  "Sea temperature off Florida",
  "Marine forecast for the Gulf of Mexico",

  // Climate / historical weather
  "Historical weather in Rome last July",
  "What was the temperature in Cairo last year",
  "Climate projection for Sao Paulo by 2050",

  // Short / conversational
  "weather tomorrow",
  "forecast Paris",
  "rain today",
  "temperature outside",
];

const NO_WEATHER_PHRASES = [
  // Crypto / stock / finance — must NOT trigger weather
  "What is the current price of Bitcoin",
  "How much is Tesla stock worth today",
  "USD to EUR exchange rate",
  "S&P 500 today",
  "Market cap of Ethereum",

  // Weather-adjacent reasoning but NOT a forecast
  "How does the water cycle work",
  "Why does it rain",
  "Explain how hurricanes form",
  "What is the difference between weather and climate",
  "How do weather satellites work",
  "What causes the seasons",
  "Why is the sky blue",

  // Generic out-of-domain negatives shared with other classifiers.
  ...GENERIC_NEGATIVE_PHRASES,

  // Other current-data web searches
  "What did Elon Musk tweet about today",
  "Who won the Super Bowl this year",
  "Find Italian restaurants near me",
];

async function main() {
  const apiKey = process.env.PORTAL_API_KEY;
  const baseUrl = process.env.ANUMA_API_URL || BASE_URL;

  if (!apiKey) {
    console.error("PORTAL_API_KEY is required");
    process.exit(1);
  }

  console.log(`Using baseUrl: ${baseUrl}`);
  console.log("Embedding weather phrases...");
  const weatherEmbeddings = await generateEmbeddings(WEATHER_PHRASES, { apiKey, baseUrl });

  console.log("Embedding no-weather phrases...");
  const noWeatherEmbeddings = await generateEmbeddings(NO_WEATHER_PHRASES, { apiKey, baseUrl });

  const weatherCentroid = averageVectors(weatherEmbeddings);
  const noWeatherCentroid = averageVectors(noWeatherEmbeddings);

  console.log(`Dimensions: ${weatherCentroid.length}`);

  const output = `/**
 * Pre-computed centroid vectors for the weather classifier.
 *
 * Generated by: npx tsx scripts/generateWeatherCentroids.ts
 *
 * weatherCentroid: average embedding of phrases representing "needs weather data" intent.
 * noWeatherCentroid: average embedding of phrases representing "no weather needed" intent.
 *
 * At runtime the classifier only needs to embed the user prompt and compute
 * two cosine similarities — no reference phrase embedding calls needed.
 *
 * Note: depending on which floats land in this regen, ESLint's
 * \`no-loss-of-precision\` rule may fire on the literal array below. If lint
 * complains, add \`/* eslint-disable no-loss-of-precision *\\/\` above the
 * \`export const\` line — but don't add it pre-emptively, because the
 * \`reportUnusedDisableDirectives\` check will then fail when the regen happens
 * to produce safe floats.
 */

// prettier-ignore
export const weatherCentroid: number[] = ${JSON.stringify(weatherCentroid)};

// prettier-ignore
export const noWeatherCentroid: number[] = ${JSON.stringify(noWeatherCentroid)};
`;

  const outPath = resolve(__dirname, "../src/lib/chat/weatherCentroids.ts");
  writeFileSync(outPath, output, "utf-8");
  console.log(`Written to ${outPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
