/**
 * Catalog of slide layout templates used by `buildSlideSystemPrompt` in
 * `./index.ts`. Templates hold typed element data in the legacy canvas-percent
 * coordinate system — at render time it's converted to pixel-based JSX for
 * the LLM prompt. The LLM then emits pixel-based JSX directly (matching the
 * unified slide + app-mockup vocabulary); this file stays in percent form
 * because most of the existing 3k lines of template data was hand-tuned
 * against that grid.
 */

// ---------------------------------------------------------------------------
// Local layout-element types (formerly the external SlideElement union;
// dropped from the public API as part of the AST migration — layouts keep
// their own shape since it's strictly a build-time DSL for LLM prompts).
// ---------------------------------------------------------------------------

interface BaseEl {
  id: string;
  x: number;
  y: number;
  w: number;
  h: number;
  rotation?: number;
}

interface TextLayoutEl extends BaseEl {
  kind: "text";
  text: string;
  fontSize: number;
  fontRole: "heading" | "body";
  fontWeight: number;
  color: string;
  align?: "left" | "center" | "right";
  lineHeight?: number;
  letterSpacing?: number;
  fontStyle?: "italic" | "normal";
  textTransform?: "uppercase" | "none";
  fontFamily?: string;
}

interface ImageLayoutEl extends BaseEl {
  kind: "image";
  src: string;
  cornerRadius?: number;
}

interface ShapeLayoutEl extends BaseEl {
  kind: "shape";
  shape: "rect" | "circle" | "line";
  fill?: string;
  stroke?: string;
  strokeWidth?: number;
  cornerRadius?: number;
}

interface IconLayoutEl extends BaseEl {
  kind: "icon";
  name: string;
  color: string;
  fontSize: number;
}

type LayoutEl = TextLayoutEl | ImageLayoutEl | ShapeLayoutEl | IconLayoutEl;

/** Backwards-name alias so existing helpers keep their old return type. */
type SlideElement = LayoutEl;

// ---------------------------------------------------------------------------
// Canvas dimensions — percentages in this file convert to pixels at emit time.
// ---------------------------------------------------------------------------

const CANVAS_W = 960;
const CANVAS_H = 540;
const pxX = (pct: number) => round2(pct * (CANVAS_W / 100));
const pxY = (pct: number) => round2(pct * (CANVAS_H / 100));
const pxFontSize = (pct: number) => round2(pct * (CANVAS_W / 100));
const pxW = pxX;
const pxH = pxY;
function round2(n: number): number {
  return Math.round(n * 100) / 100;
}

interface LayoutTemplate {
  /**
   * Short kebab-case identifier the LLM returns in `plan_slides`. Kept
   * short + typo-proof so the model can match it exactly without fuzzy
   * matching. Must be unique across templates.
   */
  name: string;
  /**
   * One-line human description rendered alongside the name in the
   * catalog and picker rubric. Explains what the layout is for and when
   * to reach for it. The LLM sees this but doesn't have to echo it back.
   */
  description: string;
  /**
   * Free-form hints that don't fit as elements. Rendered before the
   * element list in the prompt. Use for things like "set slide.background"
   * or "use '• ' prefix for each bullet line".
   */
  notes?: string[];
  /**
   * Reference elements with real coordinates + example content. The LLM
   * is told to copy the shape and substitute its own text values.
   */
  elements: SlideElement[];
}

// ---------------------------------------------------------------------------
// Helpers — keep per-template definitions compact
// ---------------------------------------------------------------------------

/** Mono uppercase label (eyebrow / chrome metadata). */
function eyebrow(
  id: string,
  text: string,
  x: number,
  y: number,
  w: number,
  opts: {
    color?: string;
    fontSize?: number;
    letterSpacing?: number;
    align?: "left" | "center" | "right";
  } = {}
): SlideElement {
  return {
    id,
    kind: "text",
    x,
    y,
    w,
    h: 3.5,
    text,
    fontSize: opts.fontSize ?? 1.4,
    fontRole: "body",
    fontWeight: 500,
    color: opts.color ?? "textMuted",
    fontFamily: "JetBrains Mono",
    letterSpacing: opts.letterSpacing ?? 0.16,
    textTransform: "uppercase",
    align: opts.align ?? "left",
  };
}

/** Horizontal hairline rule — 1px line spanning the full content area (x=6..94). */
function hrule(id: string, y: number, strokeWidth = 1): SlideElement {
  return {
    id,
    kind: "shape",
    x: 6,
    y,
    w: 88,
    h: 0,
    shape: "line",
    stroke: "border",
    strokeWidth,
  };
}

/**
 * Horizontal hairline rule spanning a single column. Use this when a layout
 * has two columns of content and the rules should only separate rows within
 * one column (not slice across the other).
 */
function hruleCol(id: string, x: number, y: number, w: number, strokeWidth = 1): SlideElement {
  return {
    id,
    kind: "shape",
    x,
    y,
    w,
    h: 0,
    shape: "line",
    stroke: "border",
    strokeWidth,
  };
}

/** Narrow vertical divider (uses a rect since line shape is horizontal-only). */
function vdiv(id: string, x: number, y: number, h: number): SlideElement {
  return {
    id,
    kind: "shape",
    x,
    y,
    w: 0.1,
    h,
    shape: "rect",
    fill: "border",
  };
}

// ---------------------------------------------------------------------------
// Templates
// ---------------------------------------------------------------------------

export const LAYOUT_TEMPLATES: LayoutTemplate[] = [
  {
    name: "cover-centered",
    description: "Cover slide: big centered title with centered subtitle below.",
    elements: [
      {
        id: "title",
        kind: "text",
        x: 7.5,
        y: 30,
        w: 85,
        h: 20,
        text: "Title Here",
        fontSize: 4.5,
        fontRole: "heading",
        fontWeight: 700,
        color: "textPrimary",
        align: "center",
      },
      {
        id: "subtitle",
        kind: "text",
        x: 19,
        y: 55,
        w: 62,
        h: 8,
        text: "Subtitle here",
        fontSize: 2.3,
        fontRole: "heading",
        fontWeight: 500,
        color: "textSecondary",
        align: "center",
      },
    ],
  },

  {
    name: "cover-accent-bar",
    description: "Cover slide: left-aligned title with a short accent-colored bar above it.",
    elements: [
      {
        id: "bar",
        kind: "shape",
        x: 6,
        y: 26,
        w: 5,
        h: 0.6,
        shape: "rect",
        fill: "accent",
        cornerRadius: 0.2,
      },
      {
        id: "title",
        kind: "text",
        x: 6,
        y: 30,
        w: 88,
        h: 24,
        text: "Title Here",
        fontSize: 4.5,
        fontRole: "heading",
        fontWeight: 700,
        color: "textPrimary",
        align: "left",
      },
      {
        id: "subtitle",
        kind: "text",
        x: 6,
        y: 56,
        w: 88,
        h: 9,
        text: "Subtitle here",
        fontSize: 2.3,
        fontRole: "heading",
        fontWeight: 500,
        color: "textSecondary",
        align: "left",
      },
    ],
  },

  {
    name: "cover-bottom",
    description:
      "Cover slide: huge editorial title anchored to the bottom, mono metadata eyebrow at top.",
    elements: [
      eyebrow("meta", "META · 2024", 6, 7, 30, { fontSize: 1.4 }),
      {
        id: "title",
        kind: "text",
        x: 6,
        y: 68,
        w: 88,
        h: 26,
        text: "Huge Title Here",
        fontSize: 6.5,
        fontRole: "heading",
        fontWeight: 700,
        color: "textPrimary",
        align: "left",
      },
    ],
  },

  {
    name: "section-dark",
    description: "Dark chapter break — a rhythm marker between parts of a multi-part deck.",
    notes: [
      `Set slide.background to a dark hex (e.g. "#1F2A22", "#1a1b1e") so this slide reads as a tonal shift from content slides.`,
    ],
    elements: [
      eyebrow("eyebrow", "CHAPTER TWO", 6, 55, 40, { color: "accent" }),
      {
        id: "title",
        kind: "text",
        x: 6,
        y: 61,
        w: 88,
        h: 26,
        text: "Timing is\nhalf the game.",
        fontSize: 7.5,
        fontRole: "heading",
        fontWeight: 400,
        color: "#EDE6D8",
        fontStyle: "italic",
        align: "left",
        lineHeight: 1.02,
      },
      {
        id: "subtitle",
        kind: "text",
        x: 6,
        y: 89,
        w: 82,
        h: 7,
        text: "Supporting line at the bottom.",
        fontSize: 1.8,
        fontRole: "body",
        fontWeight: 400,
        color: "#B8BEB3",
        align: "left",
        lineHeight: 1.3,
      },
    ],
  },

  {
    name: "agenda-cards",
    description:
      "Three enclosed rectangles side by side, each with a mono label + heading + body. For 3-part outlines, Step 01/02/03, feature rundowns.",
    notes: [
      "Use for 3-part outlines (Part I/II/III), process steps (Step 01/02/03), or feature rundowns. Each card is a fully enclosed rect with a 1px border — unlike STATS hairline cells which share a grid rail. Include the shared header above.",
    ],
    elements: [
      {
        id: "c1_box",
        kind: "shape",
        shape: "rect",
        x: 6,
        y: 42,
        w: 28,
        h: 44,
        stroke: "border",
        strokeWidth: 1,
        cornerRadius: 0.4,
      },
      {
        id: "c1_label",
        kind: "text",
        x: 9,
        y: 47,
        w: 22,
        h: 3.5,
        text: "PART I",
        fontSize: 1.4,
        fontRole: "body",
        fontWeight: 500,
        color: "accent",
        fontFamily: "JetBrains Mono",
        letterSpacing: 0.16,
        textTransform: "uppercase",
      },
      {
        id: "c1_heading",
        kind: "text",
        x: 9,
        y: 53,
        w: 22,
        h: 10,
        text: "The phenomenon",
        fontSize: 2.6,
        fontRole: "heading",
        fontWeight: 400,
        color: "textPrimary",
        lineHeight: 1.15,
      },
      {
        id: "c1_body",
        kind: "text",
        x: 9,
        y: 66,
        w: 22,
        h: 16,
        text: "Two particles that behave as one, no matter how far apart.",
        fontSize: 1.6,
        fontRole: "body",
        fontWeight: 400,
        color: "textSecondary",
        lineHeight: 1.5,
      },
      {
        id: "c2_box",
        kind: "shape",
        shape: "rect",
        x: 36,
        y: 42,
        w: 28,
        h: 44,
        stroke: "border",
        strokeWidth: 1,
        cornerRadius: 0.4,
      },
      {
        id: "c2_label",
        kind: "text",
        x: 39,
        y: 47,
        w: 22,
        h: 3.5,
        text: "PART II",
        fontSize: 1.4,
        fontRole: "body",
        fontWeight: 500,
        color: "accent",
        fontFamily: "JetBrains Mono",
        letterSpacing: 0.16,
        textTransform: "uppercase",
      },
      {
        id: "c2_heading",
        kind: "text",
        x: 39,
        y: 53,
        w: 22,
        h: 10,
        text: "The argument",
        fontSize: 2.6,
        fontRole: "heading",
        fontWeight: 400,
        color: "textPrimary",
        lineHeight: 1.15,
      },
      {
        id: "c2_body",
        kind: "text",
        x: 39,
        y: 66,
        w: 22,
        h: 16,
        text: "From Einstein's 1935 skepticism to a 2022 Nobel Prize.",
        fontSize: 1.6,
        fontRole: "body",
        fontWeight: 400,
        color: "textSecondary",
        lineHeight: 1.5,
      },
      {
        id: "c3_box",
        kind: "shape",
        shape: "rect",
        x: 66,
        y: 42,
        w: 28,
        h: 44,
        stroke: "border",
        strokeWidth: 1,
        cornerRadius: 0.4,
      },
      {
        id: "c3_label",
        kind: "text",
        x: 69,
        y: 47,
        w: 22,
        h: 3.5,
        text: "PART III",
        fontSize: 1.4,
        fontRole: "body",
        fontWeight: 500,
        color: "accent",
        fontFamily: "JetBrains Mono",
        letterSpacing: 0.16,
        textTransform: "uppercase",
      },
      {
        id: "c3_heading",
        kind: "text",
        x: 69,
        y: 53,
        w: 22,
        h: 10,
        text: "The useful part",
        fontSize: 2.6,
        fontRole: "heading",
        fontWeight: 400,
        color: "textPrimary",
        lineHeight: 1.15,
      },
      {
        id: "c3_body",
        kind: "text",
        x: 69,
        y: 66,
        w: 22,
        h: 16,
        text: "Faster computers, unbreakable keys, new networks.",
        fontSize: 1.6,
        fontRole: "body",
        fontWeight: 400,
        color: "textSecondary",
        lineHeight: 1.5,
      },
    ],
  },

  {
    name: "text-prose",
    description: "Heading + long prose body — for running explanatory text.",
    elements: [
      {
        id: "heading",
        kind: "text",
        x: 6,
        y: 10,
        w: 88,
        h: 10,
        text: "Heading",
        fontSize: 3,
        fontRole: "heading",
        fontWeight: 600,
        color: "textPrimary",
        align: "left",
      },
      {
        id: "body",
        kind: "text",
        x: 6,
        y: 23,
        w: 66,
        h: 65,
        text: "Prose body text.",
        fontSize: 1.9,
        fontRole: "body",
        fontWeight: 400,
        color: "textSecondary",
        align: "left",
        lineHeight: 1.8,
      },
    ],
  },

  {
    name: "text-bullets",
    description: "Heading + a clean bullet list (≤ 6 items with short descriptions).",
    notes: [`Use "• " prefix for each bullet line inside the "bullets" text.`],
    elements: [
      {
        id: "heading",
        kind: "text",
        x: 6,
        y: 9,
        w: 88,
        h: 10,
        text: "Heading",
        fontSize: 3,
        fontRole: "heading",
        fontWeight: 600,
        color: "accent",
        align: "left",
      },
      {
        id: "bullets",
        kind: "text",
        x: 6,
        y: 22,
        w: 88,
        h: 68,
        text: "• First point\n• Second point\n• Third point",
        fontSize: 1.9,
        fontRole: "body",
        fontWeight: 400,
        color: "textSecondary",
        align: "left",
        lineHeight: 1.75,
      },
    ],
  },

  {
    name: "text-two-col",
    description: "Two-column layout: heading on the left, running content on the right.",
    elements: [
      {
        id: "heading",
        kind: "text",
        x: 6,
        y: 9,
        w: 33,
        h: 82,
        text: "HEADING",
        fontSize: 3.3,
        fontRole: "heading",
        fontWeight: 700,
        color: "accent",
        align: "left",
        textTransform: "uppercase",
      },
      {
        id: "body",
        kind: "text",
        x: 43,
        y: 9,
        w: 51,
        h: 82,
        text: "Body text in the right column.",
        fontSize: 1.9,
        fontRole: "body",
        fontWeight: 400,
        color: "textSecondary",
        align: "left",
        lineHeight: 1.7,
      },
    ],
  },

  {
    name: "text-three-col",
    description:
      "Three lightweight text columns — each a mono label + serif heading + body. No borders, no hairline grid. For taxonomies, tier comparisons, before/during/after prose breakdowns.",
    notes: ["Include the shared header above."],
    elements: [
      {
        id: "c1_label",
        kind: "text",
        x: 6,
        y: 32,
        w: 27,
        h: 3.5,
        text: "EAST EGG",
        fontSize: 1.3,
        fontRole: "body",
        fontWeight: 500,
        color: "accent",
        fontFamily: "JetBrains Mono",
        letterSpacing: 0.14,
        textTransform: "uppercase",
      },
      {
        id: "c1_heading",
        kind: "text",
        x: 6,
        y: 38,
        w: 27,
        h: 10,
        text: "Old Money",
        fontSize: 3.2,
        fontRole: "heading",
        fontWeight: 500,
        color: "textPrimary",
        lineHeight: 1.1,
      },
      {
        id: "c1_body",
        kind: "text",
        x: 6,
        y: 50,
        w: 27,
        h: 34,
        text: "Tom and Daisy. Inheritance, tennis, careless cruelty. Manners that look like virtue and aren't. They break people and things and retreat back into their money.",
        fontSize: 1.6,
        fontRole: "body",
        fontWeight: 400,
        color: "textSecondary",
        lineHeight: 1.5,
      },
      {
        id: "c2_label",
        kind: "text",
        x: 36,
        y: 32,
        w: 27,
        h: 3.5,
        text: "WEST EGG",
        fontSize: 1.3,
        fontRole: "body",
        fontWeight: 500,
        color: "accent",
        fontFamily: "JetBrains Mono",
        letterSpacing: 0.14,
        textTransform: "uppercase",
      },
      {
        id: "c2_heading",
        kind: "text",
        x: 36,
        y: 38,
        w: 27,
        h: 10,
        text: "New Money",
        fontSize: 3.2,
        fontRole: "heading",
        fontWeight: 500,
        color: "textPrimary",
        lineHeight: 1.1,
      },
      {
        id: "c2_body",
        kind: "text",
        x: 36,
        y: 50,
        w: 27,
        h: 34,
        text: "Gatsby. A mansion that imitates a chateau, a library of uncut books, pink suits. Performance as hope. The novel's sympathy lives here — and so does its pity.",
        fontSize: 1.6,
        fontRole: "body",
        fontWeight: 400,
        color: "textSecondary",
        lineHeight: 1.5,
      },
      {
        id: "c3_label",
        kind: "text",
        x: 66,
        y: 32,
        w: 28,
        h: 3.5,
        text: "VALLEY OF ASHES",
        fontSize: 1.3,
        fontRole: "body",
        fontWeight: 500,
        color: "accent",
        fontFamily: "JetBrains Mono",
        letterSpacing: 0.14,
        textTransform: "uppercase",
      },
      {
        id: "c3_heading",
        kind: "text",
        x: 66,
        y: 38,
        w: 28,
        h: 10,
        text: "No Money",
        fontSize: 3.2,
        fontRole: "heading",
        fontWeight: 500,
        color: "textPrimary",
        lineHeight: 1.1,
      },
      {
        id: "c3_body",
        kind: "text",
        x: 66,
        y: 50,
        w: 28,
        h: 34,
        text: "The Wilsons. The gray mid-distance the wealthy drive through and ignore. The place the plot ultimately arranges to pay for everyone else's appetites.",
        fontSize: 1.6,
        fontRole: "body",
        fontWeight: 400,
        color: "textSecondary",
        lineHeight: 1.5,
      },
    ],
  },

  {
    name: "profile-spec",
    description:
      "Case study / spec sheet: label + big title + body on the left, 6 key-value datum rows with hairlines on the right. For product profiles, feature rundowns, comparisons by attribute.",
    notes: [
      "Include the shared header above. Six key-value rows with hairline rules between them.",
    ],
    elements: [
      {
        id: "left_label",
        kind: "text",
        x: 6,
        y: 32,
        w: 40,
        h: 3.5,
        text: "CASE I · 1935",
        fontSize: 1.4,
        fontRole: "body",
        fontWeight: 500,
        color: "accent",
        fontFamily: "JetBrains Mono",
        letterSpacing: 0.14,
        textTransform: "uppercase",
      },
      {
        id: "left_title",
        kind: "text",
        x: 6,
        y: 37,
        w: 40,
        h: 22,
        text: "A square track, a dice cup, a ledger.",
        fontSize: 4.5,
        fontRole: "heading",
        fontWeight: 400,
        color: "textPrimary",
        align: "left",
        lineHeight: 1.05,
      },
      {
        id: "left_body",
        kind: "text",
        x: 6,
        y: 62,
        w: 40,
        h: 22,
        text: "Parker Brothers' breakout success was a study in economic inevitability: roll, move, collect rent, repeat. The board was a loop you could not leave.",
        fontSize: 1.8,
        fontRole: "body",
        fontWeight: 400,
        color: "textSecondary",
        align: "left",
        lineHeight: 1.55,
      },
      hruleCol("spec_rule_top", 52, 32, 42, 1),
      {
        id: "r1_key",
        kind: "text",
        x: 52,
        y: 34,
        w: 18,
        h: 5,
        text: "Core loop",
        fontSize: 2,
        fontRole: "heading",
        fontWeight: 500,
        color: "textPrimary",
      },
      {
        id: "r1_val",
        kind: "text",
        x: 72,
        y: 34.5,
        w: 22,
        h: 4,
        text: "ROLL → MOVE → RESOLVE",
        fontSize: 1.3,
        fontRole: "body",
        fontWeight: 500,
        color: "textMuted",
        fontFamily: "JetBrains Mono",
        letterSpacing: 0.08,
        textTransform: "uppercase",
      },
      hruleCol("spec_rule_1", 52, 41, 42, 1),
      {
        id: "r2_key",
        kind: "text",
        x: 52,
        y: 43,
        w: 18,
        h: 5,
        text: "Information",
        fontSize: 2,
        fontRole: "heading",
        fontWeight: 500,
        color: "textPrimary",
      },
      {
        id: "r2_val",
        kind: "text",
        x: 72,
        y: 43.5,
        w: 22,
        h: 4,
        text: "PERFECT",
        fontSize: 1.3,
        fontRole: "body",
        fontWeight: 500,
        color: "textMuted",
        fontFamily: "JetBrains Mono",
        letterSpacing: 0.08,
        textTransform: "uppercase",
      },
      hruleCol("spec_rule_2", 52, 50, 42, 1),
      {
        id: "r3_key",
        kind: "text",
        x: 52,
        y: 52,
        w: 18,
        h: 5,
        text: "Turn length",
        fontSize: 2,
        fontRole: "heading",
        fontWeight: 500,
        color: "textPrimary",
      },
      {
        id: "r3_val",
        kind: "text",
        x: 72,
        y: 52.5,
        w: 22,
        h: 4,
        text: "~20 SECONDS",
        fontSize: 1.3,
        fontRole: "body",
        fontWeight: 500,
        color: "textMuted",
        fontFamily: "JetBrains Mono",
        letterSpacing: 0.08,
        textTransform: "uppercase",
      },
      hruleCol("spec_rule_3", 52, 59, 42, 1),
      {
        id: "r4_key",
        kind: "text",
        x: 52,
        y: 61,
        w: 18,
        h: 5,
        text: "Game length",
        fontSize: 2,
        fontRole: "heading",
        fontWeight: 500,
        color: "textPrimary",
      },
      {
        id: "r4_val",
        kind: "text",
        x: 72,
        y: 61.5,
        w: 22,
        h: 4,
        text: "60–180 MINUTES",
        fontSize: 1.3,
        fontRole: "body",
        fontWeight: 500,
        color: "textMuted",
        fontFamily: "JetBrains Mono",
        letterSpacing: 0.08,
        textTransform: "uppercase",
      },
      hruleCol("spec_rule_4", 52, 68, 42, 1),
      {
        id: "r5_key",
        kind: "text",
        x: 52,
        y: 70,
        w: 18,
        h: 5,
        text: "Decision density",
        fontSize: 2,
        fontRole: "heading",
        fontWeight: 500,
        color: "textPrimary",
      },
      {
        id: "r5_val",
        kind: "text",
        x: 72,
        y: 70.5,
        w: 22,
        h: 4,
        text: "LOW · 1–2 / TURN",
        fontSize: 1.3,
        fontRole: "body",
        fontWeight: 500,
        color: "textMuted",
        fontFamily: "JetBrains Mono",
        letterSpacing: 0.08,
        textTransform: "uppercase",
      },
      hruleCol("spec_rule_5", 52, 77, 42, 1),
      {
        id: "r6_key",
        kind: "text",
        x: 52,
        y: 79,
        w: 18,
        h: 5,
        text: "Loss profile",
        fontSize: 2,
        fontRole: "heading",
        fontWeight: 500,
        color: "textPrimary",
      },
      {
        id: "r6_val",
        kind: "text",
        x: 72,
        y: 79.5,
        w: 22,
        h: 4,
        text: "ELIMINATION",
        fontSize: 1.3,
        fontRole: "body",
        fontWeight: 500,
        color: "textMuted",
        fontFamily: "JetBrains Mono",
        letterSpacing: 0.08,
        textTransform: "uppercase",
      },
      hruleCol("spec_rule_bottom", 52, 86, 42, 1),
    ],
  },

  {
    name: "profile-quadrant",
    description:
      "Prose column on the left, a 2×2 grid of small labeled cells on the right (each a mono label + one-line body). For character studies, personas, product/persona what-why-how-for-whom, four-facet breakdowns.",
    notes: [
      "Include the shared header above. Each of the 4 cells has a short mono label and a 1–2 line body.",
    ],
    elements: [
      {
        id: "left_eyebrow",
        kind: "text",
        x: 6,
        y: 32,
        w: 40,
        h: 3.5,
        text: "THE ARC",
        fontSize: 1.3,
        fontRole: "body",
        fontWeight: 500,
        color: "textMuted",
        fontFamily: "JetBrains Mono",
        letterSpacing: 0.14,
        textTransform: "uppercase",
      },
      {
        id: "left_prose",
        kind: "text",
        x: 6,
        y: 38,
        w: 40,
        h: 24,
        text: "James Gatz → Jay Gatsby → the man on the dock → the host of impossible parties → the lover who waits through a rainstorm → the body in the pool.",
        fontSize: 2.2,
        fontRole: "heading",
        fontWeight: 400,
        color: "textPrimary",
        align: "left",
        lineHeight: 1.35,
      },
      {
        id: "left_body",
        kind: "text",
        x: 6,
        y: 66,
        w: 40,
        h: 16,
        text: "He is, as Nick puts it, worth the whole damn bunch put together — not for what he has made of himself, but for the size of what he wanted.",
        fontSize: 1.6,
        fontRole: "body",
        fontWeight: 400,
        color: "textSecondary",
        align: "left",
        lineHeight: 1.5,
      },
      {
        id: "c1_label",
        kind: "text",
        x: 52,
        y: 32,
        w: 20,
        h: 3.5,
        text: "WANT",
        fontSize: 1.3,
        fontRole: "body",
        fontWeight: 500,
        color: "accent",
        fontFamily: "JetBrains Mono",
        letterSpacing: 0.14,
        textTransform: "uppercase",
      },
      {
        id: "c1_body",
        kind: "text",
        x: 52,
        y: 38,
        w: 20,
        h: 14,
        text: "To undo the five years between him and Daisy.",
        fontSize: 1.8,
        fontRole: "body",
        fontWeight: 400,
        color: "textPrimary",
        align: "left",
        lineHeight: 1.4,
      },
      {
        id: "c2_label",
        kind: "text",
        x: 74,
        y: 32,
        w: 20,
        h: 3.5,
        text: "NEED",
        fontSize: 1.3,
        fontRole: "body",
        fontWeight: 500,
        color: "accent",
        fontFamily: "JetBrains Mono",
        letterSpacing: 0.14,
        textTransform: "uppercase",
      },
      {
        id: "c2_body",
        kind: "text",
        x: 74,
        y: 38,
        w: 20,
        h: 14,
        text: "To know that the dream was ever possible.",
        fontSize: 1.8,
        fontRole: "body",
        fontWeight: 400,
        color: "textPrimary",
        align: "left",
        lineHeight: 1.4,
      },
      {
        id: "c3_label",
        kind: "text",
        x: 52,
        y: 58,
        w: 20,
        h: 3.5,
        text: "FLAW",
        fontSize: 1.3,
        fontRole: "body",
        fontWeight: 500,
        color: "accent",
        fontFamily: "JetBrains Mono",
        letterSpacing: 0.14,
        textTransform: "uppercase",
      },
      {
        id: "c3_body",
        kind: "text",
        x: 52,
        y: 64,
        w: 20,
        h: 14,
        text: "Mistaking a person for a promise.",
        fontSize: 1.8,
        fontRole: "body",
        fontWeight: 400,
        color: "textPrimary",
        align: "left",
        lineHeight: 1.4,
      },
      {
        id: "c4_label",
        kind: "text",
        x: 74,
        y: 58,
        w: 20,
        h: 3.5,
        text: "FATE",
        fontSize: 1.3,
        fontRole: "body",
        fontWeight: 500,
        color: "accent",
        fontFamily: "JetBrains Mono",
        letterSpacing: 0.14,
        textTransform: "uppercase",
      },
      {
        id: "c4_body",
        kind: "text",
        x: 74,
        y: 64,
        w: 20,
        h: 14,
        text: "A funeral almost no one attends.",
        fontSize: 1.8,
        fontRole: "body",
        fontWeight: 400,
        color: "textPrimary",
        align: "left",
        lineHeight: 1.4,
      },
    ],
  },

  {
    name: "compare-two-panel",
    description:
      "Two panels side by side linked by a mid-axis label. For classical vs quantum, before vs after, option A vs B.",
    notes: [
      "Use for two-panel contrasts: option A vs option B, classical vs quantum, before vs after. The mid axis carries a short connector label (distance, relation, consequence) on a dashed horizontal line. Include the shared header above.",
    ],
    elements: [
      {
        id: "left_label",
        kind: "text",
        x: 6,
        y: 34,
        w: 38,
        h: 3.5,
        text: "CLASSICAL",
        fontSize: 1.4,
        fontRole: "body",
        fontWeight: 500,
        color: "accent",
        fontFamily: "JetBrains Mono",
        letterSpacing: 0.16,
        textTransform: "uppercase",
      },
      {
        id: "left_heading",
        kind: "text",
        x: 6,
        y: 39,
        w: 38,
        h: 18,
        text: "A pair of gloves in two boxes.",
        fontSize: 3.4,
        fontRole: "heading",
        fontWeight: 400,
        color: "textPrimary",
        align: "left",
        lineHeight: 1.15,
      },
      {
        id: "left_body",
        kind: "text",
        x: 6,
        y: 58,
        w: 38,
        h: 24,
        text: "The answer was decided at the factory. Opening the box reveals it.",
        fontSize: 1.8,
        fontRole: "body",
        fontWeight: 400,
        color: "textSecondary",
        align: "left",
        lineHeight: 1.55,
      },
      {
        id: "mid_line",
        kind: "shape",
        shape: "line",
        x: 45,
        y: 50,
        w: 10,
        h: 0,
        stroke: "border",
        strokeWidth: 1,
      },
      {
        id: "mid_label",
        kind: "text",
        x: 42,
        y: 53,
        w: 16,
        h: 3.5,
        text: "— 12,000 KM —",
        fontSize: 1.3,
        fontRole: "body",
        fontWeight: 500,
        color: "textMuted",
        fontFamily: "JetBrains Mono",
        letterSpacing: 0.18,
        textTransform: "uppercase",
        align: "center",
      },
      {
        id: "right_label",
        kind: "text",
        x: 56,
        y: 34,
        w: 38,
        h: 3.5,
        text: "QUANTUM",
        fontSize: 1.4,
        fontRole: "body",
        fontWeight: 500,
        color: "accent",
        fontFamily: "JetBrains Mono",
        letterSpacing: 0.16,
        textTransform: "uppercase",
      },
      {
        id: "right_heading",
        kind: "text",
        x: 56,
        y: 39,
        w: 38,
        h: 18,
        text: "Two entangled particles, one state.",
        fontSize: 3.4,
        fontRole: "heading",
        fontWeight: 400,
        color: "textPrimary",
        align: "left",
        lineHeight: 1.15,
      },
      {
        id: "right_body",
        kind: "text",
        x: 56,
        y: 58,
        w: 38,
        h: 24,
        text: "Before measurement neither has a value. Measuring creates one and fixes the other, instantly.",
        fontSize: 1.8,
        fontRole: "body",
        fontWeight: 400,
        color: "textSecondary",
        align: "left",
        lineHeight: 1.55,
      },
    ],
  },

  {
    name: "compare-lists",
    description:
      "Two labeled columns, each a numbered list of short items (3 steps) with a trailing caption. For old-way vs new-way, before/after process, naive vs correct approach.",
    notes: [
      "Use accent colors to differentiate the two labels so the contrast reads visually. Include the shared header above.",
    ],
    elements: [
      {
        id: "left_label",
        kind: "text",
        x: 6,
        y: 32,
        w: 40,
        h: 3.5,
        text: "MONOPOLY, 1935",
        fontSize: 1.4,
        fontRole: "body",
        fontWeight: 500,
        color: "accent",
        fontFamily: "JetBrains Mono",
        letterSpacing: 0.14,
        textTransform: "uppercase",
      },
      {
        id: "l1_n",
        kind: "text",
        x: 6,
        y: 42,
        w: 6,
        h: 5,
        text: "01",
        fontSize: 1.3,
        fontRole: "body",
        fontWeight: 500,
        color: "accent",
        fontFamily: "JetBrains Mono",
        letterSpacing: 0.1,
      },
      {
        id: "l1_t",
        kind: "text",
        x: 13,
        y: 41,
        w: 33,
        h: 6,
        text: "Roll two dice.",
        fontSize: 2.1,
        fontRole: "heading",
        fontWeight: 500,
        color: "textPrimary",
        lineHeight: 1.2,
      },
      hrule("l_rule_1", 49, 1),
      {
        id: "l2_n",
        kind: "text",
        x: 6,
        y: 53,
        w: 6,
        h: 5,
        text: "02",
        fontSize: 1.3,
        fontRole: "body",
        fontWeight: 500,
        color: "accent",
        fontFamily: "JetBrains Mono",
        letterSpacing: 0.1,
      },
      {
        id: "l2_t",
        kind: "text",
        x: 13,
        y: 52,
        w: 33,
        h: 6,
        text: "Move that many spaces.",
        fontSize: 2.1,
        fontRole: "heading",
        fontWeight: 500,
        color: "textPrimary",
        lineHeight: 1.2,
      },
      hrule("l_rule_2", 60, 1),
      {
        id: "l3_n",
        kind: "text",
        x: 6,
        y: 64,
        w: 6,
        h: 5,
        text: "03",
        fontSize: 1.3,
        fontRole: "body",
        fontWeight: 500,
        color: "accent",
        fontFamily: "JetBrains Mono",
        letterSpacing: 0.1,
      },
      {
        id: "l3_t",
        kind: "text",
        x: 13,
        y: 63,
        w: 33,
        h: 6,
        text: "Do what the square says.",
        fontSize: 2.1,
        fontRole: "heading",
        fontWeight: 500,
        color: "textPrimary",
        lineHeight: 1.2,
      },
      hrule("l_rule_3", 71, 1),
      {
        id: "l_caption",
        kind: "text",
        x: 6,
        y: 75,
        w: 40,
        h: 6,
        text: "Three steps. Zero-to-one real choices.",
        fontSize: 1.4,
        fontRole: "body",
        fontWeight: 400,
        color: "textMuted",
        fontStyle: "italic",
        lineHeight: 1.4,
      },
      {
        id: "right_label",
        kind: "text",
        x: 54,
        y: 32,
        w: 40,
        h: 3.5,
        text: "WINGSPAN, 2019",
        fontSize: 1.4,
        fontRole: "body",
        fontWeight: 500,
        color: "accent",
        fontFamily: "JetBrains Mono",
        letterSpacing: 0.14,
        textTransform: "uppercase",
      },
      {
        id: "r1_n",
        kind: "text",
        x: 54,
        y: 42,
        w: 6,
        h: 5,
        text: "01",
        fontSize: 1.3,
        fontRole: "body",
        fontWeight: 500,
        color: "accent",
        fontFamily: "JetBrains Mono",
        letterSpacing: 0.1,
      },
      {
        id: "r1_t",
        kind: "text",
        x: 61,
        y: 41,
        w: 33,
        h: 6,
        text: "Play a bird, gain food, lay eggs, or draw cards.",
        fontSize: 2.1,
        fontRole: "heading",
        fontWeight: 500,
        color: "textPrimary",
        lineHeight: 1.2,
      },
      hrule("r_rule_1", 49, 1),
      {
        id: "r2_n",
        kind: "text",
        x: 54,
        y: 53,
        w: 6,
        h: 5,
        text: "02",
        fontSize: 1.3,
        fontRole: "body",
        fontWeight: 500,
        color: "accent",
        fontFamily: "JetBrains Mono",
        letterSpacing: 0.1,
      },
      {
        id: "r2_t",
        kind: "text",
        x: 61,
        y: 52,
        w: 33,
        h: 6,
        text: "Trigger the habitat row's power chain.",
        fontSize: 2.1,
        fontRole: "heading",
        fontWeight: 500,
        color: "textPrimary",
        lineHeight: 1.2,
      },
      hrule("r_rule_2", 60, 1),
      {
        id: "r3_n",
        kind: "text",
        x: 54,
        y: 64,
        w: 6,
        h: 5,
        text: "03",
        fontSize: 1.3,
        fontRole: "body",
        fontWeight: 500,
        color: "accent",
        fontFamily: "JetBrains Mono",
        letterSpacing: 0.1,
      },
      {
        id: "r3_t",
        kind: "text",
        x: 61,
        y: 63,
        w: 33,
        h: 6,
        text: "Resolve each when-activated ability in order.",
        fontSize: 2.1,
        fontRole: "heading",
        fontWeight: 500,
        color: "textPrimary",
        lineHeight: 1.2,
      },
      hrule("r_rule_3", 71, 1),
      {
        id: "r_caption",
        kind: "text",
        x: 54,
        y: 75,
        w: 40,
        h: 6,
        text: "Three steps. Six-to-twelve real choices, branching.",
        fontSize: 1.4,
        fontRole: "body",
        fontWeight: 400,
        color: "textMuted",
        fontStyle: "italic",
        lineHeight: 1.4,
      },
    ],
  },

  {
    name: "stats-cells",
    description:
      "Editorial hairline grid of stat cells — no filled cards, dividers only. For categorical 3×2 card grids when order doesn't matter.",
    notes: [`Use SHARED HEADER PATTERN above (y 9–26) for the title/rule above the grid.`],
    elements: [
      hrule("topRule", 30),
      // Cell 0
      eyebrow("c0_eyebrow", "01 · REVENUE", 7, 34, 27, { fontSize: 1.3, letterSpacing: 0.14 }),
      {
        id: "c0_value",
        kind: "text",
        x: 7,
        y: 41,
        w: 27,
        h: 12,
        text: "142%",
        fontSize: 5.5,
        fontRole: "heading",
        fontWeight: 400,
        color: "accent",
        align: "left",
        lineHeight: 1.0,
      },
      {
        id: "c0_body",
        kind: "text",
        x: 7,
        y: 57,
        w: 27,
        h: 20,
        text: "Year-over-year growth, Q4.",
        fontSize: 1.5,
        fontRole: "body",
        fontWeight: 400,
        color: "textSecondary",
        align: "left",
        lineHeight: 1.4,
      },
      // Cell 1
      vdiv("div1", 36, 31, 48),
      eyebrow("c1_eyebrow", "02 · USERS", 37, 34, 27, { fontSize: 1.3, letterSpacing: 0.14 }),
      {
        id: "c1_value",
        kind: "text",
        x: 37,
        y: 41,
        w: 27,
        h: 12,
        text: "2.4M",
        fontSize: 5.5,
        fontRole: "heading",
        fontWeight: 400,
        color: "accent",
        align: "left",
        lineHeight: 1.0,
      },
      {
        id: "c1_body",
        kind: "text",
        x: 37,
        y: 57,
        w: 27,
        h: 20,
        text: "Monthly active users.",
        fontSize: 1.5,
        fontRole: "body",
        fontWeight: 400,
        color: "textSecondary",
        align: "left",
        lineHeight: 1.4,
      },
      // Cell 2
      vdiv("div2", 66, 31, 48),
      eyebrow("c2_eyebrow", "03 · UPTIME", 67, 34, 27, { fontSize: 1.3, letterSpacing: 0.14 }),
      {
        id: "c2_value",
        kind: "text",
        x: 67,
        y: 41,
        w: 27,
        h: 12,
        text: "99.9%",
        fontSize: 5.5,
        fontRole: "heading",
        fontWeight: 400,
        color: "accent",
        align: "left",
        lineHeight: 1.0,
      },
      {
        id: "c2_body",
        kind: "text",
        x: 67,
        y: 57,
        w: 27,
        h: 20,
        text: "Rolling 30-day average.",
        fontSize: 1.5,
        fontRole: "body",
        fontWeight: 400,
        color: "textSecondary",
        align: "left",
        lineHeight: 1.4,
      },
      hrule("bottomRule", 80),
    ],
  },

  {
    name: "palette-swatches",
    description:
      "Row of 5 colored chips, each with a serif name and a short muted gloss below. For brand/color system explanations, category legends, thematic palette overviews. Substitute your own hex values for the chip fills.",
    notes: [
      "Include the shared header above. Use real hex strings for the chip fill (not color tokens) so the palette visibly reads as distinct swatches.",
    ],
    elements: [
      {
        id: "s1_chip",
        kind: "shape",
        shape: "rect",
        x: 6,
        y: 32,
        w: 16,
        h: 22,
        fill: "#6B8246",
      },
      {
        id: "s1_name",
        kind: "text",
        x: 6,
        y: 56,
        w: 16,
        h: 5,
        text: "Green",
        fontSize: 2.2,
        fontRole: "heading",
        fontWeight: 500,
        color: "textPrimary",
      },
      {
        id: "s1_gloss",
        kind: "text",
        x: 6,
        y: 62,
        w: 16,
        h: 16,
        text: "The light, the lawns, new money — hope with a price tag.",
        fontSize: 1.3,
        fontRole: "body",
        fontWeight: 400,
        color: "textSecondary",
        lineHeight: 1.4,
      },
      {
        id: "s2_chip",
        kind: "shape",
        shape: "rect",
        x: 24,
        y: 32,
        w: 16,
        h: 22,
        fill: "#EDE6D8",
      },
      {
        id: "s2_name",
        kind: "text",
        x: 24,
        y: 56,
        w: 16,
        h: 5,
        text: "White",
        fontSize: 2.2,
        fontRole: "heading",
        fontWeight: 500,
        color: "textPrimary",
      },
      {
        id: "s2_gloss",
        kind: "text",
        x: 24,
        y: 62,
        w: 16,
        h: 16,
        text: "Daisy and Jordan in the breeze — innocence that won't stay clean.",
        fontSize: 1.3,
        fontRole: "body",
        fontWeight: 400,
        color: "textSecondary",
        lineHeight: 1.4,
      },
      {
        id: "s3_chip",
        kind: "shape",
        shape: "rect",
        x: 42,
        y: 32,
        w: 16,
        h: 22,
        fill: "#C8A85A",
      },
      {
        id: "s3_name",
        kind: "text",
        x: 42,
        y: 56,
        w: 16,
        h: 5,
        text: "Gold",
        fontSize: 2.2,
        fontRole: "heading",
        fontWeight: 500,
        color: "textPrimary",
      },
      {
        id: "s3_gloss",
        kind: "text",
        x: 42,
        y: 62,
        w: 16,
        h: 16,
        text: "Wealth, the car, the corrupted American sun.",
        fontSize: 1.3,
        fontRole: "body",
        fontWeight: 400,
        color: "textSecondary",
        lineHeight: 1.4,
      },
      {
        id: "s4_chip",
        kind: "shape",
        shape: "rect",
        x: 60,
        y: 32,
        w: 16,
        h: 22,
        fill: "#8A8F84",
      },
      {
        id: "s4_name",
        kind: "text",
        x: 60,
        y: 56,
        w: 16,
        h: 5,
        text: "Gray",
        fontSize: 2.2,
        fontRole: "heading",
        fontWeight: 500,
        color: "textPrimary",
      },
      {
        id: "s4_gloss",
        kind: "text",
        x: 60,
        y: 62,
        w: 16,
        h: 16,
        text: "The valley, George, the spaces the rich drive through.",
        fontSize: 1.3,
        fontRole: "body",
        fontWeight: 400,
        color: "textSecondary",
        lineHeight: 1.4,
      },
      {
        id: "s5_chip",
        kind: "shape",
        shape: "rect",
        x: 78,
        y: 32,
        w: 16,
        h: 22,
        fill: "#1F2A52",
      },
      {
        id: "s5_name",
        kind: "text",
        x: 78,
        y: 56,
        w: 16,
        h: 5,
        text: "Blue",
        fontSize: 2.2,
        fontRole: "heading",
        fontWeight: 500,
        color: "textPrimary",
      },
      {
        id: "s5_gloss",
        kind: "text",
        x: 78,
        y: 62,
        w: 16,
        h: 16,
        text: "Gatsby's gardens, the dream's atmosphere.",
        fontSize: 1.3,
        fontRole: "body",
        fontWeight: 400,
        color: "textSecondary",
        lineHeight: 1.4,
      },
    ],
  },

  {
    name: "stats-inline",
    description:
      "Row of 3 stats each with a vertical accent bar + large value + mono label + short body. For a headline-style metric strip.",
    notes: ["Include the shared header above."],
    elements: [
      {
        id: "s1_bar",
        kind: "shape",
        shape: "rect",
        x: 6,
        y: 38,
        w: 0.4,
        h: 24,
        fill: "accent",
      },
      {
        id: "s1_value",
        kind: "text",
        x: 8,
        y: 37,
        w: 24,
        h: 12,
        text: "+38%",
        fontSize: 6,
        fontRole: "heading",
        fontWeight: 400,
        color: "textPrimary",
        align: "left",
        lineHeight: 1.0,
      },
      {
        id: "s1_label",
        kind: "text",
        x: 8,
        y: 50,
        w: 24,
        h: 3.5,
        text: "MARGIN GROWTH",
        fontSize: 1.4,
        fontRole: "body",
        fontWeight: 500,
        color: "textMuted",
        fontFamily: "JetBrains Mono",
        letterSpacing: 0.14,
        textTransform: "uppercase",
      },
      {
        id: "s1_body",
        kind: "text",
        x: 8,
        y: 55,
        w: 24,
        h: 7,
        text: "Year-over-year, four quarters running.",
        fontSize: 1.5,
        fontRole: "body",
        fontWeight: 400,
        color: "textSecondary",
        lineHeight: 1.4,
      },
      {
        id: "s2_bar",
        kind: "shape",
        shape: "rect",
        x: 36,
        y: 38,
        w: 0.4,
        h: 24,
        fill: "accent",
      },
      {
        id: "s2_value",
        kind: "text",
        x: 38,
        y: 37,
        w: 24,
        h: 12,
        text: "50M+",
        fontSize: 6,
        fontRole: "heading",
        fontWeight: 400,
        color: "textPrimary",
        align: "left",
        lineHeight: 1.0,
      },
      {
        id: "s2_label",
        kind: "text",
        x: 38,
        y: 50,
        w: 24,
        h: 3.5,
        text: "ACTIVE USERS",
        fontSize: 1.4,
        fontRole: "body",
        fontWeight: 500,
        color: "textMuted",
        fontFamily: "JetBrains Mono",
        letterSpacing: 0.14,
        textTransform: "uppercase",
      },
      {
        id: "s2_body",
        kind: "text",
        x: 38,
        y: 55,
        w: 24,
        h: 7,
        text: "Across eleven regions — up from 18M in 2023.",
        fontSize: 1.5,
        fontRole: "body",
        fontWeight: 400,
        color: "textSecondary",
        lineHeight: 1.4,
      },
      {
        id: "s3_bar",
        kind: "shape",
        shape: "rect",
        x: 66,
        y: 38,
        w: 0.4,
        h: 24,
        fill: "accent",
      },
      {
        id: "s3_value",
        kind: "text",
        x: 68,
        y: 37,
        w: 26,
        h: 12,
        text: "99.98%",
        fontSize: 6,
        fontRole: "heading",
        fontWeight: 400,
        color: "textPrimary",
        align: "left",
        lineHeight: 1.0,
      },
      {
        id: "s3_label",
        kind: "text",
        x: 68,
        y: 50,
        w: 26,
        h: 3.5,
        text: "UPTIME · Q4",
        fontSize: 1.4,
        fontRole: "body",
        fontWeight: 500,
        color: "textMuted",
        fontFamily: "JetBrains Mono",
        letterSpacing: 0.14,
        textTransform: "uppercase",
      },
      {
        id: "s3_body",
        kind: "text",
        x: 68,
        y: 55,
        w: 26,
        h: 7,
        text: "Measured across all public endpoints.",
        fontSize: 1.5,
        fontRole: "body",
        fontWeight: 400,
        color: "textSecondary",
        lineHeight: 1.4,
      },
    ],
  },

  {
    name: "stats-large",
    description: "Single featured number dominating the slide, with a small supporting label.",
    elements: [
      {
        id: "value",
        kind: "text",
        x: 7.5,
        y: 28,
        w: 85,
        h: 22,
        text: "50M+",
        fontSize: 7.5,
        fontRole: "heading",
        fontWeight: 700,
        color: "accent",
        align: "center",
      },
      {
        id: "label",
        kind: "text",
        x: 15,
        y: 52,
        w: 70,
        h: 8,
        text: "API calls processed daily",
        fontSize: 2.1,
        fontRole: "heading",
        fontWeight: 400,
        color: "textMuted",
        align: "center",
      },
      {
        id: "body",
        kind: "text",
        x: 15,
        y: 63,
        w: 70,
        h: 12,
        text: "A 3x increase from last quarter.",
        fontSize: 1.9,
        fontRole: "body",
        fontWeight: 400,
        color: "textMuted",
        align: "center",
        lineHeight: 1.5,
      },
    ],
  },

  {
    name: "list-hairline",
    description:
      "Editorial field guide: 3 columns × 2 rows of entries separated by hairline dividers. Each entry has a mono eyebrow + serif title + body.",
    notes: [
      `Use SHARED HEADER PATTERN above for the title/rule.`,
      `Six entries arranged as 3 columns × 2 rows. Vertical dividers separate columns, a horizontal rule separates rows.`,
    ],
    elements: (() => {
      const els: SlideElement[] = [hrule("topRule", 30)];
      const sampleEntries = [
        {
          eyebrow: "SUCKING · SOFT-BODIED",
          title: "Aphids",
          body: "Clusters on new growth. Sticky residue.",
        },
        {
          eyebrow: "CHEWING · NOCTURNAL",
          title: "Slugs",
          body: "Silver trails at dawn. Ragged holes in leaves.",
        },
        {
          eyebrow: "CHEWING · CATERPILLAR",
          title: "Cabbage worms",
          body: "Green velvet caterpillars on brassicas.",
        },
        {
          eyebrow: "ARMORED · BEETLES",
          title: "Japanese beetles",
          body: "Skeletonized leaves, metallic clusters.",
        },
        {
          eyebrow: "SUCKING · TINY",
          title: "Spider mites",
          body: "Stippled yellow leaves, fine webs underneath.",
        },
        {
          eyebrow: "BORING · HIDDEN",
          title: "Squash vine borers",
          body: "Sudden plant collapse, sawdust at stem base.",
        },
      ];
      for (let r = 0; r < 2; r++) {
        for (let c = 0; c < 3; c++) {
          const idx = r * 3 + c;
          const x = 7 + 30 * c;
          const y = 33 + r * 24;
          const sample = sampleEntries[idx];
          els.push(
            eyebrow(`e${idx}_eyebrow`, sample.eyebrow, x, y, 27, {
              fontSize: 1.3,
              letterSpacing: 0.14,
            })
          );
          els.push({
            id: `e${idx}_title`,
            kind: "text",
            x,
            y: y + 4,
            w: 27,
            h: 7,
            text: sample.title,
            fontSize: 3.8,
            fontRole: "heading",
            fontWeight: 400,
            color: "textPrimary",
            align: "left",
            lineHeight: 1.0,
          });
          els.push({
            id: `e${idx}_body`,
            kind: "text",
            x,
            y: y + 13,
            w: 27,
            h: 9,
            text: sample.body,
            fontSize: 1.5,
            fontRole: "body",
            fontWeight: 400,
            color: "textSecondary",
            align: "left",
            lineHeight: 1.35,
          });
        }
      }
      els.push(vdiv("divC1", 36, 31, 48));
      els.push(vdiv("divC2", 66, 31, 48));
      els.push(hrule("midRule", 56));
      els.push(hrule("bottomRule", 80));
      return els;
    })(),
  },

  {
    name: "list-minimal",
    description: "Sidebar heading on the left, stacked items with thin dividers on the right.",
    notes: [
      `Items stack in the right column with line dividers (shape "line" with stroke="border") between them.`,
    ],
    elements: [
      {
        id: "heading",
        kind: "text",
        x: 6,
        y: 9,
        w: 29,
        h: 82,
        text: "SIDEBAR HEADING",
        fontSize: 3.3,
        fontRole: "heading",
        fontWeight: 700,
        color: "accent",
        textTransform: "uppercase",
      },
    ],
  },

  {
    name: "quote-centered",
    description: "Large centered pull-quote with a centered attribution line below.",
    elements: [
      {
        id: "quote",
        kind: "text",
        x: 7.5,
        y: 26,
        w: 85,
        h: 37,
        text: "A large centered italic quote goes here.",
        fontSize: 3.3,
        fontRole: "heading",
        fontWeight: 400,
        color: "textPrimary",
        align: "center",
        fontStyle: "italic",
        lineHeight: 1.4,
      },
      eyebrow("attribution", "— SOURCE", 20, 69, 60, {
        fontSize: 1.5,
        letterSpacing: 0.14,
        align: "center",
      }),
    ],
  },

  {
    name: "quote-offset",
    description: "Left-aligned pull-quote with a short accent bar and cite line.",
    elements: [
      {
        id: "bar",
        kind: "shape",
        x: 7.5,
        y: 28,
        w: 0.3,
        h: 33,
        shape: "rect",
        fill: "accent",
      },
      {
        id: "quote",
        kind: "text",
        x: 10,
        y: 28,
        w: 73,
        h: 33,
        text: "The quote text goes here.",
        fontSize: 2.6,
        fontRole: "heading",
        fontWeight: 400,
        color: "textPrimary",
        align: "left",
        lineHeight: 1.55,
      },
      eyebrow("attribution", "— SOURCE", 10, 65, 73, { fontSize: 1.5, letterSpacing: 0.14 }),
    ],
  },

  {
    name: "timeline-numbered",
    description:
      "Vertical timeline with big accent index numbers and a one-line description per step.",
    notes: [
      `For each step: a small number text (fontSize=1.9, fontWeight=700, color="accent") + a step title + a step body, with line dividers between steps.`,
    ],
    elements: [
      {
        id: "heading",
        kind: "text",
        x: 6,
        y: 7,
        w: 88,
        h: 8,
        text: "Heading",
        fontSize: 2.5,
        fontRole: "heading",
        fontWeight: 600,
        color: "textPrimary",
      },
    ],
  },

  {
    name: "timeline-horizontal",
    description:
      "Horizontal axis timeline: even tick marks across the page with labels above and descriptions below.",
    notes: [
      `For each event along the axis: a vertical tick line + a title below the tick + a short body below the title.`,
    ],
    elements: [
      {
        id: "heading",
        kind: "text",
        x: 6,
        y: 7,
        w: 88,
        h: 10,
        text: "Heading",
        fontSize: 3.3,
        fontRole: "heading",
        fontWeight: 700,
        color: "accent",
      },
      {
        id: "axis",
        kind: "shape",
        x: 6,
        y: 40,
        w: 88,
        h: 0,
        shape: "line",
        stroke: "border",
        strokeWidth: 2,
      },
    ],
  },

  {
    name: "timeline-table",
    description:
      "Year | what | note table rows with hairlines between. For 5+ events needing a label column and an explanatory note column.",
    notes: [
      "Use when the sequence is 5+ events with enough nuance to need a year column, a headline column, and a muted explanatory note. Different from the horizontal-axis timeline (no year column) and numbered-vertical timeline (no distinct note column). Include the shared header above.",
    ],
    elements: [
      hrule("row0_rule", 34, 1),
      {
        id: "r1_year",
        kind: "text",
        x: 6,
        y: 36,
        w: 12,
        h: 7,
        text: "1935",
        fontSize: 3.2,
        fontRole: "heading",
        fontWeight: 400,
        color: "accent",
        lineHeight: 1.0,
      },
      {
        id: "r1_what",
        kind: "text",
        x: 22,
        y: 37,
        w: 42,
        h: 6,
        text: "Einstein, Podolsky & Rosen publish the paradox.",
        fontSize: 2,
        fontRole: "heading",
        fontWeight: 400,
        color: "textPrimary",
        lineHeight: 1.25,
      },
      {
        id: "r1_note",
        kind: "text",
        x: 68,
        y: 38,
        w: 26,
        h: 6,
        text: "Argue quantum theory is incomplete.",
        fontSize: 1.5,
        fontRole: "body",
        fontWeight: 400,
        color: "textSecondary",
        lineHeight: 1.4,
      },
      hrule("row1_rule", 45, 1),
      {
        id: "r2_year",
        kind: "text",
        x: 6,
        y: 47,
        w: 12,
        h: 7,
        text: "1964",
        fontSize: 3.2,
        fontRole: "heading",
        fontWeight: 400,
        color: "accent",
        lineHeight: 1.0,
      },
      {
        id: "r2_what",
        kind: "text",
        x: 22,
        y: 48,
        w: 42,
        h: 6,
        text: "Bell's inequality turns the argument into an experiment.",
        fontSize: 2,
        fontRole: "heading",
        fontWeight: 400,
        color: "textPrimary",
        lineHeight: 1.25,
      },
      {
        id: "r2_note",
        kind: "text",
        x: 68,
        y: 49,
        w: 26,
        h: 6,
        text: "A test nature itself can decide.",
        fontSize: 1.5,
        fontRole: "body",
        fontWeight: 400,
        color: "textSecondary",
        lineHeight: 1.4,
      },
      hrule("row2_rule", 56, 1),
      {
        id: "r3_year",
        kind: "text",
        x: 6,
        y: 58,
        w: 12,
        h: 7,
        text: "1984",
        fontSize: 3.2,
        fontRole: "heading",
        fontWeight: 400,
        color: "accent",
        lineHeight: 1.0,
      },
      {
        id: "r3_what",
        kind: "text",
        x: 22,
        y: 59,
        w: 42,
        h: 6,
        text: "BB84 — the first quantum key distribution protocol.",
        fontSize: 2,
        fontRole: "heading",
        fontWeight: 400,
        color: "textPrimary",
        lineHeight: 1.25,
      },
      {
        id: "r3_note",
        kind: "text",
        x: 68,
        y: 60,
        w: 26,
        h: 6,
        text: "Cryptography gets a physics foundation.",
        fontSize: 1.5,
        fontRole: "body",
        fontWeight: 400,
        color: "textSecondary",
        lineHeight: 1.4,
      },
      hrule("row3_rule", 67, 1),
      {
        id: "r4_year",
        kind: "text",
        x: 6,
        y: 69,
        w: 12,
        h: 7,
        text: "2019",
        fontSize: 3.2,
        fontRole: "heading",
        fontWeight: 400,
        color: "accent",
        lineHeight: 1.0,
      },
      {
        id: "r4_what",
        kind: "text",
        x: 22,
        y: 70,
        w: 42,
        h: 6,
        text: "Google's Sycamore claims quantum advantage.",
        fontSize: 2,
        fontRole: "heading",
        fontWeight: 400,
        color: "textPrimary",
        lineHeight: 1.25,
      },
      {
        id: "r4_note",
        kind: "text",
        x: 68,
        y: 71,
        w: 26,
        h: 6,
        text: "A task no classical computer can match.",
        fontSize: 1.5,
        fontRole: "body",
        fontWeight: 400,
        color: "textSecondary",
        lineHeight: 1.4,
      },
      hrule("row4_rule", 78, 1),
      {
        id: "r5_year",
        kind: "text",
        x: 6,
        y: 80,
        w: 12,
        h: 7,
        text: "2022",
        fontSize: 3.2,
        fontRole: "heading",
        fontWeight: 400,
        color: "accent",
        lineHeight: 1.0,
      },
      {
        id: "r5_what",
        kind: "text",
        x: 22,
        y: 81,
        w: 42,
        h: 6,
        text: "Nobel Prize for experimental foundations of entanglement.",
        fontSize: 2,
        fontRole: "heading",
        fontWeight: 400,
        color: "textPrimary",
        lineHeight: 1.25,
      },
      {
        id: "r5_note",
        kind: "text",
        x: 68,
        y: 82,
        w: 26,
        h: 6,
        text: "Aspect · Clauser · Zeilinger.",
        fontSize: 1.5,
        fontRole: "body",
        fontWeight: 400,
        color: "textSecondary",
        lineHeight: 1.4,
      },
      hrule("row5_rule", 89, 1),
    ],
  },

  {
    name: "hero-split",
    description: "Split layout: text column on the left, full-bleed image on the right.",
    elements: [
      {
        id: "image",
        kind: "image",
        x: 50,
        y: 0,
        w: 50,
        h: 100,
        src: "attached:0",
      },
      {
        id: "heading",
        kind: "text",
        x: 6,
        y: 9,
        w: 40,
        h: 19,
        text: "HEADING",
        fontSize: 3.3,
        fontRole: "heading",
        fontWeight: 700,
        color: "accent",
        textTransform: "uppercase",
      },
      {
        id: "body",
        kind: "text",
        x: 6,
        y: 30,
        w: 40,
        h: 37,
        text: "Body copy here.",
        fontSize: 1.9,
        fontRole: "body",
        fontWeight: 400,
        color: "textSecondary",
        lineHeight: 1.7,
      },
    ],
  },

  {
    name: "hero-overlay",
    description: "Full-bleed image with a gradient overlay and title text pinned at the bottom.",
    elements: [
      {
        id: "image",
        kind: "image",
        x: 0,
        y: 0,
        w: 100,
        h: 100,
        src: "attached:0",
      },
      {
        id: "gradient",
        kind: "shape",
        x: 0,
        y: 40,
        w: 100,
        h: 60,
        shape: "rect",
        fill: "rgba(0,0,0,0.7)",
      },
      {
        id: "heading",
        kind: "text",
        x: 6,
        y: 67,
        w: 88,
        h: 15,
        text: "Heading on gradient",
        fontSize: 4.2,
        fontRole: "heading",
        fontWeight: 700,
        color: "#ffffff",
      },
      {
        id: "body",
        kind: "text",
        x: 6,
        y: 83,
        w: 88,
        h: 9,
        text: "Body text on gradient.",
        fontSize: 1.9,
        fontRole: "body",
        fontWeight: 400,
        color: "rgba(255,255,255,0.88)",
      },
    ],
  },

  {
    name: "table",
    description:
      "3-column table: serif name column + mono tag column + body note column, hairlines between rows. For rows of the same schema.",
    notes: [
      "Include the shared header above. Substitute column headers and row content for your domain.",
    ],
    elements: [
      {
        id: "h1",
        kind: "text",
        x: 6,
        y: 32,
        w: 40,
        h: 3.5,
        text: "ACCOUNT",
        fontSize: 1.3,
        fontRole: "body",
        fontWeight: 500,
        color: "textMuted",
        fontFamily: "JetBrains Mono",
        letterSpacing: 0.14,
        textTransform: "uppercase",
      },
      {
        id: "h2",
        kind: "text",
        x: 48,
        y: 32,
        w: 18,
        h: 3.5,
        text: "CHANGE",
        fontSize: 1.3,
        fontRole: "body",
        fontWeight: 500,
        color: "textMuted",
        fontFamily: "JetBrains Mono",
        letterSpacing: 0.14,
        textTransform: "uppercase",
      },
      {
        id: "h3",
        kind: "text",
        x: 68,
        y: 32,
        w: 26,
        h: 3.5,
        text: "NOTE",
        fontSize: 1.3,
        fontRole: "body",
        fontWeight: 500,
        color: "textMuted",
        fontFamily: "JetBrains Mono",
        letterSpacing: 0.14,
        textTransform: "uppercase",
      },
      hrule("rule_head", 37, 1),
      {
        id: "r1_name",
        kind: "text",
        x: 6,
        y: 40,
        w: 40,
        h: 6,
        text: "Acme Robotics",
        fontSize: 2.6,
        fontRole: "heading",
        fontWeight: 400,
        color: "textPrimary",
      },
      {
        id: "r1_change",
        kind: "text",
        x: 48,
        y: 41,
        w: 18,
        h: 5,
        text: "+38%",
        fontSize: 2,
        fontRole: "body",
        fontWeight: 500,
        color: "accent",
      },
      {
        id: "r1_note",
        kind: "text",
        x: 68,
        y: 41,
        w: 26,
        h: 6,
        text: "Expanded to four new regions.",
        fontSize: 1.5,
        fontRole: "body",
        fontWeight: 400,
        color: "textSecondary",
      },
      hrule("rule_1", 49, 1),
      {
        id: "r2_name",
        kind: "text",
        x: 6,
        y: 52,
        w: 40,
        h: 6,
        text: "Northwind",
        fontSize: 2.6,
        fontRole: "heading",
        fontWeight: 400,
        color: "textPrimary",
      },
      {
        id: "r2_change",
        kind: "text",
        x: 48,
        y: 53,
        w: 18,
        h: 5,
        text: "+22%",
        fontSize: 2,
        fontRole: "body",
        fontWeight: 500,
        color: "accent",
      },
      {
        id: "r2_note",
        kind: "text",
        x: 68,
        y: 53,
        w: 26,
        h: 6,
        text: "Added seat-based billing.",
        fontSize: 1.5,
        fontRole: "body",
        fontWeight: 400,
        color: "textSecondary",
      },
      hrule("rule_2", 61, 1),
      {
        id: "r3_name",
        kind: "text",
        x: 6,
        y: 64,
        w: 40,
        h: 6,
        text: "Contoso",
        fontSize: 2.6,
        fontRole: "heading",
        fontWeight: 400,
        color: "textPrimary",
      },
      {
        id: "r3_change",
        kind: "text",
        x: 48,
        y: 65,
        w: 18,
        h: 5,
        text: "+18%",
        fontSize: 2,
        fontRole: "body",
        fontWeight: 500,
        color: "accent",
      },
      {
        id: "r3_note",
        kind: "text",
        x: 68,
        y: 65,
        w: 26,
        h: 6,
        text: "Consolidated pricing tiers.",
        fontSize: 1.5,
        fontRole: "body",
        fontWeight: 400,
        color: "textSecondary",
      },
      hrule("rule_3", 73, 1),
      {
        id: "r4_name",
        kind: "text",
        x: 6,
        y: 76,
        w: 40,
        h: 6,
        text: "Initech",
        fontSize: 2.6,
        fontRole: "heading",
        fontWeight: 400,
        color: "textPrimary",
      },
      {
        id: "r4_change",
        kind: "text",
        x: 48,
        y: 77,
        w: 18,
        h: 5,
        text: "+11%",
        fontSize: 2,
        fontRole: "body",
        fontWeight: 500,
        color: "accent",
      },
      {
        id: "r4_note",
        kind: "text",
        x: 68,
        y: 77,
        w: 26,
        h: 6,
        text: "New enterprise add-ons shipped.",
        fontSize: 1.5,
        fontRole: "body",
        fontWeight: 400,
        color: "textSecondary",
      },
      hrule("rule_bottom", 85, 1),
    ],
  },

  {
    name: "focus-statement",
    description:
      "Centered statement with a short accent-colored underline and optional subtitle. For a single declarative takeaway.",
    elements: [
      {
        id: "title",
        kind: "text",
        x: 7.5,
        y: 26,
        w: 85,
        h: 22,
        text: "Statement of the slide.",
        fontSize: 5.2,
        fontRole: "heading",
        fontWeight: 700,
        color: "textPrimary",
        align: "center",
      },
      {
        id: "underline",
        kind: "shape",
        x: 47,
        y: 50,
        w: 6,
        h: 0.6,
        shape: "rect",
        fill: "accent",
        cornerRadius: 0.2,
      },
      {
        id: "subtitle",
        kind: "text",
        x: 10,
        y: 54,
        w: 80,
        h: 9,
        text: "Supporting subtitle.",
        fontSize: 3,
        fontRole: "heading",
        fontWeight: 500,
        color: "textSecondary",
        align: "center",
      },
    ],
  },

  {
    name: "focus-number-list",
    description:
      "Giant accent figure on the left paired with a 3-item hairline-divided list on the right. For mega-number + what-it-unlocks.",
    notes: [
      "Use when a single number carries the slide and you need to name what it unlocks or what it means. The giant number sits left, the list sits right with 1px hairlines between items. Include the shared header above.",
    ],
    elements: [
      {
        id: "figure",
        kind: "text",
        x: 6,
        y: 34,
        w: 44,
        h: 28,
        text: "2³⁰⁰",
        fontSize: 12,
        fontRole: "heading",
        fontWeight: 400,
        color: "accent",
        align: "left",
        lineHeight: 0.95,
      },
      {
        id: "figure_caption",
        kind: "text",
        x: 6,
        y: 66,
        w: 42,
        h: 14,
        text: "Parallel states a 300-qubit processor can hold — more than there are atoms in the observable universe.",
        fontSize: 1.6,
        fontRole: "body",
        fontWeight: 400,
        color: "textSecondary",
        align: "left",
        lineHeight: 1.5,
      },
      {
        id: "list_label",
        kind: "text",
        x: 54,
        y: 34,
        w: 40,
        h: 3.5,
        text: "WHAT IT UNLOCKS",
        fontSize: 1.4,
        fontRole: "body",
        fontWeight: 500,
        color: "accent",
        fontFamily: "JetBrains Mono",
        letterSpacing: 0.16,
        textTransform: "uppercase",
      },
      {
        id: "list_rule_top",
        kind: "shape",
        shape: "line",
        x: 54,
        y: 40,
        w: 40,
        h: 0,
        stroke: "border",
        strokeWidth: 1,
      },
      {
        id: "item1_heading",
        kind: "text",
        x: 54,
        y: 43,
        w: 40,
        h: 5,
        text: "Cracking current encryption",
        fontSize: 2.2,
        fontRole: "heading",
        fontWeight: 500,
        color: "textPrimary",
      },
      {
        id: "item1_body",
        kind: "text",
        x: 54,
        y: 49,
        w: 40,
        h: 5,
        text: "Shor's algorithm factors large numbers in hours, not eons.",
        fontSize: 1.5,
        fontRole: "body",
        fontWeight: 400,
        color: "textSecondary",
      },
      {
        id: "list_rule_1",
        kind: "shape",
        shape: "line",
        x: 54,
        y: 55,
        w: 40,
        h: 0,
        stroke: "border",
        strokeWidth: 1,
      },
      {
        id: "item2_heading",
        kind: "text",
        x: 54,
        y: 58,
        w: 40,
        h: 5,
        text: "Simulating molecules",
        fontSize: 2.2,
        fontRole: "heading",
        fontWeight: 500,
        color: "textPrimary",
      },
      {
        id: "item2_body",
        kind: "text",
        x: 54,
        y: 64,
        w: 40,
        h: 5,
        text: "Chemistry and drug design at atomic fidelity.",
        fontSize: 1.5,
        fontRole: "body",
        fontWeight: 400,
        color: "textSecondary",
      },
      {
        id: "list_rule_2",
        kind: "shape",
        shape: "line",
        x: 54,
        y: 70,
        w: 40,
        h: 0,
        stroke: "border",
        strokeWidth: 1,
      },
      {
        id: "item3_heading",
        kind: "text",
        x: 54,
        y: 73,
        w: 40,
        h: 5,
        text: "Optimizing the impossible",
        fontSize: 2.2,
        fontRole: "heading",
        fontWeight: 500,
        color: "textPrimary",
      },
      {
        id: "item3_body",
        kind: "text",
        x: 54,
        y: 79,
        w: 40,
        h: 5,
        text: "Routing, logistics, and portfolio problems brute force can't touch.",
        fontSize: 1.5,
        fontRole: "body",
        fontWeight: 400,
        color: "textSecondary",
      },
      {
        id: "list_rule_bottom",
        kind: "shape",
        shape: "line",
        x: 54,
        y: 85,
        w: 40,
        h: 0,
        stroke: "border",
        strokeWidth: 1,
      },
    ],
  },

  {
    name: "takeaways-numbered",
    description:
      "Closing / summary: 3 rows of giant accent number (01/02/03) paired with full-width serif sentences. For 'three things to remember'.",
    notes: [
      "Closing / summary pattern. Each row pairs a giant accent index (01 / 02 / 03) with one full-width serif sentence — use this for 'three things to remember', 'what matters', or 'the key takeaways'. Include the shared header above.",
    ],
    elements: [
      {
        id: "intro",
        kind: "text",
        x: 6,
        y: 32,
        w: 80,
        h: 3.5,
        text: "THREE SENTENCES TO TAKE WITH YOU",
        fontSize: 1.4,
        fontRole: "body",
        fontWeight: 500,
        color: "textMuted",
        fontFamily: "JetBrains Mono",
        letterSpacing: 0.16,
        textTransform: "uppercase",
      },
      {
        id: "num1",
        kind: "text",
        x: 6,
        y: 42,
        w: 10,
        h: 12,
        text: "01",
        fontSize: 7,
        fontRole: "heading",
        fontWeight: 400,
        color: "accent",
        align: "left",
        lineHeight: 1.0,
      },
      {
        id: "sent1",
        kind: "text",
        x: 18,
        y: 44,
        w: 76,
        h: 10,
        text: "Entangled particles share a single state — the outcome is created at measurement, not before.",
        fontSize: 2.8,
        fontRole: "heading",
        fontWeight: 400,
        color: "textPrimary",
        align: "left",
        lineHeight: 1.25,
      },
      {
        id: "num2",
        kind: "text",
        x: 6,
        y: 58,
        w: 10,
        h: 12,
        text: "02",
        fontSize: 7,
        fontRole: "heading",
        fontWeight: 400,
        color: "accent",
        align: "left",
        lineHeight: 1.0,
      },
      {
        id: "sent2",
        kind: "text",
        x: 18,
        y: 60,
        w: 76,
        h: 10,
        text: "This is a physical fact, verified by decades of experiment — not a philosophical stance.",
        fontSize: 2.8,
        fontRole: "heading",
        fontWeight: 400,
        color: "textPrimary",
        align: "left",
        lineHeight: 1.25,
      },
      {
        id: "num3",
        kind: "text",
        x: 6,
        y: 74,
        w: 10,
        h: 12,
        text: "03",
        fontSize: 7,
        fontRole: "heading",
        fontWeight: 400,
        color: "accent",
        align: "left",
        lineHeight: 1.0,
      },
      {
        id: "sent3",
        kind: "text",
        x: 18,
        y: 76,
        w: 76,
        h: 10,
        text: "We've already built real hardware on top of it. The weird part is now also the useful part.",
        fontSize: 2.8,
        fontRole: "heading",
        fontWeight: 400,
        color: "textPrimary",
        align: "left",
        lineHeight: 1.25,
      },
    ],
  },
];

// ---------------------------------------------------------------------------
// Shared header pattern — applied to every content slide (not a full layout)
// ---------------------------------------------------------------------------

/**
 * Elements the LLM should place on every content slide (skip only on cover
 * and chapter-break slides). Rendered into the prompt as-is, so the model
 * can copy the coordinates directly.
 */
export const SHARED_HEADER_ELEMENTS: SlideElement[] = [
  {
    id: "eyebrow",
    kind: "text",
    x: 6,
    y: 9,
    w: 80,
    h: 3.5,
    text: "CHAPTER 01 · SOIL",
    fontSize: 1.4,
    fontRole: "body",
    fontWeight: 500,
    color: "textMuted",
    fontFamily: "JetBrains Mono",
    letterSpacing: 0.16,
    textTransform: "uppercase",
  },
  {
    id: "title",
    kind: "text",
    x: 6,
    y: 14,
    w: 88,
    h: 10,
    text: "Reading your soil",
    fontSize: 5.2,
    fontRole: "heading",
    fontWeight: 400,
    color: "textPrimary",
    align: "left",
    lineHeight: 1.0,
  },
  hrule("rule", 26, 1),
];

const SHARED_HEADER_NOTE =
  "Content below the header starts at y ≥ 30. Skip this pattern on cover and chapter-break slides only.";

/** Render the shared header pattern as JSX prompt prose. */
export function renderSharedHeader(): string {
  return [elementsToJsx(SHARED_HEADER_ELEMENTS), `  ${SHARED_HEADER_NOTE}`].join("\n");
}

// ---------------------------------------------------------------------------
// Prompt rendering
// ---------------------------------------------------------------------------

/** Render the full `LAYOUT_TEMPLATES` array to the prose block the prompt embeds. */
export function renderLayoutTemplates(): string {
  return renderLayoutRecipesImpl(LAYOUT_TEMPLATES);
}

/**
 * Render the catalog as `name — description` bullets for the planning
 * prompt. The LLM returns the short `name`; description is shown so it
 * can match content shape to layout without seeing the element recipes.
 */
export function renderLayoutCatalog(): string {
  return LAYOUT_TEMPLATES.map((t) => `- ${t.name} — ${t.description}`).join("\n");
}

/** Look up a layout template by its exact `name`. Returns null if missing. */
export function getLayoutByName(name: string): LayoutTemplate | null {
  return LAYOUT_TEMPLATES.find((t) => t.name === name) ?? null;
}

/**
 * Render full element recipes for ONLY the named layouts — used by the
 * planning-step tool result to inject just the templates the LLM actually
 * picked, instead of the full catalog.
 *
 * Unknown names are silently skipped; callers that care should validate
 * first via `getLayoutByName`.
 */
export function renderLayoutRecipes(names: string[]): string {
  const seen = new Set<string>();
  const templates: LayoutTemplate[] = [];
  for (const name of names) {
    if (seen.has(name)) continue;
    seen.add(name);
    const t = getLayoutByName(name);
    if (t) templates.push(t);
  }
  return renderLayoutRecipesImpl(templates);
}

function renderLayoutRecipesImpl(templates: LayoutTemplate[]): string {
  return templates
    .map((template) => {
      const lines: string[] = [`${template.name} — ${template.description}:`];
      if (template.notes) {
        for (const note of template.notes) lines.push(`  ${note}`);
      }
      lines.push(elementsToJsx(template.elements));
      return lines.join("\n");
    })
    .join("\n\n");
}

// ---------------------------------------------------------------------------
// LayoutEl -> JSX string (with percent -> pixel conversion)
// ---------------------------------------------------------------------------

/** Render a list of layout elements as JSX fragments, one per block. */
function elementsToJsx(elements: LayoutEl[]): string {
  return elements.map((el) => emitElementJsx(el)).join("\n");
}

function emitElementJsx(el: LayoutEl): string {
  switch (el.kind) {
    case "text":
      return emitText(el);
    case "image":
      return emitImage(el);
    case "shape":
      return emitShape(el);
    case "icon":
      return emitIcon(el);
  }
}

function emitText(el: TextLayoutEl): string {
  const attrs: string[] = [
    attr("id", el.id),
    numAttr("x", pxX(el.x)),
    numAttr("y", pxY(el.y)),
    numAttr("w", pxW(el.w)),
    numAttr("h", pxH(el.h)),
  ];
  if (el.rotation !== undefined) attrs.push(numAttr("rotation", el.rotation));
  attrs.push(numAttr("fontSize", pxFontSize(el.fontSize)));
  attrs.push(attr("fontRole", el.fontRole));
  attrs.push(numAttr("fontWeight", el.fontWeight));
  attrs.push(attr("color", el.color));
  if (el.align !== undefined) attrs.push(attr("align", el.align));
  if (el.lineHeight !== undefined) attrs.push(numAttr("lineHeight", el.lineHeight));
  if (el.letterSpacing !== undefined) attrs.push(numAttr("letterSpacing", el.letterSpacing));
  if (el.fontStyle !== undefined) attrs.push(attr("fontStyle", el.fontStyle));
  if (el.textTransform !== undefined) attrs.push(attr("textTransform", el.textTransform));
  if (el.fontFamily !== undefined) attrs.push(attr("fontFamily", el.fontFamily));
  const body = renderTextBody(el.text);
  return `<Anuma.Text ${attrs.join(" ")}>${body}</Anuma.Text>`;
}

function emitImage(el: ImageLayoutEl): string {
  const attrs = commonAttrs(el);
  attrs.push(attr("src", el.src));
  if (el.cornerRadius !== undefined) attrs.push(numAttr("cornerRadius", el.cornerRadius));
  return `<Anuma.Image ${attrs.join(" ")} />`;
}

function emitShape(el: ShapeLayoutEl): string {
  const tag = el.shape === "rect" ? "Rect" : el.shape === "circle" ? "Circle" : "Line";
  const attrs = commonAttrs(el);
  if (el.fill !== undefined) attrs.push(attr("fill", el.fill));
  if (el.stroke !== undefined) attrs.push(attr("stroke", el.stroke));
  if (el.strokeWidth !== undefined) attrs.push(numAttr("strokeWidth", el.strokeWidth));
  if (el.cornerRadius !== undefined) attrs.push(numAttr("cornerRadius", el.cornerRadius));
  return `<Anuma.${tag} ${attrs.join(" ")} />`;
}

function emitIcon(el: IconLayoutEl): string {
  const attrs = commonAttrs(el);
  attrs.push(attr("name", el.name));
  attrs.push(attr("color", el.color));
  attrs.push(numAttr("fontSize", pxFontSize(el.fontSize)));
  return `<Anuma.Icon ${attrs.join(" ")} />`;
}

function commonAttrs(el: BaseEl): string[] {
  const out = [
    attr("id", el.id),
    numAttr("x", pxX(el.x)),
    numAttr("y", pxY(el.y)),
    numAttr("w", pxW(el.w)),
    numAttr("h", pxH(el.h)),
  ];
  if (el.rotation !== undefined) out.push(numAttr("rotation", el.rotation));
  return out;
}

function attr(name: string, value: string): string {
  return `${name}=${JSON.stringify(value)}`;
}

function numAttr(name: string, value: number): string {
  return `${name}={${value}}`;
}

function renderTextBody(text: string): string {
  if (text === "") return "";
  if (/[<>{}&]/.test(text) || /\n/.test(text) || /^\s|\s$/.test(text)) {
    return `{${JSON.stringify(text)}}`;
  }
  return text;
}
