/**
 * # @anuma/sdk
 *
 * A TypeScript SDK that empowers developers to build AI-powered applications. It
 * enables you to send prompts to LLMs with streaming support, manage long-term
 * memories, and encrypt sensitive data, all without needing your own LLM API key.
 *
 * ## Installation
 *
 * ```bash
 * pnpm install @anuma/sdk@next
 * ```
 *
 * > **Note:** Currently, the SDK is pre-release so all new versions are released
 * > under the `next` tag (released on every merge to the `main` branch). Check out
 * > npm to see the latest version.
 *
 * ## Configuration
 *
 * To use the SDK, you'll need to configure your Privy provider and API URL.
 *
 * ```env
 * PRIVY_APP_ID=cmhwlx82v000xle0cde4rjy5y
 * API_URL=https://portal.anuma-dev.ai
 * ```
 *
 * ## Authentication
 *
 * The SDK currently only supports authentication via [Privy](https://privy.io) and
 * expects a Privy identity token.
 *
 * ```typescript
 * import { useIdentityToken } from "@privy-io/react-auth";
 *
 * const { identityToken } = useIdentityToken();
 * ```
 *
 * ## Quick Start
 *
 * For React applications, use the hooks from `@anuma/sdk/react`:
 *
 * ```typescript
 * import { useChat } from "@anuma/sdk/react";
 *
 * const { sendMessage, isLoading, stop } = useChat({
 *   getToken: async () => identityToken || null,
 *   onFinish: (response) => console.log("Chat finished:", response),
 *   onError: (error) => console.error("Chat error:", error),
 *   onData: (chunk) => console.log("Received chunk:", chunk),
 * });
 *
 * await sendMessage({
 *   messages: [{ role: "user", content: [{ type: "text", text: "Hello!" }] }],
 *   model: "fireworks/accounts/fireworks/models/kimi-k2p5",
 * });
 * ```
 *
 * For React Native/Expo, use `@anuma/sdk/expo` instead.
 *
 * For direct API access without React hooks, use the functions from this package:
 *
 * ```typescript
 * import { postApiV1Responses } from "@anuma/sdk";
 *
 * const response = await postApiV1Responses({
 *   body: {
 *     messages: [{ role: "user", content: [{ type: "text", text: "Tell me a joke" }] }],
 *     model: "fireworks/accounts/fireworks/models/kimi-k2p5",
 *   },
 *   headers: {
 *     Authorization: `Bearer ${identityToken}`,
 *   },
 * });
 * ```
 *
 * ## Available Packages
 *
 * - `@anuma/sdk` - Core SDK with direct API access functions
 * - `@anuma/sdk/react` - React hooks for web applications
 * - `@anuma/sdk/expo` - React hooks optimized for React Native/Expo
 * - `@anuma/sdk/next` - Next.js utilities
 * - `@anuma/sdk/vercel` - Vercel platform utilities
 * - `@anuma/sdk/polyfills` - Polyfills for React Native environments
 *
 * ## Example Usage
 *
 * For a complete example of how to use this SDK, check out
 * [the example repo](https://github.com/zeta-chain/ai-examples).
 *
 * @module
 */
// Explicit re-exports from the auto-generated HTTP client. This list is
// generated from src/client/sdk.gen.ts (values) and src/client/types.gen.ts
// (types) to preserve tree-shaking for consumers of "@anuma/sdk". When
// `pnpm run spec` regenerates the client, refresh this block — `pnpm run
// check-exports` (publint + attw) will flag drift.
export type {
  ClientOptions,
  DeleteApiV1AccountData,
  DeleteApiV1AccountError,
  DeleteApiV1AccountErrors,
  DeleteApiV1AccountResponse,
  DeleteApiV1AccountResponses,
  DeleteApiV1AdminAgentsByIdData,
  DeleteApiV1AdminAgentsByIdError,
  DeleteApiV1AdminAgentsByIdErrors,
  DeleteApiV1AdminAgentsByIdResponse,
  DeleteApiV1AdminAgentsByIdResponses,
  DeleteApiV1AdminAppsByAppIdApiKeysByIdData,
  DeleteApiV1AdminAppsByAppIdApiKeysByIdError,
  DeleteApiV1AdminAppsByAppIdApiKeysByIdErrors,
  DeleteApiV1AdminAppsByAppIdApiKeysByIdResponse,
  DeleteApiV1AdminAppsByAppIdApiKeysByIdResponses,
  DeleteApiV1AdminAppsByIdData,
  DeleteApiV1AdminAppsByIdError,
  DeleteApiV1AdminAppsByIdErrors,
  DeleteApiV1AdminAppsByIdResponse,
  DeleteApiV1AdminAppsByIdResponses,
  DeleteApiV1AdminPersonasByIdData,
  DeleteApiV1AdminPersonasByIdError,
  DeleteApiV1AdminPersonasByIdErrors,
  DeleteApiV1AdminPersonasByIdResponse,
  DeleteApiV1AdminPersonasByIdResponses,
  DeleteApiV1AdminTextResetData,
  DeleteApiV1AdminTextResetError,
  DeleteApiV1AdminTextResetErrors,
  DeleteApiV1AdminTextResetResponse,
  DeleteApiV1AdminTextResetResponses,
  DeleteApiV1DeveloperAppsByAppUuidApiKeysByKeyIdData,
  DeleteApiV1DeveloperAppsByAppUuidApiKeysByKeyIdError,
  DeleteApiV1DeveloperAppsByAppUuidApiKeysByKeyIdErrors,
  DeleteApiV1DeveloperAppsByAppUuidApiKeysByKeyIdResponse,
  DeleteApiV1DeveloperAppsByAppUuidApiKeysByKeyIdResponses,
  DeleteApiV1DeveloperAppsByAppUuidData,
  DeleteApiV1DeveloperAppsByAppUuidError,
  DeleteApiV1DeveloperAppsByAppUuidErrors,
  DeleteApiV1DeveloperAppsByAppUuidPrivyData,
  DeleteApiV1DeveloperAppsByAppUuidPrivyError,
  DeleteApiV1DeveloperAppsByAppUuidPrivyErrors,
  DeleteApiV1DeveloperAppsByAppUuidPrivyResponse,
  DeleteApiV1DeveloperAppsByAppUuidPrivyResponses,
  DeleteApiV1DeveloperAppsByAppUuidResponse,
  DeleteApiV1DeveloperAppsByAppUuidResponses,
  DeleteApiV1TextByChannelUnregisterData,
  DeleteApiV1TextByChannelUnregisterError,
  DeleteApiV1TextByChannelUnregisterErrors,
  DeleteApiV1TextByChannelUnregisterResponse,
  DeleteApiV1TextByChannelUnregisterResponses,
  DeleteApiV1UserApiKeysByKeyIdData,
  DeleteApiV1UserApiKeysByKeyIdError,
  DeleteApiV1UserApiKeysByKeyIdErrors,
  DeleteApiV1UserApiKeysByKeyIdResponse,
  DeleteApiV1UserApiKeysByKeyIdResponses,
  GetApiV1AdminAppsByAppIdApiKeysByIdData,
  GetApiV1AdminAppsByAppIdApiKeysByIdError,
  GetApiV1AdminAppsByAppIdApiKeysByIdErrors,
  GetApiV1AdminAppsByAppIdApiKeysByIdResponse,
  GetApiV1AdminAppsByAppIdApiKeysByIdResponses,
  GetApiV1AdminAppsByAppIdApiKeysData,
  GetApiV1AdminAppsByAppIdApiKeysError,
  GetApiV1AdminAppsByAppIdApiKeysErrors,
  GetApiV1AdminAppsByAppIdApiKeysResponse,
  GetApiV1AdminAppsByAppIdApiKeysResponses,
  GetApiV1AdminAppsByIdData,
  GetApiV1AdminAppsByIdError,
  GetApiV1AdminAppsByIdErrors,
  GetApiV1AdminAppsByIdResponse,
  GetApiV1AdminAppsByIdResponses,
  GetApiV1AdminAppsData,
  GetApiV1AdminAppsError,
  GetApiV1AdminAppsErrors,
  GetApiV1AdminAppsResponse,
  GetApiV1AdminAppsResponses,
  GetApiV1AdminUsersLookupData,
  GetApiV1AdminUsersLookupError,
  GetApiV1AdminUsersLookupErrors,
  GetApiV1AdminUsersLookupResponse,
  GetApiV1AdminUsersLookupResponses,
  GetApiV1AgentPreferencesData,
  GetApiV1AgentPreferencesError,
  GetApiV1AgentPreferencesErrors,
  GetApiV1AgentPreferencesResponse,
  GetApiV1AgentPreferencesResponses,
  GetApiV1AgentsByIdData,
  GetApiV1AgentsByIdError,
  GetApiV1AgentsByIdErrors,
  GetApiV1AgentsByIdResponse,
  GetApiV1AgentsByIdResponses,
  GetApiV1AgentsData,
  GetApiV1AgentsError,
  GetApiV1AgentsErrors,
  GetApiV1AgentsResponse,
  GetApiV1AgentsResponses,
  GetApiV1ConfigData,
  GetApiV1ConfigError,
  GetApiV1ConfigErrors,
  GetApiV1ConfigResponse,
  GetApiV1ConfigResponses,
  GetApiV1CreditsBalanceData,
  GetApiV1CreditsBalanceError,
  GetApiV1CreditsBalanceErrors,
  GetApiV1CreditsBalanceResponse,
  GetApiV1CreditsBalanceResponses,
  GetApiV1CreditsPacksData,
  GetApiV1CreditsPacksError,
  GetApiV1CreditsPacksErrors,
  GetApiV1CreditsPacksResponse,
  GetApiV1CreditsPacksResponses,
  GetApiV1DeveloperAppsByAppUuidApiKeysData,
  GetApiV1DeveloperAppsByAppUuidApiKeysError,
  GetApiV1DeveloperAppsByAppUuidApiKeysErrors,
  GetApiV1DeveloperAppsByAppUuidApiKeysResponse,
  GetApiV1DeveloperAppsByAppUuidApiKeysResponses,
  GetApiV1DeveloperAppsByAppUuidData,
  GetApiV1DeveloperAppsByAppUuidError,
  GetApiV1DeveloperAppsByAppUuidErrors,
  GetApiV1DeveloperAppsByAppUuidResponse,
  GetApiV1DeveloperAppsByAppUuidResponses,
  GetApiV1DeveloperAppsByAppUuidUsageData,
  GetApiV1DeveloperAppsByAppUuidUsageError,
  GetApiV1DeveloperAppsByAppUuidUsageErrors,
  GetApiV1DeveloperAppsByAppUuidUsageResponse,
  GetApiV1DeveloperAppsByAppUuidUsageResponses,
  GetApiV1DeveloperAppsByAppUuidUsageUsersData,
  GetApiV1DeveloperAppsByAppUuidUsageUsersError,
  GetApiV1DeveloperAppsByAppUuidUsageUsersErrors,
  GetApiV1DeveloperAppsByAppUuidUsageUsersResponse,
  GetApiV1DeveloperAppsByAppUuidUsageUsersResponses,
  GetApiV1DeveloperAppsByAppUuidUsersByAddressData,
  GetApiV1DeveloperAppsByAppUuidUsersByAddressError,
  GetApiV1DeveloperAppsByAppUuidUsersByAddressErrors,
  GetApiV1DeveloperAppsByAppUuidUsersByAddressResponse,
  GetApiV1DeveloperAppsByAppUuidUsersByAddressResponses,
  GetApiV1DeveloperAppsByAppUuidUsersData,
  GetApiV1DeveloperAppsByAppUuidUsersError,
  GetApiV1DeveloperAppsByAppUuidUsersErrors,
  GetApiV1DeveloperAppsByAppUuidUsersResponse,
  GetApiV1DeveloperAppsByAppUuidUsersResponses,
  GetApiV1DeveloperAppsData,
  GetApiV1DeveloperAppsError,
  GetApiV1DeveloperAppsErrors,
  GetApiV1DeveloperAppsResponse,
  GetApiV1DeveloperAppsResponses,
  GetApiV1DeveloperBillingData,
  GetApiV1DeveloperBillingError,
  GetApiV1DeveloperBillingErrors,
  GetApiV1DeveloperBillingResponse,
  GetApiV1DeveloperBillingResponses,
  GetApiV1DocsSwaggerJsonData,
  GetApiV1DocsSwaggerJsonResponse,
  GetApiV1DocsSwaggerJsonResponses,
  GetApiV1ModelsData,
  GetApiV1ModelsError,
  GetApiV1ModelsErrors,
  GetApiV1ModelsResponse,
  GetApiV1ModelsResponses,
  GetApiV1PersonasByIdData,
  GetApiV1PersonasByIdError,
  GetApiV1PersonasByIdErrors,
  GetApiV1PersonasByIdResponse,
  GetApiV1PersonasByIdResponses,
  GetApiV1PersonasData,
  GetApiV1PersonasError,
  GetApiV1PersonasErrors,
  GetApiV1PersonasResponse,
  GetApiV1PersonasResponses,
  GetApiV1PhoneCallsByCallIdData,
  GetApiV1PhoneCallsByCallIdError,
  GetApiV1PhoneCallsByCallIdErrors,
  GetApiV1PhoneCallsByCallIdResponse,
  GetApiV1PhoneCallsByCallIdResponses,
  GetApiV1SubscriptionsPlansData,
  GetApiV1SubscriptionsPlansError,
  GetApiV1SubscriptionsPlansErrors,
  GetApiV1SubscriptionsPlansResponse,
  GetApiV1SubscriptionsPlansResponses,
  GetApiV1SubscriptionsStatusData,
  GetApiV1SubscriptionsStatusError,
  GetApiV1SubscriptionsStatusErrors,
  GetApiV1SubscriptionsStatusResponse,
  GetApiV1SubscriptionsStatusResponses,
  GetApiV1TasksData,
  GetApiV1TasksError,
  GetApiV1TasksErrors,
  GetApiV1TasksResponse,
  GetApiV1TasksResponses,
  GetApiV1TextByChannelLookupData,
  GetApiV1TextByChannelLookupError,
  GetApiV1TextByChannelLookupErrors,
  GetApiV1TextByChannelLookupResponse,
  GetApiV1TextByChannelLookupResponses,
  GetApiV1TextByChannelStatusData,
  GetApiV1TextByChannelStatusError,
  GetApiV1TextByChannelStatusErrors,
  GetApiV1TextByChannelStatusResponse,
  GetApiV1TextByChannelStatusResponses,
  GetApiV1ToolsData,
  GetApiV1ToolsError,
  GetApiV1ToolsErrors,
  GetApiV1ToolsResponse,
  GetApiV1ToolsResponses,
  GetApiV1UsageModelsData,
  GetApiV1UsageModelsError,
  GetApiV1UsageModelsErrors,
  GetApiV1UsageModelsResponse,
  GetApiV1UsageModelsResponses,
  GetApiV1UserApiKeysData,
  GetApiV1UserApiKeysError,
  GetApiV1UserApiKeysErrors,
  GetApiV1UserApiKeysResponse,
  GetApiV1UserApiKeysResponses,
  GetHealthData,
  GetHealthError,
  GetHealthErrors,
  GetHealthResponse,
  GetHealthResponses,
  HandlersAddCreditsRequest,
  HandlersAddCreditsResponse,
  HandlersAgentListItem,
  HandlersAgentListResponse,
  HandlersAgentResponse,
  HandlersApiKeyResponse,
  HandlersApiKeyWithKeyResponse,
  HandlersAppConfig,
  HandlersAppResponse,
  HandlersAppUsageResponse,
  HandlersAppUserUsageResponse,
  HandlersBillingHistoryResponse,
  HandlersBillingRecordResponse,
  HandlersCancelScheduledDowngradeResponse,
  HandlersCancelSubscriptionResponse,
  HandlersCheckoutSessionResponse,
  HandlersClaimDailyCreditsResponse,
  HandlersClaimTaskRewardRequest,
  HandlersClaimTaskRewardResponse,
  HandlersConfigResponse,
  HandlersConfigurePrivyRequest,
  HandlersCreateAgentRequest,
  HandlersCreateApiKeyRequest,
  HandlersCreateAppRequest,
  HandlersCreateCheckoutSessionRequest,
  HandlersCreateCreditPackCheckoutRequest,
  HandlersCreateCustomerPortalRequest,
  HandlersCreateDeveloperAppRequest,
  HandlersCreatePersonaRequest,
  HandlersCreatePhoneCallRequest,
  HandlersCreditBalanceResponse,
  HandlersCreditPack,
  HandlersCreditPacksResponse,
  HandlersCustomerPortalResponse,
  HandlersDeveloperApiKeyRequest,
  HandlersDeveloperApiKeyResponse,
  HandlersDeveloperApiKeyWithSecretResponse,
  HandlersDeveloperAppResponse,
  HandlersDeveloperUserResponse,
  HandlersExchangeRequest,
  HandlersExpiringCredits,
  HandlersFundDeveloperAppRequest,
  HandlersGeneratedApiKey,
  HandlersGetToolsResponse,
  HandlersHealthResponse,
  HandlersListApiKeysResponse,
  HandlersListAppsResponse,
  HandlersListDeveloperApiKeysResponse,
  HandlersListDeveloperAppsResponse,
  HandlersListUserApiKeysResponse,
  HandlersListUsersResponse,
  HandlersModelToolUsageItem,
  HandlersModelUsageItem,
  HandlersPaginationResponse,
  HandlersPersonaListResponse,
  HandlersPersonaResponse,
  HandlersPhoneCallResponse,
  HandlersPhoneCallTranscriptEntry,
  HandlersRedeemTokensRequest,
  HandlersRedeemTokensResponse,
  HandlersRefreshRequest,
  HandlersRegisterTextResponse,
  HandlersRenewSubscriptionResponse,
  HandlersRevokeRequest,
  HandlersScheduleDowngradeRequest,
  HandlersScheduleDowngradeResponse,
  HandlersSeedApiKeyInput,
  HandlersSeedAppInput,
  HandlersSeedAppsRequest,
  HandlersSeedAppsResponse,
  HandlersSetSubscriptionTierRequest,
  HandlersSetSubscriptionTierResponse,
  HandlersSetUserAgentPreferenceRequest,
  HandlersSubscriptionPlan,
  HandlersSubscriptionPlansResponse,
  HandlersSubscriptionStatusResponse,
  HandlersSyncSnagResponse,
  HandlersTaskResponse,
  HandlersTokenResponse,
  HandlersTool,
  HandlersToolCallDetailItem,
  HandlersTopUpUserRequest,
  HandlersUnregisterTextResponse,
  HandlersUpdateAgentRequest,
  HandlersUpdateApiKeyRequest,
  HandlersUpdateAppRequest,
  HandlersUpdateDeveloperAppRequest,
  HandlersUpdatePersonaRequest,
  HandlersUpdateUserLimitRequest,
  HandlersUpgradeSubscriptionRequest,
  HandlersUpgradeSubscriptionResponse,
  HandlersUsageByModelResponse,
  HandlersUsagePeriod,
  HandlersUsageTimeseriesPoint,
  HandlersUsageTotals,
  HandlersUserAgentPreferenceResponse,
  HandlersUserAgentPreferencesListResponse,
  HandlersUserApiKeyRequest,
  HandlersUserApiKeyResponse,
  HandlersUserApiKeyWithSecretResponse,
  HandlersUserLookupAccount,
  HandlersUserLookupEnrollment,
  HandlersUserLookupResponse,
  HandlersUserLookupTextReg,
  HandlersUserUsageResponse,
  HandlersWalletDetails,
  LlmapiChatCompletionExtraFields,
  LlmapiChatCompletionRequest,
  LlmapiChatCompletionResponse,
  LlmapiChatCompletionTool,
  LlmapiChatCompletionToolChoice,
  LlmapiChatCompletionUsage,
  LlmapiChoice,
  LlmapiEmbeddingData,
  LlmapiEmbeddingExtraFields,
  LlmapiEmbeddingRequest,
  LlmapiEmbeddingResponse,
  LlmapiEmbeddingUsage,
  LlmapiMcpTool,
  LlmapiMessage,
  LlmapiMessageContentFile,
  LlmapiMessageContentImage,
  LlmapiMessageContentPart,
  LlmapiModel,
  LlmapiModelArchitecture,
  LlmapiModelPerRequestLimits,
  LlmapiModelPricing,
  LlmapiModelsListExtraFields,
  LlmapiModelsListResponse,
  LlmapiModelTopProvider,
  LlmapiResponseExtraFields,
  LlmapiResponseInput,
  LlmapiResponseOutputContent,
  LlmapiResponseOutputItem,
  LlmapiResponseReasoning,
  LlmapiResponseRequest,
  LlmapiResponseResponse,
  LlmapiResponseTool,
  LlmapiResponseToolChoice,
  LlmapiResponseUsage,
  LlmapiRole,
  LlmapiThinkingOptions,
  LlmapiToolCall,
  LlmapiToolCallEvent,
  LlmapiToolCallFunction,
  McpToolSchema,
  ModelsReferralRewardRequest,
  ModelsReferralRewardResponse,
  ModelsRegisterTextRequest,
  ModelsTextChannel,
  ModelsTextLookupResult,
  ModelsTextStatusResponse,
  Options,
  PatchApiV1DeveloperAppsByAppUuidData,
  PatchApiV1DeveloperAppsByAppUuidError,
  PatchApiV1DeveloperAppsByAppUuidErrors,
  PatchApiV1DeveloperAppsByAppUuidResponse,
  PatchApiV1DeveloperAppsByAppUuidResponses,
  PatchApiV1DeveloperAppsByAppUuidUsersByAddressData,
  PatchApiV1DeveloperAppsByAppUuidUsersByAddressError,
  PatchApiV1DeveloperAppsByAppUuidUsersByAddressErrors,
  PatchApiV1DeveloperAppsByAppUuidUsersByAddressResponse,
  PatchApiV1DeveloperAppsByAppUuidUsersByAddressResponses,
  PostApiV1AdminAddCreditsData,
  PostApiV1AdminAddCreditsError,
  PostApiV1AdminAddCreditsErrors,
  PostApiV1AdminAddCreditsResponse,
  PostApiV1AdminAddCreditsResponses,
  PostApiV1AdminAgentsData,
  PostApiV1AdminAgentsError,
  PostApiV1AdminAgentsErrors,
  PostApiV1AdminAgentsResponse,
  PostApiV1AdminAgentsResponses,
  PostApiV1AdminAppsByAppIdApiKeysData,
  PostApiV1AdminAppsByAppIdApiKeysError,
  PostApiV1AdminAppsByAppIdApiKeysErrors,
  PostApiV1AdminAppsByAppIdApiKeysResponse,
  PostApiV1AdminAppsByAppIdApiKeysResponses,
  PostApiV1AdminAppsData,
  PostApiV1AdminAppsError,
  PostApiV1AdminAppsErrors,
  PostApiV1AdminAppsResponse,
  PostApiV1AdminAppsResponses,
  PostApiV1AdminPersonasData,
  PostApiV1AdminPersonasError,
  PostApiV1AdminPersonasErrors,
  PostApiV1AdminPersonasResponse,
  PostApiV1AdminPersonasResponses,
  PostApiV1AdminSeedAppsData,
  PostApiV1AdminSeedAppsError,
  PostApiV1AdminSeedAppsErrors,
  PostApiV1AdminSeedAppsResponse,
  PostApiV1AdminSeedAppsResponses,
  PostApiV1AdminSubscriptionTierData,
  PostApiV1AdminSubscriptionTierError,
  PostApiV1AdminSubscriptionTierErrors,
  PostApiV1AdminSubscriptionTierResponse,
  PostApiV1AdminSubscriptionTierResponses,
  PostApiV1ChatCompletionsData,
  PostApiV1ChatCompletionsError,
  PostApiV1ChatCompletionsErrors,
  PostApiV1ChatCompletionsResponse,
  PostApiV1ChatCompletionsResponses,
  PostApiV1CreditsClaimDailyData,
  PostApiV1CreditsClaimDailyError,
  PostApiV1CreditsClaimDailyErrors,
  PostApiV1CreditsClaimDailyResponse,
  PostApiV1CreditsClaimDailyResponses,
  PostApiV1CreditsClaimTaskData,
  PostApiV1CreditsClaimTaskError,
  PostApiV1CreditsClaimTaskErrors,
  PostApiV1CreditsClaimTaskResponse,
  PostApiV1CreditsClaimTaskResponses,
  PostApiV1CreditsPurchaseData,
  PostApiV1CreditsPurchaseError,
  PostApiV1CreditsPurchaseErrors,
  PostApiV1CreditsPurchaseResponse,
  PostApiV1CreditsPurchaseResponses,
  PostApiV1CreditsRedeemTokensData,
  PostApiV1CreditsRedeemTokensError,
  PostApiV1CreditsRedeemTokensErrors,
  PostApiV1CreditsRedeemTokensResponse,
  PostApiV1CreditsRedeemTokensResponses,
  PostApiV1CreditsSyncSnagData,
  PostApiV1CreditsSyncSnagError,
  PostApiV1CreditsSyncSnagErrors,
  PostApiV1CreditsSyncSnagResponse,
  PostApiV1CreditsSyncSnagResponses,
  PostApiV1DeveloperAppsByAppUuidApiKeysData,
  PostApiV1DeveloperAppsByAppUuidApiKeysError,
  PostApiV1DeveloperAppsByAppUuidApiKeysErrors,
  PostApiV1DeveloperAppsByAppUuidApiKeysResponse,
  PostApiV1DeveloperAppsByAppUuidApiKeysResponses,
  PostApiV1DeveloperAppsByAppUuidFundData,
  PostApiV1DeveloperAppsByAppUuidFundError,
  PostApiV1DeveloperAppsByAppUuidFundErrors,
  PostApiV1DeveloperAppsByAppUuidFundResponse,
  PostApiV1DeveloperAppsByAppUuidFundResponses,
  PostApiV1DeveloperAppsByAppUuidPrivyData,
  PostApiV1DeveloperAppsByAppUuidPrivyError,
  PostApiV1DeveloperAppsByAppUuidPrivyErrors,
  PostApiV1DeveloperAppsByAppUuidPrivyResponse,
  PostApiV1DeveloperAppsByAppUuidPrivyResponses,
  PostApiV1DeveloperAppsByAppUuidUsersByAddressTopUpData,
  PostApiV1DeveloperAppsByAppUuidUsersByAddressTopUpError,
  PostApiV1DeveloperAppsByAppUuidUsersByAddressTopUpErrors,
  PostApiV1DeveloperAppsByAppUuidUsersByAddressTopUpResponse,
  PostApiV1DeveloperAppsByAppUuidUsersByAddressTopUpResponses,
  PostApiV1DeveloperAppsData,
  PostApiV1DeveloperAppsError,
  PostApiV1DeveloperAppsErrors,
  PostApiV1DeveloperAppsResponse,
  PostApiV1DeveloperAppsResponses,
  PostApiV1EmbeddingsData,
  PostApiV1EmbeddingsError,
  PostApiV1EmbeddingsErrors,
  PostApiV1EmbeddingsResponse,
  PostApiV1EmbeddingsResponses,
  PostApiV1PhoneCallsData,
  PostApiV1PhoneCallsError,
  PostApiV1PhoneCallsErrors,
  PostApiV1PhoneCallsResponse,
  PostApiV1PhoneCallsResponses,
  PostApiV1ResponsesData,
  PostApiV1ResponsesError,
  PostApiV1ResponsesErrors,
  PostApiV1ResponsesResponse,
  PostApiV1ResponsesResponses,
  PostApiV1SubscriptionsCancelData,
  PostApiV1SubscriptionsCancelError,
  PostApiV1SubscriptionsCancelErrors,
  PostApiV1SubscriptionsCancelResponse,
  PostApiV1SubscriptionsCancelResponses,
  PostApiV1SubscriptionsCancelScheduledDowngradeData,
  PostApiV1SubscriptionsCancelScheduledDowngradeError,
  PostApiV1SubscriptionsCancelScheduledDowngradeErrors,
  PostApiV1SubscriptionsCancelScheduledDowngradeResponse,
  PostApiV1SubscriptionsCancelScheduledDowngradeResponses,
  PostApiV1SubscriptionsCreateCheckoutSessionData,
  PostApiV1SubscriptionsCreateCheckoutSessionError,
  PostApiV1SubscriptionsCreateCheckoutSessionErrors,
  PostApiV1SubscriptionsCreateCheckoutSessionResponse,
  PostApiV1SubscriptionsCreateCheckoutSessionResponses,
  PostApiV1SubscriptionsCustomerPortalData,
  PostApiV1SubscriptionsCustomerPortalError,
  PostApiV1SubscriptionsCustomerPortalErrors,
  PostApiV1SubscriptionsCustomerPortalResponse,
  PostApiV1SubscriptionsCustomerPortalResponses,
  PostApiV1SubscriptionsRenewData,
  PostApiV1SubscriptionsRenewError,
  PostApiV1SubscriptionsRenewErrors,
  PostApiV1SubscriptionsRenewResponse,
  PostApiV1SubscriptionsRenewResponses,
  PostApiV1SubscriptionsScheduleDowngradeData,
  PostApiV1SubscriptionsScheduleDowngradeError,
  PostApiV1SubscriptionsScheduleDowngradeErrors,
  PostApiV1SubscriptionsScheduleDowngradeResponse,
  PostApiV1SubscriptionsScheduleDowngradeResponses,
  PostApiV1SubscriptionsUpgradeData,
  PostApiV1SubscriptionsUpgradeError,
  PostApiV1SubscriptionsUpgradeErrors,
  PostApiV1SubscriptionsUpgradeResponse,
  PostApiV1SubscriptionsUpgradeResponses,
  PostApiV1SubscriptionsWebhookData,
  PostApiV1SubscriptionsWebhookError,
  PostApiV1SubscriptionsWebhookErrors,
  PostApiV1SubscriptionsWebhookResponse,
  PostApiV1SubscriptionsWebhookResponses,
  PostApiV1TextByChannelRegisterData,
  PostApiV1TextByChannelRegisterError,
  PostApiV1TextByChannelRegisterErrors,
  PostApiV1TextByChannelRegisterResponse,
  PostApiV1TextByChannelRegisterResponses,
  PostApiV1TextReferralRewardData,
  PostApiV1TextReferralRewardError,
  PostApiV1TextReferralRewardErrors,
  PostApiV1TextReferralRewardResponse,
  PostApiV1TextReferralRewardResponses,
  PostApiV1UserApiKeysData,
  PostApiV1UserApiKeysError,
  PostApiV1UserApiKeysErrors,
  PostApiV1UserApiKeysResponse,
  PostApiV1UserApiKeysResponses,
  PostApiV1WebhooksRevenuecatData,
  PostApiV1WebhooksRevenuecatError,
  PostApiV1WebhooksRevenuecatErrors,
  PostApiV1WebhooksRevenuecatResponse,
  PostApiV1WebhooksRevenuecatResponses,
  PostAuthOauthByProviderExchangeData,
  PostAuthOauthByProviderExchangeError,
  PostAuthOauthByProviderExchangeErrors,
  PostAuthOauthByProviderExchangeResponse,
  PostAuthOauthByProviderExchangeResponses,
  PostAuthOauthByProviderRefreshData,
  PostAuthOauthByProviderRefreshError,
  PostAuthOauthByProviderRefreshErrors,
  PostAuthOauthByProviderRefreshResponse,
  PostAuthOauthByProviderRefreshResponses,
  PostAuthOauthByProviderRevokeData,
  PostAuthOauthByProviderRevokeError,
  PostAuthOauthByProviderRevokeErrors,
  PostAuthOauthByProviderRevokeResponse,
  PostAuthOauthByProviderRevokeResponses,
  PutApiV1AdminAgentsByIdData,
  PutApiV1AdminAgentsByIdError,
  PutApiV1AdminAgentsByIdErrors,
  PutApiV1AdminAgentsByIdResponse,
  PutApiV1AdminAgentsByIdResponses,
  PutApiV1AdminAppsByAppIdApiKeysByIdData,
  PutApiV1AdminAppsByAppIdApiKeysByIdError,
  PutApiV1AdminAppsByAppIdApiKeysByIdErrors,
  PutApiV1AdminAppsByAppIdApiKeysByIdResponse,
  PutApiV1AdminAppsByAppIdApiKeysByIdResponses,
  PutApiV1AdminAppsByIdData,
  PutApiV1AdminAppsByIdError,
  PutApiV1AdminAppsByIdErrors,
  PutApiV1AdminAppsByIdResponse,
  PutApiV1AdminAppsByIdResponses,
  PutApiV1AdminPersonasByIdData,
  PutApiV1AdminPersonasByIdError,
  PutApiV1AdminPersonasByIdErrors,
  PutApiV1AdminPersonasByIdResponse,
  PutApiV1AdminPersonasByIdResponses,
  PutApiV1AgentsByIdPreferenceData,
  PutApiV1AgentsByIdPreferenceError,
  PutApiV1AgentsByIdPreferenceErrors,
  PutApiV1AgentsByIdPreferenceResponse,
  PutApiV1AgentsByIdPreferenceResponses,
  ResponseErrorResponse,
} from "./client";
export {
  deleteApiV1Account,
  deleteApiV1AdminAgentsById,
  deleteApiV1AdminAppsByAppIdApiKeysById,
  deleteApiV1AdminAppsById,
  deleteApiV1AdminPersonasById,
  deleteApiV1AdminTextReset,
  deleteApiV1DeveloperAppsByAppUuid,
  deleteApiV1DeveloperAppsByAppUuidApiKeysByKeyId,
  deleteApiV1DeveloperAppsByAppUuidPrivy,
  deleteApiV1TextByChannelUnregister,
  deleteApiV1UserApiKeysByKeyId,
  getApiV1AdminApps,
  getApiV1AdminAppsByAppIdApiKeys,
  getApiV1AdminAppsByAppIdApiKeysById,
  getApiV1AdminAppsById,
  getApiV1AdminUsersLookup,
  getApiV1AgentPreferences,
  getApiV1Agents,
  getApiV1AgentsById,
  getApiV1Config,
  getApiV1CreditsBalance,
  getApiV1CreditsPacks,
  getApiV1DeveloperApps,
  getApiV1DeveloperAppsByAppUuid,
  getApiV1DeveloperAppsByAppUuidApiKeys,
  getApiV1DeveloperAppsByAppUuidUsage,
  getApiV1DeveloperAppsByAppUuidUsageUsers,
  getApiV1DeveloperAppsByAppUuidUsers,
  getApiV1DeveloperAppsByAppUuidUsersByAddress,
  getApiV1DeveloperBilling,
  getApiV1DocsSwaggerJson,
  getApiV1Models,
  getApiV1Personas,
  getApiV1PersonasById,
  getApiV1PhoneCallsByCallId,
  getApiV1SubscriptionsPlans,
  getApiV1SubscriptionsStatus,
  getApiV1Tasks,
  getApiV1TextByChannelLookup,
  getApiV1TextByChannelStatus,
  getApiV1Tools,
  getApiV1UsageModels,
  getApiV1UserApiKeys,
  getHealth,
  patchApiV1DeveloperAppsByAppUuid,
  patchApiV1DeveloperAppsByAppUuidUsersByAddress,
  postApiV1AdminAddCredits,
  postApiV1AdminAgents,
  postApiV1AdminApps,
  postApiV1AdminAppsByAppIdApiKeys,
  postApiV1AdminPersonas,
  postApiV1AdminSeedApps,
  postApiV1AdminSubscriptionTier,
  postApiV1ChatCompletions,
  postApiV1CreditsClaimDaily,
  postApiV1CreditsClaimTask,
  postApiV1CreditsPurchase,
  postApiV1CreditsRedeemTokens,
  postApiV1CreditsSyncSnag,
  postApiV1DeveloperApps,
  postApiV1DeveloperAppsByAppUuidApiKeys,
  postApiV1DeveloperAppsByAppUuidFund,
  postApiV1DeveloperAppsByAppUuidPrivy,
  postApiV1DeveloperAppsByAppUuidUsersByAddressTopUp,
  postApiV1Embeddings,
  postApiV1PhoneCalls,
  postApiV1Responses,
  postApiV1SubscriptionsCancel,
  postApiV1SubscriptionsCancelScheduledDowngrade,
  postApiV1SubscriptionsCreateCheckoutSession,
  postApiV1SubscriptionsCustomerPortal,
  postApiV1SubscriptionsRenew,
  postApiV1SubscriptionsScheduleDowngrade,
  postApiV1SubscriptionsUpgrade,
  postApiV1SubscriptionsWebhook,
  postApiV1TextByChannelRegister,
  postApiV1TextReferralReward,
  postApiV1UserApiKeys,
  postApiV1WebhooksRevenuecat,
  postAuthOauthByProviderExchange,
  postAuthOauthByProviderRefresh,
  postAuthOauthByProviderRevoke,
  putApiV1AdminAgentsById,
  putApiV1AdminAppsByAppIdApiKeysById,
  putApiV1AdminAppsById,
  putApiV1AdminPersonasById,
  putApiV1AgentsByIdPreference,
} from "./client";
export { selectServerSideTools, type SelectServerSideToolsOptions } from "./lib/tools";

// SSE idle-keepalive wrapper for the generated SSE client
export {
  SseIdleTimeoutError,
  type SseKeepaliveOptions,
  withSseKeepalive,
} from "./lib/sse/keepalive";

// Agent types
export type {
  AgentConfig,
  AgentManifest,
  AgentRuntime,
  SkillConfig,
  SkillJourneyDefinition,
  SkillJourneyField,
  SkillJourneyFieldType,
} from "./agent";

// Pluggable logger
export type { Logger } from "./lib/logger";
export { consoleLogger, getLogger, noopLogger, setLogger } from "./lib/logger";

// Persona (prompt building + style analysis)
export type {
  AnalyzeStyleOptions,
  AnalyzeStyleResult,
  BuildPromptOptions,
  BuildPromptResult,
  PromptContext,
  PromptSection,
  PromptTemplates,
  StyleAnalysisSchedule,
} from "./lib/persona";
export {
  analyzeStyle,
  buildSystemPrompt,
  DEFAULT_ANALYSIS_PROMPT,
  DEFAULT_ANALYZE_AFTER_MESSAGES,
  DEFAULT_DOCUMENT_PATTERN,
  DEFAULT_MAX_INPUT_MESSAGES,
  DEFAULT_MAX_PROFILE_LENGTH,
  DEFAULT_MIN_MESSAGES,
  DEFAULT_PROMPT_TEMPLATES,
  DEFAULT_REFRESH_EVERY_MESSAGES,
  renderTemplate,
  sanitizeQuotes,
  shouldAnalyzeStyle,
} from "./lib/persona";
