// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type HandlersApiKeyResponse = {
    app_id?: number;
    created_at?: string;
    /**
     * Indicates if key is set, but doesn't expose it
     */
    has_key?: boolean;
    id?: number;
    is_active?: boolean;
    name?: string;
    updated_at?: string;
    wallet_address?: string;
    wallet_details?: HandlersWalletDetails;
};

export type HandlersApiKeyWithKeyResponse = {
    /**
     * Only included in create response
     */
    api_key?: string;
    app_id?: number;
    created_at?: string;
    id?: number;
    is_active?: boolean;
    name?: string;
    updated_at?: string;
    wallet_address?: string;
};

export type HandlersAddCreditsRequest = {
    /**
     * Number of credits to add (1 credit = 1 cent)
     */
    credits?: number;
    /**
     * Escrow contract address to use
     */
    escrow_contract?: string;
    user_address?: string;
};

export type HandlersAddCreditsResponse = {
    credits_added?: number;
    /**
     * Escrow contract used for the operation
     */
    escrow_contract?: string;
    message?: string;
    success?: boolean;
    user_address?: string;
};

export type HandlersAppConfig = {
    /**
     * EscrowContract is the escrow contract address for this app
     */
    escrow_contract?: string;
    /**
     * Name is the human-readable name of the app
     */
    name?: string;
};

export type HandlersAppResponse = {
    app_balance_usd?: number;
    app_uuid?: string;
    created_at?: string;
    credit_reset_enabled?: boolean;
    default_user_cost_limit_usd?: number;
    developer_account_id?: number;
    escrow_contract?: string;
    /**
     * Indicates if key is set, but doesn't expose it
     */
    has_privy_verification_key?: boolean;
    id?: number;
    is_active?: boolean;
    name?: string;
    privy_app_id?: string;
    updated_at?: string;
};

export type HandlersAppUsageResponse = {
    app_uuid?: string;
    period?: HandlersUsagePeriod;
    timeseries?: Array<HandlersUsageTimeseriesPoint>;
    total_cost_credits?: number;
    total_request_tokens?: number;
    total_requests?: number;
    total_response_tokens?: number;
};

export type HandlersAppUserUsageResponse = {
    pagination?: HandlersPaginationResponse;
    users?: Array<HandlersUserUsageResponse>;
};

export type HandlersBillingHistoryResponse = {
    pagination?: HandlersPaginationResponse;
    payments?: Array<HandlersBillingRecordResponse>;
};

export type HandlersBillingRecordResponse = {
    amount_cents?: number;
    app_uuid?: string;
    created_at?: string;
    credits?: number;
    currency?: string;
    id?: number;
    status?: string;
};

export type HandlersCancelScheduledDowngradeResponse = {
    message?: string;
};

export type HandlersCancelSubscriptionResponse = {
    cancel_at?: number;
    current_period_end?: number;
    message?: string;
};

export type HandlersCheckoutSessionResponse = {
    url?: string;
};

export type HandlersClaimDailyCreditsResponse = {
    /**
     * Credits awarded (1 credit = $0.01)
     */
    credits_awarded?: number;
    message?: string;
    /**
     * ISO8601 timestamp when next claim is available
     */
    next_claim_at?: string;
    success?: boolean;
};

export type HandlersClaimTaskRewardRequest = {
    memories?: Array<string>;
    task_type?: string;
};

export type HandlersClaimTaskRewardResponse = {
    already_claimed?: boolean;
    credits_awarded?: number;
    message?: string;
    success?: boolean;
};

export type HandlersConfigResponse = {
    /**
     * Apps is the list of active apps with their escrow contracts
     */
    apps?: Array<HandlersAppConfig>;
    /**
     * ChainID is the blockchain chain ID
     */
    chain_id?: string;
    /**
     * OperatorAddress is the operator wallet address
     */
    operator_address?: string;
    /**
     * SettlementRecipient is the address that receives settlement payments
     */
    settlement_recipient?: string;
};

export type HandlersConfigurePrivyRequest = {
    privy_app_id?: string;
    privy_verification_key?: string;
};

export type HandlersCreateApiKeyRequest = {
    is_active?: boolean;
    /**
     * If true, generates anuma_test_ prefix; otherwise anuma_live_
     */
    is_test?: boolean;
    name?: string;
    wallet_address?: string;
};

export type HandlersCreateAppRequest = {
    credit_reset_enabled?: boolean;
    escrow_contract?: string;
    is_active?: boolean;
    name?: string;
    privy_app_id?: string;
    privy_verification_key?: string;
};

export type HandlersCreateCheckoutSessionRequest = {
    cancel_url?: string;
    /**
     * "month" or "year"
     */
    interval?: string;
    price_id?: string;
    /**
     * Rewardful referral ID for affiliate tracking
     */
    referral?: string;
    success_url?: string;
    /**
     * "starter" or "pro"
     */
    tier?: string;
};

export type HandlersCreateCreditPackCheckoutRequest = {
    cancel_url?: string;
    credits?: number;
    /**
     * Rewardful referral ID for affiliate tracking
     */
    referral?: string;
    success_url?: string;
};

export type HandlersCreateCustomerPortalRequest = {
    return_url?: string;
};

export type HandlersCreateDeveloperAppRequest = {
    /**
     * allowed CORS origins for API key requests
     */
    allowed_origins?: Array<string>;
    /**
     * "standard" (default) or "pooled_api"
     */
    app_type?: string;
    /**
     * credits per new user (1 credit = $0.01)
     */
    default_user_credits?: number;
    name?: string;
};

export type HandlersCreditBalanceResponse = {
    /**
     * Available credits (1 credit = $0.01)
     */
    available_credits?: number;
    can_claim_daily?: boolean;
    /**
     * Which import providers have been claimed
     */
    claimed_import_rewards?: Array<string>;
    /**
     * Whether enrolled on-chain
     */
    is_enrolled?: boolean;
    last_claim_at?: string;
    /**
     * Total credits ever received (1 credit = $0.01)
     */
    lifetime_credits?: number;
    next_claim_at?: string;
    /**
     * "basic" or "pro"
     */
    subscription_tier?: string;
    wallet_address?: string;
};

export type HandlersCreditPack = {
    bonus_percent?: number;
    credits?: number;
    currency?: string;
    pro_credits?: number;
    unit_amount?: number;
};

export type HandlersCreditPacksResponse = {
    packs?: Array<HandlersCreditPack>;
};

export type HandlersCustomerPortalResponse = {
    url?: string;
};

export type HandlersDeveloperApiKeyRequest = {
    is_test?: boolean;
    name?: string;
};

export type HandlersDeveloperApiKeyResponse = {
    created_at?: string;
    id?: number;
    is_active?: boolean;
    name?: string;
};

export type HandlersDeveloperApiKeyWithSecretResponse = {
    /**
     * Full key, only shown once
     */
    api_key?: string;
    created_at?: string;
    id?: number;
    is_active?: boolean;
    name?: string;
};

export type HandlersDeveloperAppResponse = {
    /**
     * allowed CORS origins (empty = unrestricted)
     */
    allowed_origins?: Array<string>;
    /**
     * "standard" or "pooled_api"
     */
    app_type?: string;
    app_uuid?: string;
    /**
     * available credits in app pool
     */
    balance?: number;
    created_at?: string;
    /**
     * credits per new user (1 credit = $0.01)
     */
    default_user_credits?: number;
    /**
     * on-chain escrow contract address
     */
    escrow_contract?: string;
    has_privy_config?: boolean;
    is_active?: boolean;
    name?: string;
    updated_at?: string;
};

export type HandlersDeveloperUserResponse = {
    address?: string;
    created_at?: string;
    /**
     * available credits (1 credit = $0.01)
     */
    credits?: number;
    /**
     * on-chain enrollment status
     */
    is_enrolled_onchain?: boolean;
    /**
     * total credits ever received
     */
    lifetime_credits?: number;
    /**
     * basic/pro
     */
    subscription_tier?: string;
    /**
     * credits used/pending
     */
    used_credits?: number;
};

export type HandlersExchangeRequest = {
    code: string;
    /**
     * Optional - uses config default if not provided
     */
    redirect_uri?: string;
};

export type HandlersFundDeveloperAppRequest = {
    /**
     * URL to redirect if payment is cancelled
     */
    cancel_url?: string;
    /**
     * Number of credits to purchase (1 credit = $0.01)
     */
    credits?: number;
    /**
     * Rewardful referral ID for affiliate tracking
     */
    referral?: string;
    /**
     * URL to redirect after successful payment
     */
    success_url?: string;
};

export type HandlersGeneratedApiKey = {
    /**
     * Full HMAC key (anuma_live_<key_id>.<secret> or anuma_test_<key_id>.<secret>)
     */
    api_key?: string;
    name?: string;
};

export type HandlersGetToolsResponse = {
    checksum?: string;
    tools?: {
        [key: string]: HandlersTool;
    };
};

export type HandlersHealthResponse = {
    /**
     * Status indicates the service health status
     */
    status?: string;
    /**
     * Timestamp is the Unix timestamp of the response
     */
    timestamp?: number;
    /**
     * Version is the current API version
     */
    version?: string;
};

export type HandlersListApiKeysResponse = {
    api_keys?: Array<HandlersApiKeyResponse>;
    pagination?: HandlersPaginationResponse;
};

export type HandlersListAppsResponse = {
    apps?: Array<HandlersAppResponse>;
    pagination?: HandlersPaginationResponse;
};

export type HandlersListDeveloperApiKeysResponse = {
    api_keys?: Array<HandlersDeveloperApiKeyResponse>;
    pagination?: HandlersPaginationResponse;
};

export type HandlersListDeveloperAppsResponse = {
    apps?: Array<HandlersDeveloperAppResponse>;
    pagination?: HandlersPaginationResponse;
};

export type HandlersListUsersResponse = {
    pagination?: HandlersPaginationResponse;
    users?: Array<HandlersDeveloperUserResponse>;
};

export type HandlersModelToolUsageItem = {
    call_count?: number;
    cost_usd?: number;
    model?: string;
    tools?: Array<HandlersToolCallDetailItem>;
};

export type HandlersModelUsageItem = {
    cost_usd?: number;
    model?: string;
    request_count?: number;
    request_tokens?: number;
    response_tokens?: number;
};

export type HandlersPaginationResponse = {
    limit?: number;
    offset?: number;
    total?: number;
};

export type HandlersRefreshRequest = {
    refresh_token: string;
};

export type HandlersRenewSubscriptionResponse = {
    current_period_end?: number;
    message?: string;
};

export type HandlersRevokeRequest = {
    token: string;
};

export type HandlersScheduleDowngradeRequest = {
    /**
     * "month" or "year"; defaults to current interval
     */
    interval?: string;
    /**
     * target tier, e.g. "starter"
     */
    tier?: string;
};

export type HandlersScheduleDowngradeResponse = {
    current_period_end?: number;
    message?: string;
    /**
     * "month" or "year"
     */
    scheduled_interval?: string;
    scheduled_plan?: string;
};

export type HandlersSeedApiKeyInput = {
    is_active?: boolean;
    /**
     * If true, generates anuma_test_ prefix; otherwise anuma_live_
     */
    is_test?: boolean;
    name?: string;
    wallet_address?: string;
};

export type HandlersSeedAppInput = {
    api_keys?: Array<HandlersSeedApiKeyInput>;
    /**
     * Developer app balance in micro-USD
     */
    app_balance_usd?: number;
    credit_reset_enabled?: boolean;
    /**
     * Default credits for auto-enrollment in micro-USD
     */
    default_user_cost_limit_usd?: number;
    /**
     * Developer account ID (makes app developer-owned)
     */
    developer_account_id?: number;
    /**
     * Developer wallet (auto-creates account if not exists)
     */
    developer_wallet_address?: string;
    escrow_contract?: string;
    is_active?: boolean;
    name?: string;
    privy_app_id?: string;
    privy_verification_key?: string;
};

export type HandlersSeedAppsRequest = {
    apps?: Array<HandlersSeedAppInput>;
};

export type HandlersSeedAppsResponse = {
    apps_seeded?: number;
    /**
     * Map of app name to generated keys
     */
    generated_keys?: {
        [key: string]: Array<HandlersGeneratedApiKey>;
    };
    keys_seeded?: number;
    message?: string;
    success?: boolean;
};

export type HandlersSetSubscriptionTierRequest = {
    /**
     * Required to identify which app enrollment to update
     */
    escrow_contract?: string;
    /**
     * "basic" or "pro"
     */
    tier?: string;
    user_address?: string;
};

export type HandlersSetSubscriptionTierResponse = {
    message?: string;
    success?: boolean;
    tier?: string;
    user_address?: string;
};

export type HandlersSubscriptionPlan = {
    annual_credits?: number;
    annual_price?: number;
    currency?: string;
    monthly_credits?: number;
    monthly_price?: number;
    tier?: string;
};

export type HandlersSubscriptionPlansResponse = {
    plans?: Array<HandlersSubscriptionPlan>;
};

export type HandlersSubscriptionStatusResponse = {
    /**
     * true if scheduled to cancel
     */
    cancel_at_period_end?: boolean;
    /**
     * Unix timestamp, only present if subscribed
     */
    current_period_end?: number;
    /**
     * "month" | "year", only present if subscribed
     */
    interval?: string;
    /**
     * "free" | "starter" | "pro"
     */
    plan?: string;
    /**
     * billing interval of the scheduled plan
     */
    scheduled_interval?: string;
    /**
     * tier user will switch to at period end
     */
    scheduled_plan?: string;
    /**
     * "none" | "active" | "canceling" | "past_due" | "canceled"
     */
    status?: string;
};

export type HandlersSyncSnagResponse = {
    credits_awarded?: number;
    message?: string;
    next_sync_at?: string;
    success?: boolean;
    total_converted?: number;
};

export type HandlersTaskResponse = {
    /**
     * 1 credit = $0.01
     */
    amount_credits?: number;
    /**
     * null for one-time tasks
     */
    cooldown_secs?: number;
    description?: string;
    type?: string;
};

export type HandlersTokenResponse = {
    access_token?: string;
    /**
     * Seconds until expiration
     */
    expires_in?: number;
    /**
     * May not be present on refresh
     */
    refresh_token?: string;
    /**
     * Granted scopes
     */
    scope?: string;
    /**
     * Usually "Bearer"
     */
    token_type?: string;
};

export type HandlersTool = {
    cost?: number;
    embedding?: Array<number>;
    name?: string;
    schema?: McpToolSchema;
};

export type HandlersToolCallDetailItem = {
    call_count?: number;
    cost_usd?: number;
    tool?: string;
};

export type HandlersTopUpUserRequest = {
    /**
     * credits to add (1 credit = $0.01)
     */
    credits?: number;
};

export type HandlersUpdateApiKeyRequest = {
    app_id?: number;
    is_active?: boolean;
    name?: string;
    wallet_address?: string;
};

export type HandlersUpdateAppRequest = {
    app_balance_usd?: number;
    credit_reset_enabled?: boolean;
    default_user_cost_limit_usd?: number;
    escrow_contract?: string;
    is_active?: boolean;
    name?: string;
    privy_app_id?: string;
    privy_verification_key?: string;
};

export type HandlersUpdateDeveloperAppRequest = {
    /**
     * nil=skip, []=clear, populated=set
     */
    allowed_origins?: Array<string>;
    /**
     * credits per new user (1 credit = $0.01)
     */
    default_user_credits?: number;
    name?: string;
};

export type HandlersUpdateUserLimitRequest = {
    /**
     * credit limit (1 credit = $0.01)
     */
    credits?: number;
};

export type HandlersUpgradeSubscriptionRequest = {
    /**
     * Optional: "month" or "year" (defaults to current)
     */
    interval?: string;
    /**
     * Required: "starter" or "pro"
     */
    tier?: string;
};

export type HandlersUpgradeSubscriptionResponse = {
    message?: string;
    new_interval?: string;
    new_plan?: string;
};

export type HandlersUsageByModelResponse = {
    models?: Array<HandlersModelUsageItem>;
    period?: HandlersUsagePeriod;
    tool_usage?: Array<HandlersModelToolUsageItem>;
    totals?: HandlersUsageTotals;
};

export type HandlersUsagePeriod = {
    end?: string;
    start?: string;
};

export type HandlersUsageTimeseriesPoint = {
    cost_credits?: number;
    request_count?: number;
    request_tokens?: number;
    response_tokens?: number;
    timestamp?: string;
};

export type HandlersUsageTotals = {
    cost_usd?: number;
    request_count?: number;
    tool_call_count?: number;
    tool_cost_usd?: number;
    total_tokens?: number;
};

export type HandlersUserUsageResponse = {
    address?: string;
    cost_credits?: number;
    /**
     * available credits (remaining balance)
     */
    credits?: number;
    request_count?: number;
    request_tokens?: number;
    response_tokens?: number;
    /**
     * credits pending/in-flight
     */
    used_credits?: number;
};

/**
 * Wallet account details
 */
export type HandlersWalletDetails = {
    /**
     * When account was first created
     */
    account_created_at?: string;
    account_id?: number;
    /**
     * When balance was last synced from chain
     */
    balance_updated_at?: string;
    /**
     * Balance in micro-dollars (USD * 1,000,000)
     */
    cached_balance_usd?: number;
    /**
     * App ID for enrollment (0 if not enrolled)
     */
    enrolled_app_id?: number;
    /**
     * Whether enrolled in cost-limit model
     */
    is_enrolled?: boolean;
    /**
     * In-flight request holds in micro-dollars
     */
    pending_cost_usd?: number;
    /**
     * When user became Pro subscriber
     */
    pro_activated_at?: string;
    /**
     * "basic" or "pro"
     */
    subscription_tier?: string;
};

/**
 * ExtraFields contains additional metadata
 */
export type LlmapiChatCompletionExtraFields = {
    /**
     * Latency is the request latency in milliseconds
     */
    latency?: number;
    /**
     * ModelRequested is the model that was requested
     */
    model_requested?: string;
    /**
     * Provider is the LLM provider used (e.g., "openai", "anthropic")
     */
    provider?: string;
    /**
     * RequestType is always "chat_completion"
     */
    request_type?: string;
};

export type LlmapiChatCompletionRequest = {
    /**
     * ImageModel is the user-selected image generation model.
     * When set, the portal overrides the model field in image tool call arguments.
     */
    image_model?: string;
    /**
     * Messages is the conversation history
     */
    messages: Array<LlmapiMessage>;
    /**
     * Model is the model identifier
     */
    model: string;
    /**
     * Stream indicates if response should be streamed
     */
    stream?: boolean;
    tool_choice?: LlmapiChatCompletionToolChoice;
    /**
     * Tools is an array of tool schemas describing which tools the model can use
     */
    tools?: Array<LlmapiChatCompletionTool>;
};

export type LlmapiChatCompletionResponse = {
    /**
     * Choices contains the completion choices
     */
    choices?: Array<LlmapiChoice>;
    /**
     * ClientInjectedTools are tool names the client provided in the original request.
     */
    client_injected_tools?: Array<string>;
    extra_fields?: LlmapiChatCompletionExtraFields;
    /**
     * ID is the completion ID
     */
    id?: string;
    /**
     * InferenceID is the unique identifier for this inference request
     */
    inference_id?: string;
    /**
     * Messages contains the full conversation history when local tools need execution.
     * This is populated when the model requests tools that are not MCP tools (local/client-side tools).
     * The client should execute these tools and send a new request with this message history
     * plus the tool results appended.
     */
    messages?: Array<LlmapiMessage>;
    /**
     * Model is the model used
     */
    model?: string;
    /**
     * PortalInjectedTools are tool names the portal's classifier added to the request.
     */
    portal_injected_tools?: Array<string>;
    /**
     * ToolCallEvents is an array of tool call events.
     */
    tool_call_events?: Array<LlmapiToolCallEvent>;
    /**
     * ToolsChecksum is the checksum of the tool schemas used by the AI Portal.
     */
    tools_checksum?: string;
    usage?: LlmapiChatCompletionUsage;
};

export type LlmapiChatCompletionTool = {
    [key: string]: unknown;
};

/**
 * ToolChoice controls tool usage
 */
export type LlmapiChatCompletionToolChoice = {
    [key: string]: unknown;
};

/**
 * Usage contains token usage information
 */
export type LlmapiChatCompletionUsage = {
    /**
     * CompletionTokens is the number of tokens in the completion
     */
    completion_tokens?: number;
    /**
     * CostMicroUSD is the cost of this completion in micro-dollars (USD × 1,000,000)
     */
    cost_micro_usd?: number;
    /**
     * CreditsUsed is the number of credits consumed by this completion (ceiling of cost / MicroUSDPerCredit)
     */
    credits_used?: number;
    /**
     * PromptTokens is the number of tokens in the prompt
     */
    prompt_tokens?: number;
    /**
     * ToolCostMicroUSD is the cost of MCP tool calls in micro-dollars (subset of CostMicroUSD)
     */
    tool_cost_micro_usd?: number;
    /**
     * TotalTokens is the total number of tokens used
     */
    total_tokens?: number;
};

export type LlmapiChoice = {
    /**
     * FinishReason indicates why the completion stopped
     */
    finish_reason?: string;
    /**
     * Index is the choice index
     */
    index?: number;
    message?: LlmapiMessage;
};

export type LlmapiEmbeddingData = {
    /**
     * Embedding vector
     */
    embedding?: Array<number>;
    /**
     * Index of the embedding
     */
    index?: number;
    /**
     * Object type identifier
     */
    object?: string;
};

/**
 * ExtraFields contains additional metadata
 */
export type LlmapiEmbeddingExtraFields = {
    /**
     * ChunkIndex is the chunk index (0 for single requests)
     */
    chunk_index?: number;
    /**
     * Latency is the request latency in milliseconds
     */
    latency?: number;
    /**
     * ModelRequested is the model that was requested
     */
    model_requested?: string;
    /**
     * Provider is the LLM provider used (e.g., "openai", "anthropic")
     */
    provider?: string;
    /**
     * RequestType is always "embedding"
     */
    request_type?: string;
};

export type LlmapiEmbeddingRequest = {
    /**
     * Dimensions is the number of dimensions the resulting output embeddings should have (optional)
     */
    dimensions?: number;
    /**
     * EncodingFormat is the format to return the embeddings in (optional: "float" or "base64")
     */
    encoding_format?: string;
    /**
     * Input text or tokens to embed (can be string, []string, []int, or [][]int)
     */
    input: unknown;
    /**
     * Model identifier in 'provider/model' format
     */
    model: string;
};

export type LlmapiEmbeddingResponse = {
    /**
     * Data contains the embeddings
     */
    data?: Array<LlmapiEmbeddingData>;
    extra_fields?: LlmapiEmbeddingExtraFields;
    /**
     * InferenceID is the unique identifier for this inference request
     */
    inference_id?: string;
    /**
     * Model is the model used
     */
    model?: string;
    /**
     * Object is always "list"
     */
    object?: string;
    usage?: LlmapiEmbeddingUsage;
};

/**
 * Usage contains token usage information
 */
export type LlmapiEmbeddingUsage = {
    /**
     * CostMicroUSD is the inference cost for this embedding request
     */
    cost_micro_usd?: number;
    /**
     * CreditsUsed is the number of credits consumed by this embedding request
     */
    credits_used?: number;
    /**
     * PromptTokens is the number of tokens in the prompt
     */
    prompt_tokens?: number;
    /**
     * TotalTokens is the total number of tokens used
     */
    total_tokens?: number;
};

export type LlmapiMcpTool = {
    /**
     * Description is the description of the tool
     */
    description?: string;
    /**
     * InputSchema is the JSON schema describing the tool's input
     */
    input_schema?: unknown;
    /**
     * Name is the name of the tool
     */
    name?: string;
};

/**
 * Message is the generated message
 */
export type LlmapiMessage = {
    /**
     * Content is the message content
     */
    content?: Array<LlmapiMessageContentPart>;
    role?: LlmapiRole;
    /**
     * ToolCallID is the ID of the tool call this message is responding to (only for tool role)
     */
    tool_call_id?: string;
    /**
     * ToolCalls contains tool/function calls made by the assistant (only for assistant role)
     */
    tool_calls?: Array<LlmapiToolCall>;
    /**
     * Type is the message type (for Responses API: "message")
     */
    type?: string;
};

/**
 * File is used when Type=input_file (for Responses API)
 */
export type LlmapiMessageContentFile = {
    /**
     * FileData is the base64-encoded file content
     */
    file_data?: string;
    /**
     * FileID is the ID of an uploaded file
     */
    file_id?: string;
    /**
     * FileURL is the URL to the file
     */
    file_url?: string;
    /**
     * Filename is the name of the file
     */
    filename?: string;
};

/**
 * ImageURL is used when Type=image_url or Type=input_image
 */
export type LlmapiMessageContentImage = {
    /**
     * Detail is the OpenAI detail hint (auto|low|high)
     */
    detail?: string;
    /**
     * URL is the image URL or data URI
     */
    url?: string;
};

export type LlmapiMessageContentPart = {
    file?: LlmapiMessageContentFile;
    image_url?: LlmapiMessageContentImage;
    /**
     * Text holds the text content when Type=text or Type=input_text
     */
    text?: string;
    /**
     * Type is the block type (`text`, `image_url`, or `input_file`)
     */
    type?: string;
};

export type LlmapiModel = {
    architecture?: LlmapiModelArchitecture;
    /**
     * CanonicalSlug is the canonical slug for the model
     */
    canonical_slug?: string;
    /**
     * ContextLength is the maximum context length in tokens
     */
    context_length?: number;
    /**
     * Created is the Unix timestamp of when the model was created
     */
    created?: number;
    /**
     * DefaultParameters contains default parameter values
     */
    default_parameters?: {
        [key: string]: unknown;
    };
    /**
     * Description describes the model and its capabilities
     */
    description?: string;
    /**
     * HuggingFaceID is the Hugging Face model identifier
     */
    hugging_face_id?: string;
    /**
     * ID is the model identifier (e.g., "openai/gpt-4")
     */
    id?: string;
    /**
     * MaxInputTokens is the maximum input tokens
     */
    max_input_tokens?: number;
    /**
     * MaxOutputTokens is the maximum output tokens
     */
    max_output_tokens?: number;
    /**
     * Modalities is a list of supported modalities (e.g., ["llm", "vision"])
     */
    modalities?: Array<string>;
    /**
     * Name is the human-readable model name (optional)
     */
    name?: string;
    /**
     * OwnedBy is the organization that owns the model
     */
    owned_by?: string;
    per_request_limits?: LlmapiModelPerRequestLimits;
    pricing?: LlmapiModelPricing;
    /**
     * SupportedMethods is a list of supported API methods
     */
    supported_methods?: Array<string>;
    /**
     * SupportedParameters is a list of supported parameter names
     */
    supported_parameters?: Array<string>;
    top_provider?: LlmapiModelTopProvider;
};

/**
 * Architecture describes the model's technical capabilities
 */
export type LlmapiModelArchitecture = {
    instruct_type?: string;
    modality?: string;
    prompt_formatting?: string;
    tokenizer?: string;
};

/**
 * PerRequestLimits contains rate limiting information
 */
export type LlmapiModelPerRequestLimits = {
    completion_tokens?: number;
    prompt_tokens?: number;
};

/**
 * Pricing contains the pricing structure for using this model
 */
export type LlmapiModelPricing = {
    completion?: string;
    image?: string;
    prompt?: string;
    request?: string;
};

/**
 * TopProvider contains configuration details for the primary provider
 */
export type LlmapiModelTopProvider = {
    context_length?: number;
    is_moderated?: boolean;
    max_completion_tokens?: number;
};

/**
 * ExtraFields contains additional metadata
 */
export type LlmapiModelsListExtraFields = {
    /**
     * ChunkIndex is the chunk index (0 for single requests)
     */
    chunk_index?: number;
    /**
     * Latency is the request latency in milliseconds
     */
    latency?: number;
    /**
     * RequestType is always "list_models"
     */
    request_type?: string;
};

export type LlmapiModelsListResponse = {
    /**
     * Data contains the list of available models
     */
    data?: Array<LlmapiModel>;
    extra_fields?: LlmapiModelsListExtraFields;
    /**
     * NextPageToken is the token to retrieve the next page of results (omitted if no more pages)
     */
    next_page_token?: string;
};

/**
 * ExtraFields contains additional metadata
 */
export type LlmapiResponseExtraFields = {
    /**
     * Latency is the request latency in milliseconds
     */
    latency?: number;
    /**
     * ModelRequested is the model that was requested
     */
    model_requested?: string;
    /**
     * Provider is the LLM provider used (e.g., "openai", "anthropic")
     */
    provider?: string;
    /**
     * RequestType is always "responses"
     */
    request_type?: string;
};

/**
 * Input can be a simple text string or an array of messages for multi-turn conversations.
 * When continuing after client tool calls, pass the messages array from the previous response.
 */
export type LlmapiResponseInput = {
    /**
     * Messages is set when input is an array of messages (for multi-turn/tool continuations)
     */
    messages?: Array<LlmapiMessage>;
    /**
     * Text is set when input is a simple string
     */
    text?: string;
};

export type LlmapiResponseOutputContent = {
    /**
     * Text is the text content
     */
    text?: string;
    /**
     * Type is the content type (e.g., "output_text")
     */
    type?: string;
};

export type LlmapiResponseOutputItem = {
    /**
     * Arguments is the function arguments for function_call and mcp_call types
     */
    arguments?: string;
    /**
     * CallID is the call ID for function_call and mcp_call types
     */
    call_id?: string;
    /**
     * Content is the content array for message and reasoning types
     */
    content?: Array<LlmapiResponseOutputContent>;
    /**
     * Error is the MCP error message for mcp_call types
     */
    error?: string;
    /**
     * ID is the unique identifier for this output item
     */
    id?: string;
    /**
     * Name is the function name for function_call and mcp_call types
     */
    name?: string;
    /**
     * Output is the MCP tool output for mcp_call types
     */
    output?: string;
    /**
     * Role is the role for message types (e.g., "assistant")
     */
    role?: string;
    /**
     * ServerLabel is the MCP server label for mcp_call and mcp_list_tools types
     */
    server_label?: string;
    /**
     * Status is the status of this output item (e.g., "completed")
     */
    status?: string;
    /**
     * Summary is the reasoning summary for reasoning types
     */
    summary?: Array<LlmapiResponseOutputContent>;
    /**
     * Tools is the list of available tools for mcp_list_tools types
     */
    tools?: Array<LlmapiMcpTool>;
    /**
     * Type is the output item type (e.g., "message", "function_call", "reasoning", "mcp_call")
     */
    type?: string;
};

/**
 * Reasoning configures reasoning for o-series and other reasoning models
 */
export type LlmapiResponseReasoning = {
    /**
     * Effort controls reasoning effort: "low", "medium", or "high"
     */
    effort?: string;
    /**
     * Summary controls reasoning summary: "auto", "concise", or "detailed"
     */
    summary?: string;
};

export type LlmapiResponseRequest = {
    /**
     * Background indicates if request should be processed in background
     */
    background?: boolean;
    /**
     * ImageModel is the user-selected image generation model.
     * When set, the portal overrides the model field in image tool call arguments.
     */
    image_model?: string;
    input: LlmapiResponseInput;
    /**
     * MaxOutputTokens is the maximum number of tokens to generate
     */
    max_output_tokens?: number;
    /**
     * Model is the model identifier in 'provider/model' format
     */
    model: string;
    reasoning?: LlmapiResponseReasoning;
    /**
     * Stream indicates if response should be streamed
     */
    stream?: boolean;
    /**
     * Temperature controls randomness (0.0 to 2.0)
     */
    temperature?: number;
    thinking?: LlmapiThinkingOptions;
    tool_choice?: LlmapiResponseToolChoice;
    /**
     * Tools is an array of tool schemas describing which tools the model can use
     */
    tools?: Array<LlmapiResponseTool>;
};

export type LlmapiResponseResponse = {
    /**
     * ClientInjectedTools are tool names the client provided in the original request.
     */
    client_injected_tools?: Array<string>;
    /**
     * Created is the Unix timestamp of creation (created_at in OpenAI format)
     */
    created_at?: number;
    extra_fields?: LlmapiResponseExtraFields;
    /**
     * ID is the unique response identifier
     */
    id?: string;
    /**
     * Messages contains the full conversation history when local tools need execution.
     * This is populated when the model requests tools that are not MCP tools (local/client-side tools).
     * The client should execute these tools and send a new request with this message history
     * plus the tool results appended.
     */
    messages?: Array<LlmapiMessage>;
    /**
     * Model is the model used for generation
     */
    model?: string;
    /**
     * Object is the response type (e.g., "response")
     */
    object?: string;
    /**
     * Output is the array of output items (OpenAI Responses API format)
     */
    output?: Array<LlmapiResponseOutputItem>;
    /**
     * PortalInjectedTools are tool names the portal's classifier added to the request.
     */
    portal_injected_tools?: Array<string>;
    /**
     * ToolCallEvents is an array of tool call events.
     */
    tool_call_events?: Array<LlmapiToolCallEvent>;
    /**
     * ToolsChecksum is the checksum of the tool schemas used by the AI Portal.
     */
    tools_checksum?: string;
    usage?: LlmapiResponseUsage;
};

export type LlmapiResponseTool = {
    [key: string]: unknown;
};

/**
 * ToolChoice controls tool usage
 */
export type LlmapiResponseToolChoice = {
    [key: string]: unknown;
};

/**
 * Usage contains token usage information
 */
export type LlmapiResponseUsage = {
    /**
     * CompletionTokens is the number of tokens in the completion
     */
    completion_tokens?: number;
    /**
     * CostMicroUSD is the cost of this response in micro-dollars (USD × 1,000,000)
     */
    cost_micro_usd?: number;
    /**
     * CreditsUsed is the number of credits consumed by this response
     */
    credits_used?: number;
    /**
     * PromptTokens is the number of tokens in the prompt
     */
    prompt_tokens?: number;
    /**
     * ToolCostMicroUSD is the cost of MCP tool calls in micro-dollars (subset of CostMicroUSD)
     */
    tool_cost_micro_usd?: number;
    /**
     * TotalTokens is the total number of tokens used
     */
    total_tokens?: number;
};

/**
 * Role is the message role (system, user, assistant, tool)
 */
export type LlmapiRole = string;

/**
 * Thinking configures extended thinking for Anthropic models
 */
export type LlmapiThinkingOptions = {
    /**
     * BudgetTokens is the token budget for thinking
     */
    budget_tokens?: number;
    /**
     * Type indicates if thinking is enabled: "enabled" or "disabled"
     */
    type?: string;
};

export type LlmapiToolCall = {
    function?: LlmapiToolCallFunction;
    /**
     * ID is the unique identifier for this tool call
     */
    id?: string;
    /**
     * Type is the type of tool call (always "function" for now)
     */
    type?: string;
};

export type LlmapiToolCallEvent = {
    arguments?: string;
    cost_micro_usd?: number;
    id?: string;
    name?: string;
    output?: string;
};

/**
 * Function contains the function call details
 */
export type LlmapiToolCallFunction = {
    /**
     * Arguments is the JSON string of arguments to pass to the function
     */
    arguments?: string;
    /**
     * Name is the name of the function to call
     */
    name?: string;
};

export type McpToolSchema = {
    description?: string;
    name?: string;
    parameters?: unknown;
};

export type ResponseErrorResponse = {
    code?: string;
    error?: string;
    request_id?: string;
    trace_id?: string;
    type?: string;
};

export type PostApiV1AdminAddCreditsData = {
    /**
     * Add credits request
     */
    body: HandlersAddCreditsRequest;
    headers: {
        /**
         * Admin API key
         */
        'X-Admin-API-Key': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/admin/add-credits';
};

export type PostApiV1AdminAddCreditsErrors = {
    /**
     * Bad Request
     */
    400: ResponseErrorResponse;
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Not Found
     */
    404: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type PostApiV1AdminAddCreditsError = PostApiV1AdminAddCreditsErrors[keyof PostApiV1AdminAddCreditsErrors];

export type PostApiV1AdminAddCreditsResponses = {
    /**
     * OK
     */
    200: HandlersAddCreditsResponse;
};

export type PostApiV1AdminAddCreditsResponse = PostApiV1AdminAddCreditsResponses[keyof PostApiV1AdminAddCreditsResponses];

export type GetApiV1AdminAppsData = {
    body?: never;
    headers: {
        /**
         * Admin API key
         */
        'X-Admin-API-Key': string;
    };
    path?: never;
    query?: {
        /**
         * Maximum number of apps to return (default 50, max 100)
         */
        limit?: number;
        /**
         * Number of apps to skip (default 0)
         */
        offset?: number;
    };
    url: '/api/v1/admin/apps';
};

export type GetApiV1AdminAppsErrors = {
    /**
     * Bad Request
     */
    400: ResponseErrorResponse;
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type GetApiV1AdminAppsError = GetApiV1AdminAppsErrors[keyof GetApiV1AdminAppsErrors];

export type GetApiV1AdminAppsResponses = {
    /**
     * OK
     */
    200: HandlersListAppsResponse;
};

export type GetApiV1AdminAppsResponse = GetApiV1AdminAppsResponses[keyof GetApiV1AdminAppsResponses];

export type PostApiV1AdminAppsData = {
    /**
     * Create app request
     */
    body: HandlersCreateAppRequest;
    headers: {
        /**
         * Admin API key
         */
        'X-Admin-API-Key': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/admin/apps';
};

export type PostApiV1AdminAppsErrors = {
    /**
     * Bad Request
     */
    400: ResponseErrorResponse;
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type PostApiV1AdminAppsError = PostApiV1AdminAppsErrors[keyof PostApiV1AdminAppsErrors];

export type PostApiV1AdminAppsResponses = {
    /**
     * Created
     */
    201: HandlersAppResponse;
};

export type PostApiV1AdminAppsResponse = PostApiV1AdminAppsResponses[keyof PostApiV1AdminAppsResponses];

export type GetApiV1AdminAppsByAppIdApiKeysData = {
    body?: never;
    headers: {
        /**
         * Admin API key
         */
        'X-Admin-API-Key': string;
    };
    path: {
        /**
         * App ID
         */
        app_id: number;
    };
    query?: {
        /**
         * Maximum number of API keys to return (default 50, max 100)
         */
        limit?: number;
        /**
         * Number of API keys to skip (default 0)
         */
        offset?: number;
    };
    url: '/api/v1/admin/apps/{app_id}/api-keys';
};

export type GetApiV1AdminAppsByAppIdApiKeysErrors = {
    /**
     * Bad Request
     */
    400: ResponseErrorResponse;
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Not Found
     */
    404: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type GetApiV1AdminAppsByAppIdApiKeysError = GetApiV1AdminAppsByAppIdApiKeysErrors[keyof GetApiV1AdminAppsByAppIdApiKeysErrors];

export type GetApiV1AdminAppsByAppIdApiKeysResponses = {
    /**
     * OK
     */
    200: HandlersListApiKeysResponse;
};

export type GetApiV1AdminAppsByAppIdApiKeysResponse = GetApiV1AdminAppsByAppIdApiKeysResponses[keyof GetApiV1AdminAppsByAppIdApiKeysResponses];

export type PostApiV1AdminAppsByAppIdApiKeysData = {
    /**
     * Create API key request
     */
    body: HandlersCreateApiKeyRequest;
    headers: {
        /**
         * Admin API key
         */
        'X-Admin-API-Key': string;
    };
    path: {
        /**
         * App ID
         */
        app_id: number;
    };
    query?: never;
    url: '/api/v1/admin/apps/{app_id}/api-keys';
};

export type PostApiV1AdminAppsByAppIdApiKeysErrors = {
    /**
     * Bad Request
     */
    400: ResponseErrorResponse;
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Not Found
     */
    404: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type PostApiV1AdminAppsByAppIdApiKeysError = PostApiV1AdminAppsByAppIdApiKeysErrors[keyof PostApiV1AdminAppsByAppIdApiKeysErrors];

export type PostApiV1AdminAppsByAppIdApiKeysResponses = {
    /**
     * Created
     */
    201: HandlersApiKeyWithKeyResponse;
};

export type PostApiV1AdminAppsByAppIdApiKeysResponse = PostApiV1AdminAppsByAppIdApiKeysResponses[keyof PostApiV1AdminAppsByAppIdApiKeysResponses];

export type DeleteApiV1AdminAppsByAppIdApiKeysByIdData = {
    body?: never;
    headers: {
        /**
         * Admin API key
         */
        'X-Admin-API-Key': string;
    };
    path: {
        /**
         * App ID
         */
        app_id: number;
        /**
         * API Key ID
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/admin/apps/{app_id}/api-keys/{id}';
};

export type DeleteApiV1AdminAppsByAppIdApiKeysByIdErrors = {
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Not Found
     */
    404: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type DeleteApiV1AdminAppsByAppIdApiKeysByIdError = DeleteApiV1AdminAppsByAppIdApiKeysByIdErrors[keyof DeleteApiV1AdminAppsByAppIdApiKeysByIdErrors];

export type DeleteApiV1AdminAppsByAppIdApiKeysByIdResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type DeleteApiV1AdminAppsByAppIdApiKeysByIdResponse = DeleteApiV1AdminAppsByAppIdApiKeysByIdResponses[keyof DeleteApiV1AdminAppsByAppIdApiKeysByIdResponses];

export type GetApiV1AdminAppsByAppIdApiKeysByIdData = {
    body?: never;
    headers: {
        /**
         * Admin API key
         */
        'X-Admin-API-Key': string;
    };
    path: {
        /**
         * App ID
         */
        app_id: number;
        /**
         * API Key ID
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/admin/apps/{app_id}/api-keys/{id}';
};

export type GetApiV1AdminAppsByAppIdApiKeysByIdErrors = {
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Not Found
     */
    404: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type GetApiV1AdminAppsByAppIdApiKeysByIdError = GetApiV1AdminAppsByAppIdApiKeysByIdErrors[keyof GetApiV1AdminAppsByAppIdApiKeysByIdErrors];

export type GetApiV1AdminAppsByAppIdApiKeysByIdResponses = {
    /**
     * OK
     */
    200: HandlersApiKeyResponse;
};

export type GetApiV1AdminAppsByAppIdApiKeysByIdResponse = GetApiV1AdminAppsByAppIdApiKeysByIdResponses[keyof GetApiV1AdminAppsByAppIdApiKeysByIdResponses];

export type PutApiV1AdminAppsByAppIdApiKeysByIdData = {
    /**
     * Update API key request
     */
    body: HandlersUpdateApiKeyRequest;
    headers: {
        /**
         * Admin API key
         */
        'X-Admin-API-Key': string;
    };
    path: {
        /**
         * App ID
         */
        app_id: number;
        /**
         * API Key ID
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/admin/apps/{app_id}/api-keys/{id}';
};

export type PutApiV1AdminAppsByAppIdApiKeysByIdErrors = {
    /**
     * Bad Request
     */
    400: ResponseErrorResponse;
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Not Found
     */
    404: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type PutApiV1AdminAppsByAppIdApiKeysByIdError = PutApiV1AdminAppsByAppIdApiKeysByIdErrors[keyof PutApiV1AdminAppsByAppIdApiKeysByIdErrors];

export type PutApiV1AdminAppsByAppIdApiKeysByIdResponses = {
    /**
     * OK
     */
    200: HandlersApiKeyResponse;
};

export type PutApiV1AdminAppsByAppIdApiKeysByIdResponse = PutApiV1AdminAppsByAppIdApiKeysByIdResponses[keyof PutApiV1AdminAppsByAppIdApiKeysByIdResponses];

export type DeleteApiV1AdminAppsByIdData = {
    body?: never;
    headers: {
        /**
         * Admin API key
         */
        'X-Admin-API-Key': string;
    };
    path: {
        /**
         * App ID
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/admin/apps/{id}';
};

export type DeleteApiV1AdminAppsByIdErrors = {
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Not Found
     */
    404: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type DeleteApiV1AdminAppsByIdError = DeleteApiV1AdminAppsByIdErrors[keyof DeleteApiV1AdminAppsByIdErrors];

export type DeleteApiV1AdminAppsByIdResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type DeleteApiV1AdminAppsByIdResponse = DeleteApiV1AdminAppsByIdResponses[keyof DeleteApiV1AdminAppsByIdResponses];

export type GetApiV1AdminAppsByIdData = {
    body?: never;
    headers: {
        /**
         * Admin API key
         */
        'X-Admin-API-Key': string;
    };
    path: {
        /**
         * App ID
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/admin/apps/{id}';
};

export type GetApiV1AdminAppsByIdErrors = {
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Not Found
     */
    404: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type GetApiV1AdminAppsByIdError = GetApiV1AdminAppsByIdErrors[keyof GetApiV1AdminAppsByIdErrors];

export type GetApiV1AdminAppsByIdResponses = {
    /**
     * OK
     */
    200: HandlersAppResponse;
};

export type GetApiV1AdminAppsByIdResponse = GetApiV1AdminAppsByIdResponses[keyof GetApiV1AdminAppsByIdResponses];

export type PutApiV1AdminAppsByIdData = {
    /**
     * Update app request
     */
    body: HandlersUpdateAppRequest;
    headers: {
        /**
         * Admin API key
         */
        'X-Admin-API-Key': string;
    };
    path: {
        /**
         * App ID (numeric) or App UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/admin/apps/{id}';
};

export type PutApiV1AdminAppsByIdErrors = {
    /**
     * Bad Request
     */
    400: ResponseErrorResponse;
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Not Found
     */
    404: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type PutApiV1AdminAppsByIdError = PutApiV1AdminAppsByIdErrors[keyof PutApiV1AdminAppsByIdErrors];

export type PutApiV1AdminAppsByIdResponses = {
    /**
     * OK
     */
    200: HandlersAppResponse;
};

export type PutApiV1AdminAppsByIdResponse = PutApiV1AdminAppsByIdResponses[keyof PutApiV1AdminAppsByIdResponses];

export type PostApiV1AdminSeedAppsData = {
    /**
     * Seed apps request
     */
    body: HandlersSeedAppsRequest;
    headers: {
        /**
         * Admin API key
         */
        'X-Admin-API-Key': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/admin/seed-apps';
};

export type PostApiV1AdminSeedAppsErrors = {
    /**
     * Bad Request
     */
    400: ResponseErrorResponse;
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type PostApiV1AdminSeedAppsError = PostApiV1AdminSeedAppsErrors[keyof PostApiV1AdminSeedAppsErrors];

export type PostApiV1AdminSeedAppsResponses = {
    /**
     * OK
     */
    200: HandlersSeedAppsResponse;
};

export type PostApiV1AdminSeedAppsResponse = PostApiV1AdminSeedAppsResponses[keyof PostApiV1AdminSeedAppsResponses];

export type PostApiV1AdminSubscriptionTierData = {
    /**
     * Set subscription tier request
     */
    body: HandlersSetSubscriptionTierRequest;
    headers: {
        /**
         * Admin API key
         */
        'X-Admin-API-Key': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/admin/subscription-tier';
};

export type PostApiV1AdminSubscriptionTierErrors = {
    /**
     * Bad Request
     */
    400: ResponseErrorResponse;
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Not Found
     */
    404: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type PostApiV1AdminSubscriptionTierError = PostApiV1AdminSubscriptionTierErrors[keyof PostApiV1AdminSubscriptionTierErrors];

export type PostApiV1AdminSubscriptionTierResponses = {
    /**
     * OK
     */
    200: HandlersSetSubscriptionTierResponse;
};

export type PostApiV1AdminSubscriptionTierResponse = PostApiV1AdminSubscriptionTierResponses[keyof PostApiV1AdminSubscriptionTierResponses];

export type PostApiV1ChatCompletionsData = {
    /**
     * Chat completion request
     */
    body: LlmapiChatCompletionRequest;
    path?: never;
    query?: never;
    url: '/api/v1/chat/completions';
};

export type PostApiV1ChatCompletionsErrors = {
    /**
     * Bad Request
     */
    400: ResponseErrorResponse;
    /**
     * Model provider rate limit exceeded
     */
    429: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type PostApiV1ChatCompletionsError = PostApiV1ChatCompletionsErrors[keyof PostApiV1ChatCompletionsErrors];

export type PostApiV1ChatCompletionsResponses = {
    /**
     * OK
     */
    200: LlmapiChatCompletionResponse | string;
};

export type PostApiV1ChatCompletionsResponse = PostApiV1ChatCompletionsResponses[keyof PostApiV1ChatCompletionsResponses];

export type GetApiV1ConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/config';
};

export type GetApiV1ConfigErrors = {
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type GetApiV1ConfigError = GetApiV1ConfigErrors[keyof GetApiV1ConfigErrors];

export type GetApiV1ConfigResponses = {
    /**
     * OK
     */
    200: HandlersConfigResponse;
};

export type GetApiV1ConfigResponse = GetApiV1ConfigResponses[keyof GetApiV1ConfigResponses];

export type GetApiV1CreditsBalanceData = {
    body?: never;
    headers?: {
        /**
         * IANA timezone (e.g., America/New_York)
         */
        'X-Timezone'?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/credits/balance';
};

export type GetApiV1CreditsBalanceErrors = {
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Balance endpoint not available for this app
     */
    403: ResponseErrorResponse;
    /**
     * Account not found
     */
    404: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type GetApiV1CreditsBalanceError = GetApiV1CreditsBalanceErrors[keyof GetApiV1CreditsBalanceErrors];

export type GetApiV1CreditsBalanceResponses = {
    /**
     * OK
     */
    200: HandlersCreditBalanceResponse;
};

export type GetApiV1CreditsBalanceResponse = GetApiV1CreditsBalanceResponses[keyof GetApiV1CreditsBalanceResponses];

export type PostApiV1CreditsClaimDailyData = {
    body?: never;
    headers?: {
        /**
         * IANA timezone (e.g., America/New_York)
         */
        'X-Timezone'?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/credits/claim-daily';
};

export type PostApiV1CreditsClaimDailyErrors = {
    /**
     * Already claimed today or invalid timezone
     */
    400: ResponseErrorResponse;
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Daily credits not available for this app
     */
    403: ResponseErrorResponse;
    /**
     * Account not found
     */
    404: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type PostApiV1CreditsClaimDailyError = PostApiV1CreditsClaimDailyErrors[keyof PostApiV1CreditsClaimDailyErrors];

export type PostApiV1CreditsClaimDailyResponses = {
    /**
     * OK
     */
    200: HandlersClaimDailyCreditsResponse;
};

export type PostApiV1CreditsClaimDailyResponse = PostApiV1CreditsClaimDailyResponses[keyof PostApiV1CreditsClaimDailyResponses];

export type PostApiV1CreditsClaimTaskData = {
    /**
     * Task to claim
     */
    body: HandlersClaimTaskRewardRequest;
    path?: never;
    query?: never;
    url: '/api/v1/credits/claim-task';
};

export type PostApiV1CreditsClaimTaskErrors = {
    /**
     * Invalid task type or already claimed
     */
    400: ResponseErrorResponse;
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type PostApiV1CreditsClaimTaskError = PostApiV1CreditsClaimTaskErrors[keyof PostApiV1CreditsClaimTaskErrors];

export type PostApiV1CreditsClaimTaskResponses = {
    /**
     * OK
     */
    200: HandlersClaimTaskRewardResponse;
};

export type PostApiV1CreditsClaimTaskResponse = PostApiV1CreditsClaimTaskResponses[keyof PostApiV1CreditsClaimTaskResponses];

export type GetApiV1CreditsPacksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/credits/packs';
};

export type GetApiV1CreditsPacksErrors = {
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type GetApiV1CreditsPacksError = GetApiV1CreditsPacksErrors[keyof GetApiV1CreditsPacksErrors];

export type GetApiV1CreditsPacksResponses = {
    /**
     * OK
     */
    200: HandlersCreditPacksResponse;
};

export type GetApiV1CreditsPacksResponse = GetApiV1CreditsPacksResponses[keyof GetApiV1CreditsPacksResponses];

export type PostApiV1CreditsPurchaseData = {
    /**
     * Credit pack checkout request
     */
    body: HandlersCreateCreditPackCheckoutRequest;
    path?: never;
    query?: never;
    url: '/api/v1/credits/purchase';
};

export type PostApiV1CreditsPurchaseErrors = {
    /**
     * Bad Request
     */
    400: ResponseErrorResponse;
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Forbidden
     */
    403: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type PostApiV1CreditsPurchaseError = PostApiV1CreditsPurchaseErrors[keyof PostApiV1CreditsPurchaseErrors];

export type PostApiV1CreditsPurchaseResponses = {
    /**
     * OK
     */
    200: HandlersCheckoutSessionResponse;
};

export type PostApiV1CreditsPurchaseResponse = PostApiV1CreditsPurchaseResponses[keyof PostApiV1CreditsPurchaseResponses];

export type PostApiV1CreditsSyncSnagData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/credits/sync-snag';
};

export type PostApiV1CreditsSyncSnagErrors = {
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Forbidden
     */
    403: ResponseErrorResponse;
    /**
     * Too Many Requests
     */
    429: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type PostApiV1CreditsSyncSnagError = PostApiV1CreditsSyncSnagErrors[keyof PostApiV1CreditsSyncSnagErrors];

export type PostApiV1CreditsSyncSnagResponses = {
    /**
     * OK
     */
    200: HandlersSyncSnagResponse;
};

export type PostApiV1CreditsSyncSnagResponse = PostApiV1CreditsSyncSnagResponses[keyof PostApiV1CreditsSyncSnagResponses];

export type GetApiV1DeveloperAppsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Maximum number of apps to return (default 50, max 100)
         */
        limit?: number;
        /**
         * Number of apps to skip (default 0)
         */
        offset?: number;
    };
    url: '/api/v1/developer/apps';
};

export type GetApiV1DeveloperAppsErrors = {
    /**
     * Bad Request
     */
    400: ResponseErrorResponse;
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type GetApiV1DeveloperAppsError = GetApiV1DeveloperAppsErrors[keyof GetApiV1DeveloperAppsErrors];

export type GetApiV1DeveloperAppsResponses = {
    /**
     * OK
     */
    200: HandlersListDeveloperAppsResponse;
};

export type GetApiV1DeveloperAppsResponse = GetApiV1DeveloperAppsResponses[keyof GetApiV1DeveloperAppsResponses];

export type PostApiV1DeveloperAppsData = {
    /**
     * Create app request
     */
    body: HandlersCreateDeveloperAppRequest;
    path?: never;
    query?: never;
    url: '/api/v1/developer/apps';
};

export type PostApiV1DeveloperAppsErrors = {
    /**
     * Bad Request
     */
    400: ResponseErrorResponse;
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type PostApiV1DeveloperAppsError = PostApiV1DeveloperAppsErrors[keyof PostApiV1DeveloperAppsErrors];

export type PostApiV1DeveloperAppsResponses = {
    /**
     * Created
     */
    201: HandlersDeveloperAppResponse;
};

export type PostApiV1DeveloperAppsResponse = PostApiV1DeveloperAppsResponses[keyof PostApiV1DeveloperAppsResponses];

export type DeleteApiV1DeveloperAppsByAppUuidData = {
    body?: never;
    path: {
        /**
         * App UUID
         */
        app_uuid: string;
    };
    query?: never;
    url: '/api/v1/developer/apps/{app_uuid}';
};

export type DeleteApiV1DeveloperAppsByAppUuidErrors = {
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Forbidden
     */
    403: ResponseErrorResponse;
    /**
     * Not Found
     */
    404: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type DeleteApiV1DeveloperAppsByAppUuidError = DeleteApiV1DeveloperAppsByAppUuidErrors[keyof DeleteApiV1DeveloperAppsByAppUuidErrors];

export type DeleteApiV1DeveloperAppsByAppUuidResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type DeleteApiV1DeveloperAppsByAppUuidResponse = DeleteApiV1DeveloperAppsByAppUuidResponses[keyof DeleteApiV1DeveloperAppsByAppUuidResponses];

export type GetApiV1DeveloperAppsByAppUuidData = {
    body?: never;
    path: {
        /**
         * App UUID
         */
        app_uuid: string;
    };
    query?: never;
    url: '/api/v1/developer/apps/{app_uuid}';
};

export type GetApiV1DeveloperAppsByAppUuidErrors = {
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Forbidden
     */
    403: ResponseErrorResponse;
    /**
     * Not Found
     */
    404: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type GetApiV1DeveloperAppsByAppUuidError = GetApiV1DeveloperAppsByAppUuidErrors[keyof GetApiV1DeveloperAppsByAppUuidErrors];

export type GetApiV1DeveloperAppsByAppUuidResponses = {
    /**
     * OK
     */
    200: HandlersDeveloperAppResponse;
};

export type GetApiV1DeveloperAppsByAppUuidResponse = GetApiV1DeveloperAppsByAppUuidResponses[keyof GetApiV1DeveloperAppsByAppUuidResponses];

export type PatchApiV1DeveloperAppsByAppUuidData = {
    /**
     * Update app request
     */
    body: HandlersUpdateDeveloperAppRequest;
    path: {
        /**
         * App UUID
         */
        app_uuid: string;
    };
    query?: never;
    url: '/api/v1/developer/apps/{app_uuid}';
};

export type PatchApiV1DeveloperAppsByAppUuidErrors = {
    /**
     * Bad Request
     */
    400: ResponseErrorResponse;
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Forbidden
     */
    403: ResponseErrorResponse;
    /**
     * Not Found
     */
    404: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type PatchApiV1DeveloperAppsByAppUuidError = PatchApiV1DeveloperAppsByAppUuidErrors[keyof PatchApiV1DeveloperAppsByAppUuidErrors];

export type PatchApiV1DeveloperAppsByAppUuidResponses = {
    /**
     * OK
     */
    200: HandlersDeveloperAppResponse;
};

export type PatchApiV1DeveloperAppsByAppUuidResponse = PatchApiV1DeveloperAppsByAppUuidResponses[keyof PatchApiV1DeveloperAppsByAppUuidResponses];

export type GetApiV1DeveloperAppsByAppUuidApiKeysData = {
    body?: never;
    path: {
        /**
         * App UUID
         */
        app_uuid: string;
    };
    query?: {
        /**
         * Maximum number of API keys to return (default 50, max 100)
         */
        limit?: number;
        /**
         * Number of API keys to skip (default 0)
         */
        offset?: number;
    };
    url: '/api/v1/developer/apps/{app_uuid}/api-keys';
};

export type GetApiV1DeveloperAppsByAppUuidApiKeysErrors = {
    /**
     * Bad Request
     */
    400: ResponseErrorResponse;
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Forbidden
     */
    403: ResponseErrorResponse;
    /**
     * Not Found
     */
    404: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type GetApiV1DeveloperAppsByAppUuidApiKeysError = GetApiV1DeveloperAppsByAppUuidApiKeysErrors[keyof GetApiV1DeveloperAppsByAppUuidApiKeysErrors];

export type GetApiV1DeveloperAppsByAppUuidApiKeysResponses = {
    /**
     * OK
     */
    200: HandlersListDeveloperApiKeysResponse;
};

export type GetApiV1DeveloperAppsByAppUuidApiKeysResponse = GetApiV1DeveloperAppsByAppUuidApiKeysResponses[keyof GetApiV1DeveloperAppsByAppUuidApiKeysResponses];

export type PostApiV1DeveloperAppsByAppUuidApiKeysData = {
    /**
     * API key request
     */
    body: HandlersDeveloperApiKeyRequest;
    path: {
        /**
         * App UUID
         */
        app_uuid: string;
    };
    query?: never;
    url: '/api/v1/developer/apps/{app_uuid}/api-keys';
};

export type PostApiV1DeveloperAppsByAppUuidApiKeysErrors = {
    /**
     * Bad Request
     */
    400: ResponseErrorResponse;
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Forbidden
     */
    403: ResponseErrorResponse;
    /**
     * Not Found
     */
    404: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type PostApiV1DeveloperAppsByAppUuidApiKeysError = PostApiV1DeveloperAppsByAppUuidApiKeysErrors[keyof PostApiV1DeveloperAppsByAppUuidApiKeysErrors];

export type PostApiV1DeveloperAppsByAppUuidApiKeysResponses = {
    /**
     * Created
     */
    201: HandlersDeveloperApiKeyWithSecretResponse;
};

export type PostApiV1DeveloperAppsByAppUuidApiKeysResponse = PostApiV1DeveloperAppsByAppUuidApiKeysResponses[keyof PostApiV1DeveloperAppsByAppUuidApiKeysResponses];

export type DeleteApiV1DeveloperAppsByAppUuidApiKeysByKeyIdData = {
    body?: never;
    path: {
        /**
         * App UUID
         */
        app_uuid: string;
        /**
         * API Key ID
         */
        key_id: number;
    };
    query?: never;
    url: '/api/v1/developer/apps/{app_uuid}/api-keys/{key_id}';
};

export type DeleteApiV1DeveloperAppsByAppUuidApiKeysByKeyIdErrors = {
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Forbidden
     */
    403: ResponseErrorResponse;
    /**
     * Not Found
     */
    404: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type DeleteApiV1DeveloperAppsByAppUuidApiKeysByKeyIdError = DeleteApiV1DeveloperAppsByAppUuidApiKeysByKeyIdErrors[keyof DeleteApiV1DeveloperAppsByAppUuidApiKeysByKeyIdErrors];

export type DeleteApiV1DeveloperAppsByAppUuidApiKeysByKeyIdResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type DeleteApiV1DeveloperAppsByAppUuidApiKeysByKeyIdResponse = DeleteApiV1DeveloperAppsByAppUuidApiKeysByKeyIdResponses[keyof DeleteApiV1DeveloperAppsByAppUuidApiKeysByKeyIdResponses];

export type DeleteApiV1DeveloperAppsByAppUuidPrivyData = {
    body?: never;
    path: {
        /**
         * App UUID
         */
        app_uuid: string;
    };
    query?: never;
    url: '/api/v1/developer/apps/{app_uuid}/privy';
};

export type DeleteApiV1DeveloperAppsByAppUuidPrivyErrors = {
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Forbidden
     */
    403: ResponseErrorResponse;
    /**
     * Not Found
     */
    404: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type DeleteApiV1DeveloperAppsByAppUuidPrivyError = DeleteApiV1DeveloperAppsByAppUuidPrivyErrors[keyof DeleteApiV1DeveloperAppsByAppUuidPrivyErrors];

export type DeleteApiV1DeveloperAppsByAppUuidPrivyResponses = {
    /**
     * OK
     */
    200: HandlersDeveloperAppResponse;
};

export type DeleteApiV1DeveloperAppsByAppUuidPrivyResponse = DeleteApiV1DeveloperAppsByAppUuidPrivyResponses[keyof DeleteApiV1DeveloperAppsByAppUuidPrivyResponses];

export type PostApiV1DeveloperAppsByAppUuidPrivyData = {
    /**
     * Privy configuration
     */
    body: HandlersConfigurePrivyRequest;
    path: {
        /**
         * App UUID
         */
        app_uuid: string;
    };
    query?: never;
    url: '/api/v1/developer/apps/{app_uuid}/privy';
};

export type PostApiV1DeveloperAppsByAppUuidPrivyErrors = {
    /**
     * Bad Request
     */
    400: ResponseErrorResponse;
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Forbidden
     */
    403: ResponseErrorResponse;
    /**
     * Not Found
     */
    404: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type PostApiV1DeveloperAppsByAppUuidPrivyError = PostApiV1DeveloperAppsByAppUuidPrivyErrors[keyof PostApiV1DeveloperAppsByAppUuidPrivyErrors];

export type PostApiV1DeveloperAppsByAppUuidPrivyResponses = {
    /**
     * OK
     */
    200: HandlersDeveloperAppResponse;
};

export type PostApiV1DeveloperAppsByAppUuidPrivyResponse = PostApiV1DeveloperAppsByAppUuidPrivyResponses[keyof PostApiV1DeveloperAppsByAppUuidPrivyResponses];

export type GetApiV1DeveloperAppsByAppUuidUsageData = {
    body?: never;
    path: {
        /**
         * App UUID
         */
        app_uuid: string;
    };
    query?: {
        /**
         * Start time (RFC3339). Defaults to 30 days ago.
         */
        start_time?: string;
        /**
         * End time (RFC3339). Defaults to now.
         */
        end_time?: string;
        /**
         * Timeseries granularity: 'day' (default) or 'hour'
         */
        granularity?: string;
    };
    url: '/api/v1/developer/apps/{app_uuid}/usage';
};

export type GetApiV1DeveloperAppsByAppUuidUsageErrors = {
    /**
     * Bad Request
     */
    400: ResponseErrorResponse;
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Forbidden
     */
    403: ResponseErrorResponse;
    /**
     * Not Found
     */
    404: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type GetApiV1DeveloperAppsByAppUuidUsageError = GetApiV1DeveloperAppsByAppUuidUsageErrors[keyof GetApiV1DeveloperAppsByAppUuidUsageErrors];

export type GetApiV1DeveloperAppsByAppUuidUsageResponses = {
    /**
     * OK
     */
    200: HandlersAppUsageResponse;
};

export type GetApiV1DeveloperAppsByAppUuidUsageResponse = GetApiV1DeveloperAppsByAppUuidUsageResponses[keyof GetApiV1DeveloperAppsByAppUuidUsageResponses];

export type GetApiV1DeveloperAppsByAppUuidUsageUsersData = {
    body?: never;
    path: {
        /**
         * App UUID
         */
        app_uuid: string;
    };
    query?: {
        /**
         * Start time (RFC3339). Defaults to 30 days ago.
         */
        start_time?: string;
        /**
         * End time (RFC3339). Defaults to now.
         */
        end_time?: string;
        /**
         * Number of results (default 50, max 100)
         */
        limit?: number;
        /**
         * Offset for pagination (default 0)
         */
        offset?: number;
    };
    url: '/api/v1/developer/apps/{app_uuid}/usage/users';
};

export type GetApiV1DeveloperAppsByAppUuidUsageUsersErrors = {
    /**
     * Bad Request
     */
    400: ResponseErrorResponse;
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Forbidden
     */
    403: ResponseErrorResponse;
    /**
     * Not Found
     */
    404: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type GetApiV1DeveloperAppsByAppUuidUsageUsersError = GetApiV1DeveloperAppsByAppUuidUsageUsersErrors[keyof GetApiV1DeveloperAppsByAppUuidUsageUsersErrors];

export type GetApiV1DeveloperAppsByAppUuidUsageUsersResponses = {
    /**
     * OK
     */
    200: HandlersAppUserUsageResponse;
};

export type GetApiV1DeveloperAppsByAppUuidUsageUsersResponse = GetApiV1DeveloperAppsByAppUuidUsageUsersResponses[keyof GetApiV1DeveloperAppsByAppUuidUsageUsersResponses];

export type GetApiV1DeveloperAppsByAppUuidUsersData = {
    body?: never;
    path: {
        /**
         * App UUID
         */
        app_uuid: string;
    };
    query?: {
        /**
         * Maximum number of users to return (default 50, max 200)
         */
        limit?: number;
        /**
         * Number of users to skip (default 0)
         */
        offset?: number;
    };
    url: '/api/v1/developer/apps/{app_uuid}/users';
};

export type GetApiV1DeveloperAppsByAppUuidUsersErrors = {
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Forbidden
     */
    403: ResponseErrorResponse;
    /**
     * Not Found
     */
    404: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type GetApiV1DeveloperAppsByAppUuidUsersError = GetApiV1DeveloperAppsByAppUuidUsersErrors[keyof GetApiV1DeveloperAppsByAppUuidUsersErrors];

export type GetApiV1DeveloperAppsByAppUuidUsersResponses = {
    /**
     * OK
     */
    200: HandlersListUsersResponse;
};

export type GetApiV1DeveloperAppsByAppUuidUsersResponse = GetApiV1DeveloperAppsByAppUuidUsersResponses[keyof GetApiV1DeveloperAppsByAppUuidUsersResponses];

export type GetApiV1DeveloperAppsByAppUuidUsersByAddressData = {
    body?: never;
    path: {
        /**
         * App UUID
         */
        app_uuid: string;
        /**
         * User wallet address
         */
        address: string;
    };
    query?: never;
    url: '/api/v1/developer/apps/{app_uuid}/users/{address}';
};

export type GetApiV1DeveloperAppsByAppUuidUsersByAddressErrors = {
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Forbidden
     */
    403: ResponseErrorResponse;
    /**
     * Not Found
     */
    404: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type GetApiV1DeveloperAppsByAppUuidUsersByAddressError = GetApiV1DeveloperAppsByAppUuidUsersByAddressErrors[keyof GetApiV1DeveloperAppsByAppUuidUsersByAddressErrors];

export type GetApiV1DeveloperAppsByAppUuidUsersByAddressResponses = {
    /**
     * OK
     */
    200: HandlersDeveloperUserResponse;
};

export type GetApiV1DeveloperAppsByAppUuidUsersByAddressResponse = GetApiV1DeveloperAppsByAppUuidUsersByAddressResponses[keyof GetApiV1DeveloperAppsByAppUuidUsersByAddressResponses];

export type PatchApiV1DeveloperAppsByAppUuidUsersByAddressData = {
    /**
     * Update limit request
     */
    body: HandlersUpdateUserLimitRequest;
    path: {
        /**
         * App UUID
         */
        app_uuid: string;
        /**
         * User wallet address
         */
        address: string;
    };
    query?: never;
    url: '/api/v1/developer/apps/{app_uuid}/users/{address}';
};

export type PatchApiV1DeveloperAppsByAppUuidUsersByAddressErrors = {
    /**
     * Bad Request
     */
    400: ResponseErrorResponse;
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Forbidden
     */
    403: ResponseErrorResponse;
    /**
     * Not Found
     */
    404: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type PatchApiV1DeveloperAppsByAppUuidUsersByAddressError = PatchApiV1DeveloperAppsByAppUuidUsersByAddressErrors[keyof PatchApiV1DeveloperAppsByAppUuidUsersByAddressErrors];

export type PatchApiV1DeveloperAppsByAppUuidUsersByAddressResponses = {
    /**
     * OK
     */
    200: HandlersDeveloperUserResponse;
};

export type PatchApiV1DeveloperAppsByAppUuidUsersByAddressResponse = PatchApiV1DeveloperAppsByAppUuidUsersByAddressResponses[keyof PatchApiV1DeveloperAppsByAppUuidUsersByAddressResponses];

export type PostApiV1DeveloperAppsByAppUuidUsersByAddressTopUpData = {
    /**
     * Top-up request
     */
    body: HandlersTopUpUserRequest;
    path: {
        /**
         * App UUID
         */
        app_uuid: string;
        /**
         * User wallet address
         */
        address: string;
    };
    query?: never;
    url: '/api/v1/developer/apps/{app_uuid}/users/{address}/top-up';
};

export type PostApiV1DeveloperAppsByAppUuidUsersByAddressTopUpErrors = {
    /**
     * Bad Request
     */
    400: ResponseErrorResponse;
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Forbidden
     */
    403: ResponseErrorResponse;
    /**
     * Not Found
     */
    404: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type PostApiV1DeveloperAppsByAppUuidUsersByAddressTopUpError = PostApiV1DeveloperAppsByAppUuidUsersByAddressTopUpErrors[keyof PostApiV1DeveloperAppsByAppUuidUsersByAddressTopUpErrors];

export type PostApiV1DeveloperAppsByAppUuidUsersByAddressTopUpResponses = {
    /**
     * OK
     */
    200: HandlersDeveloperUserResponse;
};

export type PostApiV1DeveloperAppsByAppUuidUsersByAddressTopUpResponse = PostApiV1DeveloperAppsByAppUuidUsersByAddressTopUpResponses[keyof PostApiV1DeveloperAppsByAppUuidUsersByAddressTopUpResponses];

export type GetApiV1DeveloperBillingData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Maximum number of records to return (default 50, max 100)
         */
        limit?: number;
        /**
         * Number of records to skip (default 0)
         */
        offset?: number;
    };
    url: '/api/v1/developer/billing';
};

export type GetApiV1DeveloperBillingErrors = {
    /**
     * Bad Request
     */
    400: ResponseErrorResponse;
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type GetApiV1DeveloperBillingError = GetApiV1DeveloperBillingErrors[keyof GetApiV1DeveloperBillingErrors];

export type GetApiV1DeveloperBillingResponses = {
    /**
     * OK
     */
    200: HandlersBillingHistoryResponse;
};

export type GetApiV1DeveloperBillingResponse = GetApiV1DeveloperBillingResponses[keyof GetApiV1DeveloperBillingResponses];

export type GetApiV1DocsSwaggerJsonData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/docs/swagger.json';
};

export type GetApiV1DocsSwaggerJsonResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetApiV1DocsSwaggerJsonResponse = GetApiV1DocsSwaggerJsonResponses[keyof GetApiV1DocsSwaggerJsonResponses];

export type PostApiV1EmbeddingsData = {
    /**
     * Embedding request
     */
    body: LlmapiEmbeddingRequest;
    path?: never;
    query?: never;
    url: '/api/v1/embeddings';
};

export type PostApiV1EmbeddingsErrors = {
    /**
     * Bad Request
     */
    400: ResponseErrorResponse;
    /**
     * Model provider rate limit exceeded
     */
    429: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type PostApiV1EmbeddingsError = PostApiV1EmbeddingsErrors[keyof PostApiV1EmbeddingsErrors];

export type PostApiV1EmbeddingsResponses = {
    /**
     * OK
     */
    200: LlmapiEmbeddingResponse;
};

export type PostApiV1EmbeddingsResponse = PostApiV1EmbeddingsResponses[keyof PostApiV1EmbeddingsResponses];

export type GetApiV1ModelsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by provider (e.g., openai, anthropic)
         */
        provider?: string;
        /**
         * Number of models to return per page
         */
        page_size?: number;
        /**
         * Token to get next page of results
         */
        page_token?: string;
    };
    url: '/api/v1/models';
};

export type GetApiV1ModelsErrors = {
    /**
     * Bad Request
     */
    400: ResponseErrorResponse;
    /**
     * Rate limit exceeded
     */
    429: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type GetApiV1ModelsError = GetApiV1ModelsErrors[keyof GetApiV1ModelsErrors];

export type GetApiV1ModelsResponses = {
    /**
     * OK
     */
    200: LlmapiModelsListResponse;
};

export type GetApiV1ModelsResponse = GetApiV1ModelsResponses[keyof GetApiV1ModelsResponses];

export type PostApiV1ResponsesData = {
    /**
     * Response request
     */
    body: LlmapiResponseRequest;
    path?: never;
    query?: never;
    url: '/api/v1/responses';
};

export type PostApiV1ResponsesErrors = {
    /**
     * Bad Request
     */
    400: ResponseErrorResponse;
    /**
     * Model provider rate limit exceeded
     */
    429: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type PostApiV1ResponsesError = PostApiV1ResponsesErrors[keyof PostApiV1ResponsesErrors];

export type PostApiV1ResponsesResponses = {
    /**
     * OK
     */
    200: LlmapiResponseResponse | string;
};

export type PostApiV1ResponsesResponse = PostApiV1ResponsesResponses[keyof PostApiV1ResponsesResponses];

export type PostApiV1SubscriptionsCancelData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/subscriptions/cancel';
};

export type PostApiV1SubscriptionsCancelErrors = {
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Not Found
     */
    404: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type PostApiV1SubscriptionsCancelError = PostApiV1SubscriptionsCancelErrors[keyof PostApiV1SubscriptionsCancelErrors];

export type PostApiV1SubscriptionsCancelResponses = {
    /**
     * OK
     */
    200: HandlersCancelSubscriptionResponse;
};

export type PostApiV1SubscriptionsCancelResponse = PostApiV1SubscriptionsCancelResponses[keyof PostApiV1SubscriptionsCancelResponses];

export type PostApiV1SubscriptionsCancelScheduledDowngradeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/subscriptions/cancel-scheduled-downgrade';
};

export type PostApiV1SubscriptionsCancelScheduledDowngradeErrors = {
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Not Found
     */
    404: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type PostApiV1SubscriptionsCancelScheduledDowngradeError = PostApiV1SubscriptionsCancelScheduledDowngradeErrors[keyof PostApiV1SubscriptionsCancelScheduledDowngradeErrors];

export type PostApiV1SubscriptionsCancelScheduledDowngradeResponses = {
    /**
     * OK
     */
    200: HandlersCancelScheduledDowngradeResponse;
};

export type PostApiV1SubscriptionsCancelScheduledDowngradeResponse = PostApiV1SubscriptionsCancelScheduledDowngradeResponses[keyof PostApiV1SubscriptionsCancelScheduledDowngradeResponses];

export type PostApiV1SubscriptionsCreateCheckoutSessionData = {
    /**
     * Checkout session request with redirect URLs
     */
    body: HandlersCreateCheckoutSessionRequest;
    path?: never;
    query?: never;
    url: '/api/v1/subscriptions/create-checkout-session';
};

export type PostApiV1SubscriptionsCreateCheckoutSessionErrors = {
    /**
     * Bad Request
     */
    400: ResponseErrorResponse;
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Forbidden
     */
    403: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type PostApiV1SubscriptionsCreateCheckoutSessionError = PostApiV1SubscriptionsCreateCheckoutSessionErrors[keyof PostApiV1SubscriptionsCreateCheckoutSessionErrors];

export type PostApiV1SubscriptionsCreateCheckoutSessionResponses = {
    /**
     * OK
     */
    200: HandlersCheckoutSessionResponse;
};

export type PostApiV1SubscriptionsCreateCheckoutSessionResponse = PostApiV1SubscriptionsCreateCheckoutSessionResponses[keyof PostApiV1SubscriptionsCreateCheckoutSessionResponses];

export type PostApiV1SubscriptionsCustomerPortalData = {
    /**
     * Customer portal request with return URL
     */
    body: HandlersCreateCustomerPortalRequest;
    path?: never;
    query?: never;
    url: '/api/v1/subscriptions/customer-portal';
};

export type PostApiV1SubscriptionsCustomerPortalErrors = {
    /**
     * Bad Request
     */
    400: ResponseErrorResponse;
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Not Found
     */
    404: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type PostApiV1SubscriptionsCustomerPortalError = PostApiV1SubscriptionsCustomerPortalErrors[keyof PostApiV1SubscriptionsCustomerPortalErrors];

export type PostApiV1SubscriptionsCustomerPortalResponses = {
    /**
     * OK
     */
    200: HandlersCustomerPortalResponse;
};

export type PostApiV1SubscriptionsCustomerPortalResponse = PostApiV1SubscriptionsCustomerPortalResponses[keyof PostApiV1SubscriptionsCustomerPortalResponses];

export type GetApiV1SubscriptionsPlansData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/subscriptions/plans';
};

export type GetApiV1SubscriptionsPlansErrors = {
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type GetApiV1SubscriptionsPlansError = GetApiV1SubscriptionsPlansErrors[keyof GetApiV1SubscriptionsPlansErrors];

export type GetApiV1SubscriptionsPlansResponses = {
    /**
     * OK
     */
    200: HandlersSubscriptionPlansResponse;
};

export type GetApiV1SubscriptionsPlansResponse = GetApiV1SubscriptionsPlansResponses[keyof GetApiV1SubscriptionsPlansResponses];

export type PostApiV1SubscriptionsRenewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/subscriptions/renew';
};

export type PostApiV1SubscriptionsRenewErrors = {
    /**
     * Bad Request
     */
    400: ResponseErrorResponse;
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Not Found
     */
    404: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type PostApiV1SubscriptionsRenewError = PostApiV1SubscriptionsRenewErrors[keyof PostApiV1SubscriptionsRenewErrors];

export type PostApiV1SubscriptionsRenewResponses = {
    /**
     * OK
     */
    200: HandlersRenewSubscriptionResponse;
};

export type PostApiV1SubscriptionsRenewResponse = PostApiV1SubscriptionsRenewResponses[keyof PostApiV1SubscriptionsRenewResponses];

export type PostApiV1SubscriptionsScheduleDowngradeData = {
    /**
     * Downgrade request with target tier and optional interval
     */
    body: HandlersScheduleDowngradeRequest;
    path?: never;
    query?: never;
    url: '/api/v1/subscriptions/schedule-downgrade';
};

export type PostApiV1SubscriptionsScheduleDowngradeErrors = {
    /**
     * Bad Request
     */
    400: ResponseErrorResponse;
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Not Found
     */
    404: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type PostApiV1SubscriptionsScheduleDowngradeError = PostApiV1SubscriptionsScheduleDowngradeErrors[keyof PostApiV1SubscriptionsScheduleDowngradeErrors];

export type PostApiV1SubscriptionsScheduleDowngradeResponses = {
    /**
     * OK
     */
    200: HandlersScheduleDowngradeResponse;
};

export type PostApiV1SubscriptionsScheduleDowngradeResponse = PostApiV1SubscriptionsScheduleDowngradeResponses[keyof PostApiV1SubscriptionsScheduleDowngradeResponses];

export type GetApiV1SubscriptionsStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/subscriptions/status';
};

export type GetApiV1SubscriptionsStatusErrors = {
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type GetApiV1SubscriptionsStatusError = GetApiV1SubscriptionsStatusErrors[keyof GetApiV1SubscriptionsStatusErrors];

export type GetApiV1SubscriptionsStatusResponses = {
    /**
     * OK
     */
    200: HandlersSubscriptionStatusResponse;
};

export type GetApiV1SubscriptionsStatusResponse = GetApiV1SubscriptionsStatusResponses[keyof GetApiV1SubscriptionsStatusResponses];

export type PostApiV1SubscriptionsUpgradeData = {
    /**
     * Upgrade request with target tier and optional interval
     */
    body: HandlersUpgradeSubscriptionRequest;
    path?: never;
    query?: never;
    url: '/api/v1/subscriptions/upgrade';
};

export type PostApiV1SubscriptionsUpgradeErrors = {
    /**
     * Bad Request
     */
    400: ResponseErrorResponse;
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Forbidden
     */
    403: ResponseErrorResponse;
    /**
     * Not Found
     */
    404: ResponseErrorResponse;
    /**
     * Too Many Requests
     */
    429: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type PostApiV1SubscriptionsUpgradeError = PostApiV1SubscriptionsUpgradeErrors[keyof PostApiV1SubscriptionsUpgradeErrors];

export type PostApiV1SubscriptionsUpgradeResponses = {
    /**
     * OK
     */
    200: HandlersUpgradeSubscriptionResponse;
};

export type PostApiV1SubscriptionsUpgradeResponse = PostApiV1SubscriptionsUpgradeResponses[keyof PostApiV1SubscriptionsUpgradeResponses];

export type PostApiV1SubscriptionsWebhookData = {
    body?: {
        [key: string]: unknown;
    };
    headers: {
        /**
         * Stripe webhook signature
         */
        'Stripe-Signature': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/subscriptions/webhook';
};

export type PostApiV1SubscriptionsWebhookErrors = {
    /**
     * Bad Request
     */
    400: ResponseErrorResponse;
};

export type PostApiV1SubscriptionsWebhookError = PostApiV1SubscriptionsWebhookErrors[keyof PostApiV1SubscriptionsWebhookErrors];

export type PostApiV1SubscriptionsWebhookResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type PostApiV1SubscriptionsWebhookResponse = PostApiV1SubscriptionsWebhookResponses[keyof PostApiV1SubscriptionsWebhookResponses];

export type GetApiV1TasksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tasks';
};

export type GetApiV1TasksErrors = {
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type GetApiV1TasksError = GetApiV1TasksErrors[keyof GetApiV1TasksErrors];

export type GetApiV1TasksResponses = {
    /**
     * OK
     */
    200: Array<HandlersTaskResponse>;
};

export type GetApiV1TasksResponse = GetApiV1TasksResponses[keyof GetApiV1TasksResponses];

export type GetApiV1ToolsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tools';
};

export type GetApiV1ToolsErrors = {
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type GetApiV1ToolsError = GetApiV1ToolsErrors[keyof GetApiV1ToolsErrors];

export type GetApiV1ToolsResponses = {
    /**
     * OK
     */
    200: HandlersGetToolsResponse;
};

export type GetApiV1ToolsResponse = GetApiV1ToolsResponses[keyof GetApiV1ToolsResponses];

export type GetApiV1UsageModelsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Time period. Day aliases: 7d, 30d, 90d. Durations: 10m, 30m, 1h, 6h, 12h, 24h, 72h. Default: 30d. Max: 90d.
         */
        period?: string;
    };
    url: '/api/v1/usage/models';
};

export type GetApiV1UsageModelsErrors = {
    /**
     * Invalid period
     */
    400: ResponseErrorResponse;
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type GetApiV1UsageModelsError = GetApiV1UsageModelsErrors[keyof GetApiV1UsageModelsErrors];

export type GetApiV1UsageModelsResponses = {
    /**
     * OK
     */
    200: HandlersUsageByModelResponse;
};

export type GetApiV1UsageModelsResponse = GetApiV1UsageModelsResponses[keyof GetApiV1UsageModelsResponses];

export type PostAuthOauthByProviderExchangeData = {
    /**
     * Exchange request
     */
    body: HandlersExchangeRequest;
    path: {
        /**
         * OAuth provider (google-drive, dropbox)
         */
        provider: string;
    };
    query?: never;
    url: '/auth/oauth/{provider}/exchange';
};

export type PostAuthOauthByProviderExchangeErrors = {
    /**
     * Bad Request
     */
    400: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type PostAuthOauthByProviderExchangeError = PostAuthOauthByProviderExchangeErrors[keyof PostAuthOauthByProviderExchangeErrors];

export type PostAuthOauthByProviderExchangeResponses = {
    /**
     * OK
     */
    200: HandlersTokenResponse;
};

export type PostAuthOauthByProviderExchangeResponse = PostAuthOauthByProviderExchangeResponses[keyof PostAuthOauthByProviderExchangeResponses];

export type PostAuthOauthByProviderRefreshData = {
    /**
     * Refresh request
     */
    body: HandlersRefreshRequest;
    path: {
        /**
         * OAuth provider (google-drive, dropbox)
         */
        provider: string;
    };
    query?: never;
    url: '/auth/oauth/{provider}/refresh';
};

export type PostAuthOauthByProviderRefreshErrors = {
    /**
     * Bad Request
     */
    400: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type PostAuthOauthByProviderRefreshError = PostAuthOauthByProviderRefreshErrors[keyof PostAuthOauthByProviderRefreshErrors];

export type PostAuthOauthByProviderRefreshResponses = {
    /**
     * OK
     */
    200: HandlersTokenResponse;
};

export type PostAuthOauthByProviderRefreshResponse = PostAuthOauthByProviderRefreshResponses[keyof PostAuthOauthByProviderRefreshResponses];

export type PostAuthOauthByProviderRevokeData = {
    /**
     * Revoke request
     */
    body: HandlersRevokeRequest;
    path: {
        /**
         * OAuth provider (google-drive, dropbox)
         */
        provider: string;
    };
    query?: never;
    url: '/auth/oauth/{provider}/revoke';
};

export type PostAuthOauthByProviderRevokeErrors = {
    /**
     * Bad Request
     */
    400: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type PostAuthOauthByProviderRevokeError = PostAuthOauthByProviderRevokeErrors[keyof PostAuthOauthByProviderRevokeErrors];

export type PostAuthOauthByProviderRevokeResponses = {
    /**
     * Empty object on success
     */
    200: {
        [key: string]: unknown;
    };
};

export type PostAuthOauthByProviderRevokeResponse = PostAuthOauthByProviderRevokeResponses[keyof PostAuthOauthByProviderRevokeResponses];

export type PostDeveloperAppsByAppUuidFundData = {
    /**
     * Fund request
     */
    body: HandlersFundDeveloperAppRequest;
    path: {
        /**
         * App UUID
         */
        app_uuid: string;
    };
    query?: never;
    url: '/developer/apps/{app_uuid}/fund';
};

export type PostDeveloperAppsByAppUuidFundErrors = {
    /**
     * Bad Request
     */
    400: ResponseErrorResponse;
    /**
     * Unauthorized
     */
    401: ResponseErrorResponse;
    /**
     * Forbidden
     */
    403: ResponseErrorResponse;
    /**
     * Not Found
     */
    404: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type PostDeveloperAppsByAppUuidFundError = PostDeveloperAppsByAppUuidFundErrors[keyof PostDeveloperAppsByAppUuidFundErrors];

export type PostDeveloperAppsByAppUuidFundResponses = {
    /**
     * OK
     */
    200: HandlersCheckoutSessionResponse;
};

export type PostDeveloperAppsByAppUuidFundResponse = PostDeveloperAppsByAppUuidFundResponses[keyof PostDeveloperAppsByAppUuidFundResponses];

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthErrors = {
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type GetHealthError = GetHealthErrors[keyof GetHealthErrors];

export type GetHealthResponses = {
    /**
     * OK
     */
    200: HandlersHealthResponse;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];
