// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type HandlersHealthResponse = {
    /**
     * Status indicates the service health status
     */
    status?: string;
    /**
     * Timestamp is the Unix timestamp of the response
     */
    timestamp?: number;
    /**
     * Version is the current API version
     */
    version?: string;
};

/**
 * ExtraFields contains additional metadata
 */
export type LlmapiChatCompletionExtraFields = {
    /**
     * Latency is the request latency in milliseconds
     */
    latency?: number;
    /**
     * ModelRequested is the model that was requested
     */
    model_requested?: string;
    /**
     * Provider is the LLM provider used (e.g., "openai", "anthropic")
     */
    provider?: string;
    /**
     * RequestType is always "chat_completion"
     */
    request_type?: string;
};

export type LlmapiChatCompletionRequest = {
    /**
     * Messages is the conversation history
     */
    messages?: Array<LlmapiMessage>;
    /**
     * Model is the model identifier
     */
    model?: string;
    /**
     * Stream indicates if response should be streamed
     */
    stream?: boolean;
};

export type LlmapiChatCompletionResponse = {
    /**
     * Choices contains the completion choices
     */
    choices?: Array<LlmapiChoice>;
    extra_fields?: LlmapiChatCompletionExtraFields;
    /**
     * ID is the completion ID
     */
    id?: string;
    /**
     * Model is the model used
     */
    model?: string;
    usage?: LlmapiChatCompletionUsage;
};

/**
 * Usage contains token usage information
 */
export type LlmapiChatCompletionUsage = {
    /**
     * CompletionTokens is the number of tokens in the completion
     */
    completion_tokens?: number;
    /**
     * PromptTokens is the number of tokens in the prompt
     */
    prompt_tokens?: number;
    /**
     * TotalTokens is the total number of tokens used
     */
    total_tokens?: number;
};

export type LlmapiChoice = {
    /**
     * FinishReason indicates why the completion stopped
     */
    finish_reason?: string;
    /**
     * Index is the choice index
     */
    index?: number;
    message?: LlmapiMessage;
};

export type LlmapiEmbeddingData = {
    /**
     * Embedding vector
     */
    embedding?: Array<number>;
    /**
     * Index of the embedding
     */
    index?: number;
    /**
     * Object type identifier
     */
    object?: string;
};

/**
 * ExtraFields contains additional metadata
 */
export type LlmapiEmbeddingExtraFields = {
    /**
     * ChunkIndex is the chunk index (0 for single requests)
     */
    chunk_index?: number;
    /**
     * Latency is the request latency in milliseconds
     */
    latency?: number;
    /**
     * ModelRequested is the model that was requested
     */
    model_requested?: string;
    /**
     * Provider is the LLM provider used (e.g., "openai", "anthropic")
     */
    provider?: string;
    /**
     * RequestType is always "embedding"
     */
    request_type?: string;
};

export type LlmapiEmbeddingRequest = {
    /**
     * Dimensions is the number of dimensions the resulting output embeddings should have (optional)
     */
    dimensions?: number;
    /**
     * EncodingFormat is the format to return the embeddings in (optional: "float" or "base64")
     */
    encoding_format?: string;
    /**
     * Input text or tokens to embed (can be string, []string, []int, or [][]int)
     */
    input?: unknown;
    /**
     * Model identifier in 'provider/model' format
     */
    model?: string;
};

export type LlmapiEmbeddingResponse = {
    /**
     * Data contains the embeddings
     */
    data?: Array<LlmapiEmbeddingData>;
    extra_fields?: LlmapiEmbeddingExtraFields;
    /**
     * Model is the model used
     */
    model?: string;
    /**
     * Object is always "list"
     */
    object?: string;
    usage?: LlmapiEmbeddingUsage;
};

/**
 * Usage contains token usage information
 */
export type LlmapiEmbeddingUsage = {
    /**
     * PromptTokens is the number of tokens in the prompt
     */
    prompt_tokens?: number;
    /**
     * TotalTokens is the total number of tokens used
     */
    total_tokens?: number;
};

/**
 * Message is the generated message
 */
export type LlmapiMessage = {
    /**
     * Content is the message content
     */
    content?: string;
    role?: LlmapiRole;
};

export type LlmapiModel = {
    architecture?: LlmapiModelArchitecture;
    /**
     * CanonicalSlug is the canonical slug for the model
     */
    canonical_slug?: string;
    /**
     * ContextLength is the maximum context length in tokens
     */
    context_length?: number;
    /**
     * Created is the Unix timestamp of when the model was created
     */
    created?: number;
    /**
     * DefaultParameters contains default parameter values
     */
    default_parameters?: {
        [key: string]: unknown;
    };
    /**
     * Description describes the model and its capabilities
     */
    description?: string;
    /**
     * HuggingFaceID is the Hugging Face model identifier
     */
    hugging_face_id?: string;
    /**
     * ID is the model identifier (e.g., "openai/gpt-4")
     */
    id?: string;
    /**
     * MaxInputTokens is the maximum input tokens
     */
    max_input_tokens?: number;
    /**
     * MaxOutputTokens is the maximum output tokens
     */
    max_output_tokens?: number;
    /**
     * Name is the human-readable model name (optional)
     */
    name?: string;
    /**
     * OwnedBy is the organization that owns the model
     */
    owned_by?: string;
    per_request_limits?: LlmapiModelPerRequestLimits;
    pricing?: LlmapiModelPricing;
    /**
     * SupportedMethods is a list of supported API methods
     */
    supported_methods?: Array<string>;
    /**
     * SupportedParameters is a list of supported parameter names
     */
    supported_parameters?: Array<string>;
    top_provider?: LlmapiModelTopProvider;
};

/**
 * Architecture describes the model's technical capabilities
 */
export type LlmapiModelArchitecture = {
    instruct_type?: string;
    modality?: string;
    prompt_formatting?: string;
    tokenizer?: string;
};

/**
 * PerRequestLimits contains rate limiting information
 */
export type LlmapiModelPerRequestLimits = {
    completion_tokens?: number;
    prompt_tokens?: number;
};

/**
 * Pricing contains the pricing structure for using this model
 */
export type LlmapiModelPricing = {
    completion?: string;
    image?: string;
    prompt?: string;
    request?: string;
};

/**
 * TopProvider contains configuration details for the primary provider
 */
export type LlmapiModelTopProvider = {
    context_length?: number;
    is_moderated?: boolean;
    max_completion_tokens?: number;
};

/**
 * ExtraFields contains additional metadata
 */
export type LlmapiModelsListExtraFields = {
    /**
     * ChunkIndex is the chunk index (0 for single requests)
     */
    chunk_index?: number;
    /**
     * Latency is the request latency in milliseconds
     */
    latency?: number;
    /**
     * RequestType is always "list_models"
     */
    request_type?: string;
};

export type LlmapiModelsListResponse = {
    /**
     * Data contains the list of available models
     */
    data?: Array<LlmapiModel>;
    extra_fields?: LlmapiModelsListExtraFields;
    /**
     * NextPageToken is the token to retrieve the next page of results (omitted if no more pages)
     */
    next_page_token?: string;
};

/**
 * Role is the message role (system, user, assistant)
 */
export type LlmapiRole = string;

export type ResponseErrorResponse = {
    error?: string;
};

export type PostApiV1ChatCompletionsData = {
    /**
     * Chat completion request
     */
    body: LlmapiChatCompletionRequest;
    path?: never;
    query?: never;
    url: '/api/v1/chat/completions';
};

export type PostApiV1ChatCompletionsErrors = {
    /**
     * Bad Request
     */
    400: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type PostApiV1ChatCompletionsError = PostApiV1ChatCompletionsErrors[keyof PostApiV1ChatCompletionsErrors];

export type PostApiV1ChatCompletionsResponses = {
    /**
     * OK
     */
    200: LlmapiChatCompletionResponse | string;
};

export type PostApiV1ChatCompletionsResponse = PostApiV1ChatCompletionsResponses[keyof PostApiV1ChatCompletionsResponses];

export type PostApiV1EmbeddingsData = {
    /**
     * Embedding request
     */
    body: LlmapiEmbeddingRequest;
    path?: never;
    query?: never;
    url: '/api/v1/embeddings';
};

export type PostApiV1EmbeddingsErrors = {
    /**
     * Bad Request
     */
    400: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type PostApiV1EmbeddingsError = PostApiV1EmbeddingsErrors[keyof PostApiV1EmbeddingsErrors];

export type PostApiV1EmbeddingsResponses = {
    /**
     * OK
     */
    200: LlmapiEmbeddingResponse;
};

export type PostApiV1EmbeddingsResponse = PostApiV1EmbeddingsResponses[keyof PostApiV1EmbeddingsResponses];

export type GetApiV1ModelsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by provider (e.g., openai, anthropic)
         */
        provider?: string;
        /**
         * Number of models to return per page
         */
        page_size?: number;
        /**
         * Token to get next page of results
         */
        page_token?: string;
    };
    url: '/api/v1/models';
};

export type GetApiV1ModelsErrors = {
    /**
     * Bad Request
     */
    400: ResponseErrorResponse;
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type GetApiV1ModelsError = GetApiV1ModelsErrors[keyof GetApiV1ModelsErrors];

export type GetApiV1ModelsResponses = {
    /**
     * OK
     */
    200: LlmapiModelsListResponse;
};

export type GetApiV1ModelsResponse = GetApiV1ModelsResponses[keyof GetApiV1ModelsResponses];

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthErrors = {
    /**
     * Internal Server Error
     */
    500: ResponseErrorResponse;
};

export type GetHealthError = GetHealthErrors[keyof GetHealthErrors];

export type GetHealthResponses = {
    /**
     * OK
     */
    200: HandlersHealthResponse;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];
